Repository nextcloud/talk-android, pull requests merged in 2020-10, with the labels that each got.

#897 Improves visiblity of text and URLs in chat view.
  app/src/main/java/com/nextcloud/talk/newarch/features/chat/ChatPresenter.kt
  app/src/main/res/layout/item_message_quote.xml
  app/src/main/res/layout/rv_chat_item.xml
  app/src/main/res/values-night/colors.xml
  app/src/main/res/values/colors.xml
Labels: approved

#904 [v8.0.x] Fix some issues related to guest participants
  app/src/main/java/com/nextcloud/talk/controllers/CallController.java
  app/src/main/java/com/nextcloud/talk/webrtc/MagicPeerConnectionWrapper.java
  app/src/main/java/com/nextcloud/talk/webrtc/MagicWebSocketInstance.java
Labels: 3. to review, bug

#905 [v8.0.x] Fix frozen video when screen is shared
  app/src/main/java/com/nextcloud/talk/webrtc/MagicPeerConnectionWrapper.java
Labels: 3. to review, bug

#903 use new versionCode
  app/build.gradle
Labels: 3. to review

#912 Chat during call
  .idea/misc.xml
  .idea/modules.xml
  app/build.gradle
  app/src/main/java/com/nextcloud/talk/activities/MagicCallActivity.kt
  app/src/main/java/com/nextcloud/talk/controllers/CallController.java
  app/src/main/java/com/nextcloud/talk/controllers/ChatController.kt
  app/src/main/java/com/nextcloud/talk/jobs/NotificationWorker.java
  app/src/main/res/drawable/ic_chat_black_24dp.xml
  app/src/main/res/drawable/ic_comment.xml
  app/src/main/res/layout/activity_magic_call.xml
  app/src/main/res/layout/controller_call.xml
  app/src/main/res/layout/controller_chat.xml
  app/src/main/res/values/colors.xml
Labels: 3. to review

#911 Add branding support
  app/src/main/java/com/nextcloud/talk/activities/BaseActivity.kt
  app/src/main/java/com/nextcloud/talk/activities/MainActivity.kt
  app/src/main/java/com/nextcloud/talk/adapters/items/UserItem.java
  app/src/main/java/com/nextcloud/talk/adapters/messages/MagicIncomingTextMessageViewHolder.kt
  app/src/main/java/com/nextcloud/talk/adapters/messages/MagicOutcomingTextMessageViewHolder.kt
  app/src/main/java/com/nextcloud/talk/adapters/messages/MagicSystemMessageViewHolder.java
  app/src/main/java/com/nextcloud/talk/controllers/ServerSelectionController.java
  app/src/main/java/com/nextcloud/talk/controllers/SettingsController.java
  app/src/main/res/drawable/accent_circle.xml
  app/src/main/res/drawable/ic_logo.xml
  app/src/main/res/layout/controller_chat.xml
  app/src/main/res/layout/controller_conversation_info.xml
  app/src/main/res/layout/controller_conversations_rv.xml
  app/src/main/res/layout/controller_server_selection.xml
  app/src/main/res/layout/controller_settings.xml
  app/src/main/res/layout/item_custom_incoming_text_message.xml
  app/src/main/res/layout/item_system_message.xml
  app/src/main/res/layout/notification_settings_item.xml
  app/src/main/res/layout/rv_item_conversation_info_participant.xml
  app/src/main/res/layout/rv_item_conversation_with_last_message.xml
  app/src/main/res/layout/rv_item_mention.xml
  app/src/main/res/values-night/colors.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/setup.xml
  app/src/main/res/values/styles.xml
  app/src/main/res/xml/chip_others.xml
  app/src/main/res/xml/chip_you.xml
Labels: 3. to review

#907 [v8.0.x] Fix data channel suport with newer Janus versions
  app/src/main/java/com/nextcloud/talk/webrtc/MagicPeerConnectionWrapper.java
Labels: 3. to review, bug

#923 Add missing import
  .idea/misc.xml
  app/src/main/java/com/nextcloud/talk/newarch/features/chat/ChatView.kt
Labels: 3. to review
