Repository nextcloud/talk-android, pull requests merged in 2021-04, with the labels that each got.

#1101 Remove "Nextcloud" hardcoding
  app/src/main/java/com/nextcloud/talk/controllers/CallController.java
  app/src/main/java/com/nextcloud/talk/models/database/User.java
  app/src/main/java/com/nextcloud/talk/models/json/capabilities/ThemingCapability.java
  app/src/main/java/com/nextcloud/talk/ui/dialog/AttachmentDialog.kt
  app/src/main/res/layout/dialog_attachment.xml
  app/src/main/res/values/strings.xml
Labels: 3. to review

#1100 On Recyclerview everything needs to be set explicitly
  app/src/main/java/com/nextcloud/talk/adapters/items/ConversationItem.java
Labels: 3. to review

#1097 Introduce SearchBar/Toolbar in dark/light design
  CHANGELOG.md
  app/src/main/java/com/nextcloud/talk/activities/MainActivity.kt
  app/src/main/java/com/nextcloud/talk/controllers/ConversationsListController.java
  app/src/main/java/com/nextcloud/talk/controllers/ServerSelectionController.java
  app/src/main/java/com/nextcloud/talk/controllers/SettingsController.java
  app/src/main/java/com/nextcloud/talk/controllers/WebViewLoginController.java
  app/src/main/java/com/nextcloud/talk/controllers/base/BaseController.java
  app/src/main/java/com/nextcloud/talk/jobs/NotificationWorker.java
  app/src/main/java/com/nextcloud/talk/utils/DisplayUtils.java
  app/src/main/res/animator/appbar_elevation_off.xml
  app/src/main/res/animator/appbar_elevation_on.xml
  app/src/main/res/drawable-night/ic_close_search.xml
  app/src/main/res/drawable/ic_close_search.xml
  app/src/main/res/drawable/ic_menu.xml
  app/src/main/res/drawable/ic_search_grey.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/controller_account_verification.xml
  app/src/main/res/layout/controller_browser.xml
  app/src/main/res/layout/controller_call.xml
  app/src/main/res/layout/controller_call_menu.xml
  app/src/main/res/layout/controller_chat.xml
  app/src/main/res/layout/controller_entry_menu.xml
  app/src/main/res/layout/controller_generic_rv.xml
  app/src/main/res/layout/controller_locked.xml
  app/src/main/res/layout/controller_operations_menu.xml
  app/src/main/res/layout/rv_item_app.xml
  app/src/main/res/layout/rv_item_browser_file.xml
  app/src/main/res/layout/search_layout.xml
  app/src/main/res/menu/menu_conversation_plus_filter.xml
  app/src/main/res/values-night/colors.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
  scripts/analysis/lint-results.txt
Labels: 3. to review, design

#1113 l10n: Correct spelling
  app/src/main/res/values/strings.xml
Labels: 3. to review

#1111 Toolbar/list-item/preferences alignments
  CHANGELOG.md
  app/src/main/java/com/nextcloud/talk/controllers/ConversationInfoController.kt
  app/src/main/java/com/nextcloud/talk/controllers/ProfileController.java
  app/src/main/java/com/nextcloud/talk/utils/ui/MaterialPreferenceCategoryWithRightLink.java
  app/src/main/res/drawable/ic_account_plus.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/category_with_right_action.xml
  app/src/main/res/layout/controller_conversation_info.xml
  app/src/main/res/layout/controller_settings.xml
  app/src/main/res/layout/conversation_privacy_toggle.xml
  app/src/main/res/layout/dialog_attachment.xml
  app/src/main/res/layout/join_conversation_via_link.xml
  app/src/main/res/layout/notification_settings_item.xml
  app/src/main/res/layout/rv_item_contact.xml
  app/src/main/res/layout/rv_item_conversation.xml
  app/src/main/res/layout/rv_item_notification_sound.xml
  app/src/main/res/layout/rv_item_title_header.xml
  app/src/main/res/layout/user_info_details_table_item.xml
  app/src/main/res/layout/webinar_info_item.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: 3. to review, design

#1115 Backport/enhance login screen
  CHANGELOG.md
  app/src/main/java/com/nextcloud/talk/controllers/ServerSelectionController.java
  app/src/main/res/drawable/ic_warning_white.xml
  app/src/main/res/layout/controller_server_selection.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: 3. to review, design

#1116 Update empty conversations screen and added shimmer effect
  app/src/main/java/com/nextcloud/talk/controllers/ConversationsListController.java
  app/src/main/res/layout/controller_conversations_rv.xml
  app/src/main/res/layout/lobby_view.xml
  app/src/main/res/layout/rv_item_conversation_with_last_message_shimmer.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values/strings.xml
  scripts/analysis/lint-results.txt
Labels: 3. to review, design

#1120 Add space between avatar and title in toolbar
  app/src/main/java/com/nextcloud/talk/controllers/ChatController.kt
  app/src/main/java/com/nextcloud/talk/controllers/ConversationInfoController.kt
  app/src/main/java/com/nextcloud/talk/utils/bundle/BundleKeys.kt
Labels: 3. to review

#1121 Lib updates
  app/build.gradle
  scripts/analysis/lint-results.txt
Labels: 3. to review

#1124 Unify (and update) dagger dependency version code(s)
  app/build.gradle
Labels: 3. to review

#1132 Add splash screen to Talk App
  app/src/gplay/AndroidManifest.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/nextcloud/talk/activities/MainActivity.kt
  app/src/main/res/drawable/launch_screen.xml
  app/src/main/res/values/styles.xml
Labels: 3. to review

#1130 Accessibility participants list and grey tones
  app/src/main/java/com/nextcloud/talk/adapters/items/UserItem.java
  app/src/main/java/com/nextcloud/talk/controllers/ConversationInfoController.kt
  app/src/main/java/com/nextcloud/talk/controllers/ProfileController.java
  app/src/main/java/com/nextcloud/talk/models/json/conversations/Conversation.java
  app/src/main/java/com/nextcloud/talk/models/json/converters/EnumParticipantTypeConverter.java
  app/src/main/java/com/nextcloud/talk/models/json/participants/Participant.java
  app/src/main/res/layout/controller_conversation_info.xml
  app/src/main/res/layout/controller_profile.xml
  app/src/main/res/layout/controller_settings.xml
  app/src/main/res/layout/rv_item_conversation_info_participant.xml
  app/src/main/res/layout/rv_item_conversation_with_last_message.xml
  app/src/main/res/layout/rv_item_mention.xml
  app/src/main/res/layout/search_layout.xml
  app/src/main/res/layout/user_info_details_table_item.xml
  app/src/main/res/values-night/colors.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/styles.xml
  app/src/main/res/xml/chip_others.xml
Labels: 3. to review, accessibility, bug, design

#1133 Optimize chat input separator for dark theme + message quote optimizations
  app/src/main/java/com/nextcloud/talk/adapters/messages/MagicIncomingTextMessageViewHolder.kt
  app/src/main/java/com/nextcloud/talk/adapters/messages/MagicOutcomingTextMessageViewHolder.kt
  app/src/main/java/com/nextcloud/talk/controllers/ChatController.kt
  app/src/main/res/layout/controller_chat.xml
  app/src/main/res/layout/dialog_scope.xml
  app/src/main/res/layout/item_message_quote.xml
  app/src/main/res/layout/rv_item_browser_file.xml
  app/src/main/res/layout/rv_item_conversation.xml
  app/src/main/res/layout/rv_item_conversation_info_participant.xml
  app/src/main/res/layout/rv_item_conversation_with_last_message.xml
  app/src/main/res/values-night/colors.xml
  app/src/main/res/values/strings.xml
  scripts/analysis/lint-results.txt
Labels: 3. to review, design

#1153 don't keep screen enabled in chat
  CHANGELOG.md
  app/src/main/res/layout/controller_chat.xml
Labels: 2. developing

#1164 Enable enlarging the image more than default 3x maximumScale.
  app/src/main/java/com/nextcloud/talk/activities/FullScreenImageActivity.kt
Labels: 3. to review

#1141 Optimize Shimmer and upload bottom sheet
  app/src/main/java/com/nextcloud/talk/adapters/items/NotificationSoundItem.java
  app/src/main/java/com/nextcloud/talk/controllers/ContactsController.java
  app/src/main/java/com/nextcloud/talk/controllers/ConversationsListController.java
  app/src/main/res/drawable/ic_play_circle_outline_white_24dp.xml
  app/src/main/res/drawable/ic_share_variant.xml
  app/src/main/res/drawable/ic_stop_white_24dp.xml
  app/src/main/res/layout/controller_entry_menu.xml
  app/src/main/res/layout/dialog_attachment.xml
  app/src/main/res/layout/item_custom_outcoming_text_message.xml
  app/src/main/res/layout/rv_item_conversation_with_last_message_shimmer.xml
  app/src/main/res/layout/rv_item_notification_sound.xml
  app/src/main/res/layout/user_info_details_table_item_shimmer.xml
  app/src/main/res/values-night/colors.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: 3. to review, design

#1149 Make sure "unread messages" bubble text is always white
  app/src/main/res/layout/controller_chat.xml
Labels: 3. to review, design

#1147 Optimize lock-screen layout/colors
  app/build.gradle
  app/src/main/java/com/nextcloud/talk/controllers/LockedController.java
  app/src/main/res/layout/controller_locked.xml
  app/src/main/res/layout/item_message_quote.xml
  app/src/main/res/values-night/colors.xml
  scripts/analysis/lint-results.txt
Labels: 3. to review, design

#1155 jsr250 lib has moved from annotation to annotation-api
  app/build.gradle
  build.gradle
Labels: 3. to review, technical debt

#1154 Bump coil to 1.2.0
  app/build.gradle
  app/src/main/java/com/nextcloud/talk/adapters/messages/MagicIncomingTextMessageViewHolder.kt
  app/src/main/java/com/nextcloud/talk/adapters/messages/MagicOutcomingTextMessageViewHolder.kt
  app/src/main/java/com/nextcloud/talk/application/NextcloudTalkApplication.kt
  app/src/main/java/com/nextcloud/talk/controllers/ChatController.kt
Labels: 3. to review, technical debt

#1146 Unify parceler version(s)
  app/build.gradle
Labels: 3. to review, technical debt

#1142 Support delete-multiple push notification
  app/src/gplay/java/com/nextcloud/talk/services/firebase/MagicFirebaseMessagingService.kt
  app/src/main/java/com/nextcloud/talk/jobs/NotificationWorker.java
  app/src/main/java/com/nextcloud/talk/models/json/push/DecryptedPushMessage.java
  scripts/analysis/findbugs-results.txt
  spotbugs-filter.xml
Labels: 3. to review, enhancement

#1207 Align contact category headlines
  app/src/main/res/layout/rv_item_title_header.xml
Labels: 3. to review, design
