Repository nextcloud/talk-android, pull requests merged in 2021-07, with the labels that each got.

#1380 Shortened launcher label
  app/src/main/java/com/nextcloud/talk/controllers/AccountVerificationController.java
  app/src/main/java/com/nextcloud/talk/controllers/CallController.java
  app/src/main/java/com/nextcloud/talk/controllers/CallNotificationController.java
  app/src/main/java/com/nextcloud/talk/controllers/ChatController.kt
  app/src/main/java/com/nextcloud/talk/controllers/ContactsController.java
  app/src/main/java/com/nextcloud/talk/controllers/ConversationsListController.java
  app/src/main/java/com/nextcloud/talk/controllers/LockedController.kt
  app/src/main/java/com/nextcloud/talk/controllers/ServerSelectionController.java
  app/src/main/java/com/nextcloud/talk/controllers/SettingsController.java
  app/src/main/java/com/nextcloud/talk/controllers/WebViewLoginController.java
  app/src/main/java/com/nextcloud/talk/controllers/base/BaseController.java
  app/src/main/java/com/nextcloud/talk/controllers/base/NewBaseController.kt
  app/src/main/java/com/nextcloud/talk/controllers/bottomsheet/CallMenuController.java
  app/src/main/java/com/nextcloud/talk/dagger/modules/DatabaseModule.java
  app/src/main/java/com/nextcloud/talk/jobs/ContactAddressBookWorker.kt
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/controller_conversations_rv.xml
  app/src/main/res/layout/controller_locked.xml
  app/src/main/res/layout/controller_server_selection.xml
  app/src/main/res/layout/controller_settings.xml
  app/src/main/res/values/setup.xml
  app/src/main/res/xml/auth.xml
  app/src/qa/res/values/setup.xml
Labels: 3. to review, backport-request

#1387 Bugfix/1308/improve grid view design
  app/src/main/java/com/nextcloud/talk/adapters/ParticipantsAdapter.java
  app/src/main/java/com/nextcloud/talk/controllers/CallController.java
  app/src/main/res/layout/call_item.xml
  app/src/main/res/layout/controller_call.xml
  app/src/main/res/values/dimens.xml
  scripts/analysis/findbugs-results.txt
Labels: 3. to review

#1114 Fix own peer handling when HPB is used
  app/src/main/java/com/nextcloud/talk/controllers/CallController.java
Labels: 3. to review, bug

#1394 set locationName to "Shared location" when geocoding failed
  app/src/main/java/com/nextcloud/talk/controllers/LocationPickerController.kt
  app/src/main/res/values/strings.xml
Labels: 3. to review, bug, feature: 🤝 sharing

#1396 fix to expand attachment menu in landscape mode
  app/src/main/java/com/nextcloud/talk/ui/dialog/AttachmentDialog.kt
Labels: 3. to review, backport-request, bug, feature: 🤝 sharing

#1401 Raise size of clickable-text areas
  app/src/main/res/layout/controller_server_selection.xml
  app/src/main/res/values/dimens.xml
Labels: 3. to review, backport-request

#1403 Unbreak translations
  app/src/main/res/values/strings.xml
Labels: 3. to review, don't merge

#1418 Add missing .editorconfig
  .editorconfig
Labels: 3. to review

#1423 Only parse baseURl if not empty
  app/src/main/java/com/nextcloud/talk/adapters/items/AdvancedUserItem.java
Labels: 3. to review, backport-request

#1425 Binding can be null due to async call
  app/src/main/java/com/nextcloud/talk/controllers/ConversationInfoController.kt
Labels: 3. to review, backport-request

#1434 Fix call notifications
  app/src/gplay/java/com/nextcloud/talk/services/firebase/MagicFirebaseMessagingService.kt
Labels: 3. to review, backport-request, bug, feature: ☎️ call, feature: 🔔 notifications

#1420 Use launcher icon as bot-avatar/system-conversation-icon
  app/build.gradle
  app/src/main/java/com/nextcloud/talk/adapters/items/ConversationItem.java
  app/src/main/java/com/nextcloud/talk/adapters/messages/IncomingVoiceMessageViewHolder.kt
  app/src/main/java/com/nextcloud/talk/adapters/messages/MagicIncomingTextMessageViewHolder.kt
  app/src/main/java/com/nextcloud/talk/components/filebrowser/webdav/ReadFilesystemOperation.java
  app/src/main/java/com/nextcloud/talk/utils/database/user/UserUtils.java
  scripts/analysis/lint-results.txt
Labels: 3. to review, backport-request, feature: 📄 conversations

#1442 Fix capability check for 14-18
  app/src/main/java/com/nextcloud/talk/utils/ApiUtils.java
Labels: 3. to review, backport-request, bug, feature: 📄 conversations

#1444 Fix the check if user joined on another device
  app/src/gplay/java/com/nextcloud/talk/services/firebase/MagicFirebaseMessagingService.kt
Labels: 3. to review, backport-request, bug, feature: ☎️ call

#1449 update changelog for 12.1.1
  CHANGELOG.md
Labels: backport-request

#1451 Share from a browser should share the page URL
  app/src/main/java/com/nextcloud/talk/controllers/ConversationsListController.java
Labels: 3. to review, backport-request, bug

#1457 remove logo dimensions for sever selection screen
  app/src/main/res/layout/controller_server_selection.xml
Labels: backport-request

#1432 Handle async call back to already destroyed UI
  app/src/main/java/com/nextcloud/talk/controllers/ChatController.kt
Labels: 3. to review, backport-request, feature: 🗨️ chat

#1455 [stable-12.1] Bump spotbugs-gradle-plugin from 4.7.1 to 4.7.2
  build.gradle
  scripts/analysis/findbugs-results.txt
Labels: 3. to review

#1459 Base url can be null
  app/src/main/java/com/nextcloud/talk/controllers/ProfileController.java
Labels: 3. to review, backport-request

#1462 Add item background for popup menu items
  app/src/main/res/values/styles.xml
Labels: 3. to review, backport-request

#1466 Make links clickable in conversation description
  app/src/main/res/layout/controller_conversation_info.xml
Labels: 3. to review, backport-request

#1470 Bugfix/1167/posting a local link hides the information
  app/build.gradle
  app/src/main/java/com/nextcloud/talk/models/json/chat/ChatMessage.java
  app/src/main/java/com/nextcloud/talk/utils/TextMatchers.java
  app/src/test/java/com/nextcloud/talk/utils/TextMatchersTest.java
  scripts/analysis/findbugs-results.txt
Labels: 3. to review, backport-request

#1471 [stable-12.1] Bugfix/1167/posting a local link hides the information
  app/build.gradle
  app/src/main/java/com/nextcloud/talk/models/json/chat/ChatMessage.java
  app/src/main/java/com/nextcloud/talk/utils/TextMatchers.java
  app/src/test/java/com/nextcloud/talk/utils/TextMatchersTest.java
  scripts/analysis/findbugs-results.txt
Labels: 3. to review

#1475 Add new system message types
  app/src/main/java/com/nextcloud/talk/models/json/chat/ChatMessage.java
  app/src/main/java/com/nextcloud/talk/models/json/converters/EnumSystemMessageTypeConverter.kt
Labels: 3. to review

#1482 remove hardcoded api version for location sharing
  app/src/main/java/com/nextcloud/talk/controllers/LocationPickerController.kt
  app/src/main/java/com/nextcloud/talk/utils/ApiUtils.java
Labels: 3. to review

#1484 Manual backport for #1472
  app/src/main/java/com/nextcloud/talk/controllers/ChatController.kt
  app/src/main/java/com/nextcloud/talk/controllers/SettingsController.java
  app/src/main/java/com/nextcloud/talk/dagger/modules/DatabaseModule.java
  app/src/main/java/com/nextcloud/talk/models/json/chat/ChatMessage.java
  app/src/main/java/com/nextcloud/talk/utils/preferences/AppPreferences.java
  app/src/main/res/layout/controller_settings.xml
  app/src/main/res/values/strings.xml
Labels: 3. to review

#1480 add ability to clear chat history
  app/src/main/java/com/nextcloud/talk/api/NcApi.java
  app/src/main/java/com/nextcloud/talk/controllers/ChatController.kt
  app/src/main/java/com/nextcloud/talk/controllers/ConversationInfoController.kt
  app/src/main/java/com/nextcloud/talk/models/json/chat/ChatMessage.java
  app/src/main/java/com/nextcloud/talk/models/json/converters/EnumSystemMessageTypeConverter.kt
  app/src/main/res/layout/controller_conversation_info.xml
  app/src/main/res/values/strings.xml
Labels: 3. to review

#1483 Improve RTL text flow for untranslated strings in rtl languages/views
  app/src/main/res/layout/account_item.xml
  app/src/main/res/layout/activity_full_screen_media.xml
  app/src/main/res/layout/activity_full_screen_text.xml
  app/src/main/res/layout/call_item.xml
  app/src/main/res/layout/controller_entry_menu.xml
  app/src/main/res/layout/controller_location.xml
  app/src/main/res/layout/controller_server_selection.xml
  app/src/main/res/layout/controller_settings.xml
  app/src/main/res/layout/conversation_privacy_toggle.xml
  app/src/main/res/layout/dialog_attachment.xml
  app/src/main/res/layout/dialog_scope.xml
  app/src/main/res/layout/geocoding_item.xml
  app/src/main/res/layout/item_custom_incoming_location_message.xml
  app/src/main/res/layout/item_custom_incoming_preview_message.xml
  app/src/main/res/layout/item_custom_incoming_text_message.xml
  app/src/main/res/layout/item_custom_incoming_voice_message.xml
  app/src/main/res/layout/item_custom_outcoming_location_message.xml
  app/src/main/res/layout/item_custom_outcoming_preview_message.xml
  app/src/main/res/layout/item_custom_outcoming_text_message.xml
  app/src/main/res/layout/item_message_quote.xml
  app/src/main/res/layout/join_conversation_via_link.xml
  app/src/main/res/layout/library_fast_scroller_layout.xml
  app/src/main/res/layout/rv_item_app.xml
  app/src/main/res/layout/rv_item_browser_file.xml
  app/src/main/res/layout/rv_item_contact.xml
  app/src/main/res/layout/rv_item_conversation.xml
  app/src/main/res/layout/rv_item_conversation_info_participant.xml
  app/src/main/res/layout/rv_item_conversation_with_last_message.xml
  app/src/main/res/layout/rv_item_mention.xml
  app/src/main/res/layout/rv_item_menu.xml
  app/src/main/res/layout/rv_item_notification_sound.xml
  app/src/main/res/layout/rv_item_title_header.xml
  app/src/main/res/layout/search_layout.xml
  app/src/main/res/layout/view_message_input.xml
  scripts/analysis/lint-results.txt
Labels: 3. to review

#1492 Forwarding chat messages
  app/src/main/java/com/nextcloud/talk/activities/MainActivity.kt
  app/src/main/java/com/nextcloud/talk/adapters/messages/MagicPreviewMessageViewHolder.java
  app/src/main/java/com/nextcloud/talk/controllers/AccountVerificationController.java
  app/src/main/java/com/nextcloud/talk/controllers/ChatController.kt
  app/src/main/java/com/nextcloud/talk/controllers/ConversationsListController.java
  app/src/main/java/com/nextcloud/talk/utils/bundle/BundleKeys.kt
  app/src/main/res/drawable/ic_share_action.xml
  app/src/main/res/menu/chat_message_menu.xml
  app/src/main/res/values/strings.xml
Labels: 3. to review
