Repository nextcloud/talk-android, pull requests merged in 2021-06, with the labels that each got.

#1304 Improve Preview Screens
  app/src/main/java/com/nextcloud/talk/activities/FullScreenImageActivity.kt
  app/src/main/java/com/nextcloud/talk/activities/FullScreenMediaActivity.kt
  app/src/main/java/com/nextcloud/talk/activities/FullScreenTextViewerActivity.kt
  app/src/main/res/layout/activity_full_screen_image.xml
  app/src/main/res/layout/activity_full_screen_media.xml
  app/src/main/res/layout/activity_full_screen_text.xml
  app/src/main/res/values/styles.xml
  scripts/analysis/lint-results.txt
Labels: 3. to review, feature: 🌗 theming

#1313 Swipe-right to reply
  app/src/main/java/com/nextcloud/talk/controllers/ChatController.kt
  app/src/main/java/com/nextcloud/talk/ui/recyclerview/MessageSwipeActions.kt
  app/src/main/java/com/nextcloud/talk/ui/recyclerview/MessageSwipeCallback.kt
  detekt.yml
Labels: 3. to review

#1283 fix displaying of large images
  app/build.gradle
  app/src/main/java/com/nextcloud/talk/activities/FullScreenImageActivity.kt
  app/src/main/java/com/nextcloud/talk/utils/BitmapShrinker.kt
Labels: 2. developing, don't merge

#1315 Swipe to reply flag processing
  app/src/main/java/com/nextcloud/talk/adapters/messages/MagicIncomingTextMessageViewHolder.kt
  app/src/main/java/com/nextcloud/talk/adapters/messages/MagicOutcomingTextMessageViewHolder.kt
  app/src/main/java/com/nextcloud/talk/adapters/messages/MagicPreviewMessageViewHolder.java
  app/src/main/java/com/nextcloud/talk/adapters/messages/MagicSystemMessageViewHolder.java
  app/src/main/java/com/nextcloud/talk/ui/recyclerview/MessageSwipeCallback.kt
  app/src/main/res/values/strings.xml
  scripts/analysis/findbugs-results.txt
Labels: 3. to review

#1334 Show "contact-name" and "contact-photo" when applicable
  app/src/main/java/com/nextcloud/talk/adapters/messages/IncomingPreviewMessageViewHolder.java
  app/src/main/java/com/nextcloud/talk/adapters/messages/MagicPreviewMessageViewHolder.java
  app/src/main/java/com/nextcloud/talk/adapters/messages/OutcomingPreviewMessageViewHolder.java
  app/src/main/res/layout/item_custom_incoming_preview_message.xml
  app/src/main/res/layout/item_custom_outcoming_preview_message.xml
  scripts/analysis/lint-results.txt
Labels: 3. to review, enhancement, feature: 🗨️ chat, feature: 🤝 sharing

#1324 Correct text selection background
  app/src/main/res/values/styles.xml
Labels: 3. to review

#1337 Add tracking circles support
  app/src/main/java/com/nextcloud/talk/adapters/items/UserItem.java
  app/src/main/java/com/nextcloud/talk/controllers/ConversationInfoController.kt
  app/src/main/res/values/strings.xml
Labels: 3. to review, feature: 📄 conversations

#1352 l10n: Add "message" to the text string
  app/src/main/res/values/strings.xml
Labels: backport-request

#1355 Fix avatar handling
  app/src/main/java/com/nextcloud/talk/models/json/chat/ChatMessage.java
Labels: 3. to review, bug, feature: 🗨️ chat

#1359 Check if attendeePin exists
  app/src/main/java/com/nextcloud/talk/controllers/ConversationInfoController.kt
Labels: 3. to review, backport-request

#1362 Update command-rebase.yml from template
  .github/workflows/command-rebase.yml
  .github/workflows/rebase.yml
Labels: 3. to review

#1365 Add shimmer for chat content loading
  app/src/main/res/layout/controller_chat.xml
  app/src/main/res/layout/item_custom_incoming_text_message_shimmer.xml
Labels: 3. to review, backport-request

#1364 Add dark/light aware high-res conversation icons
  app/src/main/java/com/nextcloud/talk/adapters/items/ConversationItem.java
  app/src/main/res/drawable-night/ic_circular_document.xml
  app/src/main/res/drawable-night/ic_circular_lock.xml
  app/src/main/res/drawable/ic_circular_document.xml
  app/src/main/res/drawable/ic_circular_lock.xml
  app/src/main/res/drawable/ic_file_icon.xml
  app/src/main/res/drawable/ic_file_password_request.xml
  drawable_resources/other/circular_document.svg
  drawable_resources/other/circular_lock.svg
Labels: 3. to review, backport-request

#1372 Harden Chat Title Calculation
  app/src/main/java/com/nextcloud/talk/controllers/ChatController.kt
Labels: 3. to review, backport-request

#1373 Bugfix/1343/stop voice message
  app/build.gradle
  app/src/main/java/com/nextcloud/talk/adapters/items/ConversationItem.java
  app/src/main/java/com/nextcloud/talk/adapters/items/MentionAutocompleteItem.java
  app/src/main/java/com/nextcloud/talk/adapters/messages/IncomingVoiceMessageViewHolder.kt
  app/src/main/java/com/nextcloud/talk/adapters/messages/OutcomingVoiceMessageViewHolder.kt
  app/src/main/java/com/nextcloud/talk/adapters/messages/TalkMessagesListAdapter.java
  app/src/main/java/com/nextcloud/talk/adapters/messages/VoiceMessageInterface.kt
  app/src/main/java/com/nextcloud/talk/controllers/ChatController.kt
  app/src/main/java/com/nextcloud/talk/models/json/chat/ChatMessage.java
  app/src/main/res/layout/item_custom_incoming_voice_message.xml
  app/src/main/res/layout/item_custom_outcoming_voice_message.xml
  app/src/main/res/values/strings.xml
  scripts/analysis/findbugs-results.txt
  scripts/analysis/lint-results.txt
Labels: 3. to review, backport-request

#1377 temporarily disable logging to file
  app/src/main/java/com/nextcloud/talk/dagger/modules/RestModule.java
  app/src/main/java/com/nextcloud/talk/utils/LoggingUtils.kt
  app/src/main/java/com/nextcloud/talk/webrtc/MagicPeerConnectionWrapper.java
  app/src/main/java/com/nextcloud/talk/webrtc/MagicWebSocketInstance.java
  scripts/analysis/findbugs-results.txt
Labels: backport-request

#1379 [stable-12.1] temporarily disable logging to file
  app/src/main/java/com/nextcloud/talk/dagger/modules/RestModule.java
  app/src/main/java/com/nextcloud/talk/utils/LoggingUtils.kt
  app/src/main/java/com/nextcloud/talk/webrtc/MagicPeerConnectionWrapper.java
  app/src/main/java/com/nextcloud/talk/webrtc/MagicWebSocketInstance.java
Labels: 3. to review

#1369 Improve Chat Accessibility
  app/src/main/java/com/nextcloud/talk/controllers/ChatController.kt
  app/src/main/res/layout/controller_chat.xml
  app/src/main/res/layout/view_message_input.xml
  app/src/main/res/values-night/colors.xml
Labels: 3. to review, backport-request, design

#1370 Check if view is (still) available
  app/src/main/java/com/nextcloud/talk/controllers/CallController.java
  scripts/analysis/findbugs-results.txt
Labels: 3. to review, backport-request
