Repository nextcloud/talk-android, pull requests merged in 2021-12, with the labels that each got.

#1731 Don't mirror check icon in RTL
  app/src/gplay/java/com/nextcloud/talk/services/firebase/MagicFirebaseMessagingService.kt
  app/src/main/java/com/nextcloud/talk/controllers/ChatController.kt
  app/src/main/res/drawable/ic_check_black_24dp.xml
Labels: 3. to review

#1715 Align file browser layout and folder icon with files client
  app/src/main/res/drawable/ic_mimetype_folder.xml
  app/src/main/res/layout/rv_item_browser_file.xml
Labels: 3. to review, backport-request

#1733 Show quotes of unnamed guests with "Guests"
  app/src/main/java/com/nextcloud/talk/adapters/messages/MagicIncomingTextMessageViewHolder.kt
  scripts/analysis/lint-results.txt
Labels: 3. to review

#1736 Correct URL of branching diagram
  CONTRIBUTING.md
Labels: 3. to review

#1619 Feature/1547/setup test automation on ci
  .drone.yml
  app/build.gradle
  app/src/androidTest/java/com/nextcloud/talk/ExampleInstrumentedTest.java
  app/src/androidTest/java/com/nextcloud/talk/activities/MainActivityTest.kt
  app/src/androidTest/java/com/nextcloud/talk/utils/ShareUtilsIT.kt
  app/src/main/java/com/nextcloud/talk/utils/database/user/UserUtils.java
  app/src/test/java/com/nextcloud/talk/utils/DoNotDisturbUtilsTest.java
  app/src/test/java/com/nextcloud/talk/utils/ShareUtilsTest.kt
  scripts/wait_for_emulator.sh
Labels: 3. to review

#1741 Fix unread indirect mention bg color
  app/src/main/java/com/nextcloud/talk/adapters/items/ConversationItem.java
Labels: 3. to review

#1728 Adapt notification code to Android 8.0 (Oreo) and later
  app/src/gplay/java/com/nextcloud/talk/services/firebase/MagicFirebaseMessagingService.kt
  app/src/main/java/com/nextcloud/talk/activities/CallActivity.java
  app/src/main/java/com/nextcloud/talk/activities/CallNotificationActivity.java
  app/src/main/java/com/nextcloud/talk/application/NextcloudTalkApplication.kt
  app/src/main/java/com/nextcloud/talk/controllers/RingtoneSelectionController.java
  app/src/main/java/com/nextcloud/talk/controllers/SettingsController.java
  app/src/main/java/com/nextcloud/talk/jobs/NotificationWorker.java
  app/src/main/java/com/nextcloud/talk/utils/NotificationUtils.kt
  app/src/main/res/layout/controller_settings.xml
  app/src/main/res/values/strings.xml
Labels: 3. to review, feature: 🔔 notifications, feature: ⚙️ settings

#1739 Add test for login flow
  .drone.yml
  app/build.gradle
  app/src/androidTest/java/com/nextcloud/talk/activities/MainActivityTest.kt
  app/src/androidTest/java/com/nextcloud/talk/ui/LoginIT.java
  app/src/main/java/com/nextcloud/talk/controllers/ContactsController.java
  app/src/main/java/com/nextcloud/talk/webrtc/MagicWebRTCUtils.java
  gradle.properties
  scripts/analysis/lint-results.txt
Labels: 3. to review
