Repository nextcloud/talk-android, pull requests merged in 2021-11, with the labels that each got.

#1659 Avatar "hovercard"
  app/src/main/java/com/nextcloud/talk/adapters/messages/IncomingLocationMessageViewHolder.kt
  app/src/main/java/com/nextcloud/talk/adapters/messages/IncomingPreviewMessageViewHolder.java
  app/src/main/java/com/nextcloud/talk/adapters/messages/IncomingVoiceMessageViewHolder.kt
  app/src/main/java/com/nextcloud/talk/adapters/messages/MagicIncomingTextMessageViewHolder.kt
  app/src/main/java/com/nextcloud/talk/adapters/messages/MagicPreviewMessageViewHolder.java
  app/src/main/java/com/nextcloud/talk/adapters/messages/OutcomingPreviewMessageViewHolder.java
  app/src/main/java/com/nextcloud/talk/api/NcApi.java
  app/src/main/java/com/nextcloud/talk/components/filebrowser/webdav/DavUtils.java
  app/src/main/java/com/nextcloud/talk/controllers/ChatController.kt
  app/src/main/java/com/nextcloud/talk/controllers/ConversationInfoController.kt
  app/src/main/java/com/nextcloud/talk/models/json/hovercard/HoverCard.java
  app/src/main/java/com/nextcloud/talk/models/json/hovercard/HoverCardAction.java
  app/src/main/java/com/nextcloud/talk/models/json/hovercard/HoverCardOCS.java
  app/src/main/java/com/nextcloud/talk/models/json/hovercard/HoverCardOverall.java
  app/src/main/java/com/nextcloud/talk/ui/bottom/sheet/ProfileBottomSheet.kt
  app/src/main/java/com/nextcloud/talk/utils/ApiUtils.java
  app/src/main/res/drawable/ic_talk.xml
Labels: 3. to review

#1673 Ignore generated JsonObjectMapper
  scripts/analysis/findbugs-results.txt
  spotbugs-filter.xml
Labels: 3. to review

#1674 bump version to 13.0.0 Alpha 1
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/nextcloud/talk/adapters/messages/MagicPreviewMessageViewHolder.java
Labels: 3. to review

#1680 Make all infos a subline
  app/src/main/res/layout/controller_settings.xml
Labels: 3. to review

#1703 Skip QA build if keystore not available
  .github/workflows/qa.yml
Labels: 3. to review, backport-request

#1701 Gradle should log plain
  .drone.yml
  scripts/analysis/findbugs-up.rb
  scripts/analysis/lint-up.rb
Labels: 3. to review, backport-request

#1706 make all cam buttons reflect current state instead of triggered action
  app/src/main/java/com/nextcloud/talk/models/TakePictureViewModel.java
  scripts/analysis/lint-results.txt
Labels: 3. to review, backport-request

#1698 add logging for calls
  app/src/gplay/java/com/nextcloud/talk/services/firebase/MagicFirebaseMessagingService.kt
  app/src/main/java/com/nextcloud/talk/activities/CallActivity.java
  app/src/main/java/com/nextcloud/talk/controllers/ChatController.kt
  app/src/main/java/com/nextcloud/talk/utils/ApiUtils.java
  app/src/main/java/com/nextcloud/talk/webrtc/MagicWebSocketInstance.java
  app/src/main/java/com/nextcloud/talk/webrtc/WebSocketConnectionHelper.java
Labels: don't merge

#1634 timeout call notification
  app/src/gplay/java/com/nextcloud/talk/services/firebase/MagicFirebaseMessagingService.kt
  app/src/main/java/com/nextcloud/talk/activities/CallNotificationActivity.java
  app/src/main/java/com/nextcloud/talk/controllers/ChatController.kt
Labels: 3. to review

#1727 [stable-13.0] timeout call notification
  app/src/gplay/java/com/nextcloud/talk/services/firebase/MagicFirebaseMessagingService.kt
  app/src/main/java/com/nextcloud/talk/activities/CallNotificationActivity.java
  app/src/main/java/com/nextcloud/talk/controllers/ChatController.kt
Labels: 3. to review

#1729 Bump version to 13.0.0
  app/build.gradle
Labels: 3. to review
