Repository nextcloud/talk-android, pull requests merged in 2021-05, with the labels that each got.

#1191 Start the reauth webview also when there is no getParentController()
  app/src/main/java/com/nextcloud/talk/controllers/ConversationsListController.java
  app/src/main/java/com/nextcloud/talk/controllers/WebViewLoginController.java
  app/src/main/java/com/nextcloud/talk/jobs/AccountRemovalWorker.java
  app/src/main/res/values/strings.xml
Labels: 3. to review, bug

#1212 Open files by external Apps
  CHANGELOG.md
  app/src/main/java/com/nextcloud/talk/adapters/messages/MagicPreviewMessageViewHolder.java
  app/src/main/res/xml/file_provider_paths.xml
Labels: 3. to review

#1216 A11y content description
  app/src/main/java/com/nextcloud/talk/adapters/items/UserItem.java
  app/src/main/java/com/nextcloud/talk/adapters/messages/MagicOutcomingTextMessageViewHolder.kt
  app/src/main/java/com/nextcloud/talk/controllers/ProfileController.java
  app/src/main/java/com/nextcloud/talk/controllers/bottomsheet/EntryMenuController.java
  app/src/main/res/layout/call_item.xml
  app/src/main/res/layout/call_states.xml
  app/src/main/res/layout/controller_call_notification.xml
  app/src/main/res/layout/controller_entry_menu.xml
  app/src/main/res/layout/controller_locked.xml
  app/src/main/res/layout/controller_operations_menu.xml
  app/src/main/res/layout/item_custom_outcoming_text_message.xml
  app/src/main/res/layout/lobby_view.xml
  app/src/main/res/layout/rv_item_app.xml
  app/src/main/res/layout/rv_item_browser_file.xml
  app/src/main/res/layout/rv_item_conversation.xml
  app/src/main/res/layout/rv_item_conversation_info_participant.xml
  app/src/main/res/layout/user_info_details_table_item.xml
  app/src/main/res/layout/view_message_input.xml
  app/src/main/res/values/strings.xml
  scripts/analysis/lint-results.txt
Labels: 3. to review

#1205 replace forks: chatkit, fresco, popupBubble
  app/build.gradle
Labels: 3. to review

#1215 Add a warning when the server version is (almost) EOL
  app/src/main/java/com/nextcloud/talk/controllers/ConversationsListController.java
  app/src/main/java/com/nextcloud/talk/controllers/SettingsController.java
  app/src/main/java/com/nextcloud/talk/models/database/User.java
  app/src/main/java/com/nextcloud/talk/utils/database/user/UserUtils.java
  app/src/main/res/layout/controller_settings.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  scripts/analysis/lint-results.txt
Labels: 3. to review, enhancement

#1221 Properly parse encryption/favorite flags
  app/src/main/java/com/nextcloud/talk/components/filebrowser/models/properties/NCEncrypted.java
  app/src/main/java/com/nextcloud/talk/components/filebrowser/models/properties/OCFavorite.java
Labels: 3. to review

#1223 Remove lock icon in conversation list
  app/src/main/java/com/nextcloud/talk/adapters/items/ConversationItem.java
  app/src/main/res/drawable/shape_lock_bubble.xml
  app/src/main/res/layout/rv_item_conversation_with_last_message.xml
  scripts/analysis/findbugs-results.txt
  scripts/analysis/lint-results.txt
Labels: 3. to review, design

#1119 🍱 Grid view for calls
  CHANGELOG.md
  app/src/main/java/com/nextcloud/talk/adapters/ParticipantDisplayItem.java
  app/src/main/java/com/nextcloud/talk/adapters/ParticipantsAdapter.java
  app/src/main/java/com/nextcloud/talk/controllers/CallController.java
  app/src/main/java/com/nextcloud/talk/utils/DisplayUtils.java
  app/src/main/java/com/nextcloud/talk/webrtc/MagicPeerConnectionWrapper.java
  app/src/main/res/layout/call_item.xml
  app/src/main/res/layout/controller_call.xml
  app/src/main/res/layout/controller_call_notification.xml
  app/src/main/res/values/strings.xml
  scripts/analysis/findbugs-results.txt
Labels: 3. to review

#1224 Define all system messages as such
  app/src/main/java/com/nextcloud/talk/controllers/ChatController.kt
  app/src/main/java/com/nextcloud/talk/models/json/chat/ChatMessage.java
  app/src/main/java/com/nextcloud/talk/models/json/converters/EnumSystemMessageTypeConverter.kt
Labels: 3. to review, backport-request, bug

#1156 v4️⃣ - Add option for APIv4 compatibility
  app/src/gplay/java/com/nextcloud/talk/services/firebase/MagicFirebaseMessagingService.kt
  app/src/main/java/com/nextcloud/talk/activities/MainActivity.kt
  app/src/main/java/com/nextcloud/talk/controllers/AccountVerificationController.java
  app/src/main/java/com/nextcloud/talk/controllers/CallController.java
  app/src/main/java/com/nextcloud/talk/controllers/CallNotificationController.java
  app/src/main/java/com/nextcloud/talk/controllers/ChatController.kt
  app/src/main/java/com/nextcloud/talk/controllers/ContactsController.java
  app/src/main/java/com/nextcloud/talk/controllers/ConversationInfoController.kt
  app/src/main/java/com/nextcloud/talk/controllers/ConversationsListController.java
  app/src/main/java/com/nextcloud/talk/controllers/bottomsheet/OperationsMenuController.java
  app/src/main/java/com/nextcloud/talk/jobs/AddParticipantsToConversation.java
  app/src/main/java/com/nextcloud/talk/jobs/DeleteConversationWorker.java
  app/src/main/java/com/nextcloud/talk/jobs/LeaveConversationWorker.java
  app/src/main/java/com/nextcloud/talk/jobs/NotificationWorker.java
  app/src/main/java/com/nextcloud/talk/jobs/SignalingSettingsWorker.java
  app/src/main/java/com/nextcloud/talk/presenters/MentionAutocompletePresenter.java
  app/src/main/java/com/nextcloud/talk/utils/ApiUtils.java
  app/src/main/java/com/nextcloud/talk/utils/NoSupportedApiException.kt
  app/src/main/java/com/nextcloud/talk/utils/preferences/preferencestorage/DatabaseStorageModule.java
  app/src/main/java/com/nextcloud/talk/webrtc/WebSocketConnectionHelper.java
Labels: 3. to review

#1214 🧹 Drop ping functionality
  app/src/main/java/com/nextcloud/talk/api/NcApi.java
  app/src/main/java/com/nextcloud/talk/controllers/CallController.java
  app/src/main/java/com/nextcloud/talk/controllers/CallNotificationController.java
  app/src/main/java/com/nextcloud/talk/controllers/ChatController.kt
  app/src/main/java/com/nextcloud/talk/jobs/NotificationWorker.java
  app/src/main/java/com/nextcloud/talk/utils/ApiUtils.java
Labels: 3. to review, enhancement

#1218 [apiv4] Remove props which are not there anymore
  app/src/main/java/com/nextcloud/talk/controllers/ConversationInfoController.kt
  app/src/main/java/com/nextcloud/talk/controllers/ConversationsListController.java
  app/src/main/java/com/nextcloud/talk/models/json/conversations/Conversation.java
  app/src/main/res/values/strings.xml
  scripts/analysis/findbugs-results.txt
Labels: 3. to review, bug, high

#1219 [apiv4] Add apiv4 for easy conversation api calls
  app/src/main/java/com/nextcloud/talk/activities/MainActivity.kt
  app/src/main/java/com/nextcloud/talk/controllers/CallController.java
  app/src/main/java/com/nextcloud/talk/controllers/CallNotificationController.java
  app/src/main/java/com/nextcloud/talk/controllers/ChatController.kt
  app/src/main/java/com/nextcloud/talk/controllers/ContactsController.java
  app/src/main/java/com/nextcloud/talk/controllers/ConversationInfoController.kt
  app/src/main/java/com/nextcloud/talk/controllers/ConversationsListController.java
  app/src/main/java/com/nextcloud/talk/controllers/bottomsheet/OperationsMenuController.java
  app/src/main/java/com/nextcloud/talk/jobs/DeleteConversationWorker.java
  app/src/main/java/com/nextcloud/talk/jobs/LeaveConversationWorker.java
  app/src/main/java/com/nextcloud/talk/jobs/NotificationWorker.java
  app/src/main/java/com/nextcloud/talk/utils/ApiUtils.java
  app/src/main/java/com/nextcloud/talk/utils/preferences/preferencestorage/DatabaseStorageModule.java
Labels: 3. to review, enhancement

#1236 ✉️ Add mail icon for mail users
  app/src/main/java/com/nextcloud/talk/adapters/items/ConversationItem.java
  app/src/main/java/com/nextcloud/talk/adapters/items/UserItem.java
  app/src/main/res/drawable/ic_circular_mail.xml
  drawable_resources/other/circular_mail.svg
Labels: 3. to review

#1231 "chat-v2" is there since nextcloud13
  app/src/main/java/com/nextcloud/talk/activities/MainActivity.kt
  app/src/main/java/com/nextcloud/talk/controllers/ChatController.kt
  app/src/main/java/com/nextcloud/talk/controllers/ContactsController.java
  app/src/main/java/com/nextcloud/talk/controllers/ConversationsListController.java
  app/src/main/java/com/nextcloud/talk/controllers/bottomsheet/OperationsMenuController.java
  app/src/main/java/com/nextcloud/talk/jobs/NotificationWorker.java
  scripts/analysis/findbugs-results.txt
Labels: 3. to review, enhancement

#1229 [apiv4] ☎️ Calls
  app/src/main/java/com/nextcloud/talk/adapters/items/UserItem.java
  app/src/main/java/com/nextcloud/talk/controllers/CallController.java
  app/src/main/java/com/nextcloud/talk/controllers/CallNotificationController.java
  app/src/main/java/com/nextcloud/talk/controllers/ContactsController.java
  app/src/main/java/com/nextcloud/talk/models/json/participants/Participant.java
  app/src/main/java/com/nextcloud/talk/webrtc/MagicWebSocketInstance.java
Labels: 3. to review, bug

#1239 Add account switcher in search bar
  app/build.gradle
  app/src/main/java/com/nextcloud/talk/activities/MainActivity.kt
  app/src/main/java/com/nextcloud/talk/adapters/items/ConversationItem.java
  app/src/main/java/com/nextcloud/talk/controllers/ConversationsListController.java
  app/src/main/java/com/nextcloud/talk/controllers/SettingsController.java
  app/src/main/java/com/nextcloud/talk/ui/dialog/ChooseAccountDialogFragment.java
  app/src/main/res/drawable/ic_check_circle.xml
  app/src/main/res/drawable/ic_settings.xml
  app/src/main/res/layout/account_item.xml
  app/src/main/res/layout/controller_settings.xml
  app/src/main/res/layout/dialog_choose_account.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
  scripts/analysis/findbugs-results.txt
Labels: 3. to review, design

#1222 🗒️ Add (read-only for now) description to the conversation info
  app/src/main/java/com/nextcloud/talk/controllers/ConversationInfoController.kt
  app/src/main/java/com/nextcloud/talk/models/json/conversations/Conversation.java
  app/src/main/res/layout/controller_conversation_info.xml
  scripts/analysis/lint-results.txt
Labels: 3. to review, enhancement

#1235 [apiv4] 👤🏷️ Fix API calls for guests
  app/src/main/java/com/nextcloud/talk/controllers/CallController.java
  app/src/main/java/com/nextcloud/talk/controllers/CallNotificationController.java
  app/src/main/java/com/nextcloud/talk/controllers/ChatController.kt
  app/src/main/java/com/nextcloud/talk/controllers/bottomsheet/OperationsMenuController.java
  app/src/main/java/com/nextcloud/talk/models/json/chat/ChatMessage.java
  app/src/main/java/com/nextcloud/talk/models/json/conversations/Conversation.java
  app/src/main/java/com/nextcloud/talk/webrtc/MagicWebSocketInstance.java
  app/src/main/java/com/nextcloud/talk/webrtc/WebSocketConnectionHelper.java
Labels: 3. to review, bug, feature: ☎️ call, feature: 🗨️ chat

#1242 [backport] set proper colors for unread-messages for edge case of theme switch
  app/src/main/java/com/nextcloud/talk/adapters/items/ConversationItem.java
Labels: 3. to review

#1240 run drone on stable-11 branch
  .drone.yml
  scripts/analysis/analysis-wrapper.sh
  scripts/analysis/getBranchName.sh
Labels: 3. to review

#1173 make navigationbar for videocall black
  app/src/main/java/com/nextcloud/talk/activities/MagicCallActivity.kt
  app/src/main/res/values/styles.xml
Labels: 3. to review, backport-request

#1249 🎙️ Fix participant list call state icon
  app/src/main/java/com/nextcloud/talk/adapters/items/UserItem.java
  app/src/main/java/com/nextcloud/talk/controllers/ChatController.kt
  app/src/main/java/com/nextcloud/talk/models/json/participants/Participant.java
  app/src/main/res/drawable/shape_call_bubble.xml
  app/src/main/res/drawable/shape_favorite_bubble.xml
  app/src/main/res/drawable/shape_lock_bubble.xml
  app/src/main/res/drawable/shape_video_bubble.xml
  app/src/main/res/drawable/shape_voice_bubble.xml
  app/src/main/res/layout/rv_item_conversation_info_participant.xml
  app/src/main/res/values/strings.xml
  scripts/analysis/findbugs-results.txt
  scripts/analysis/lint-results.txt
Labels: 3. to review, bug, feature: ☎️ call

#1246 ↖️ Reply privately
  app/src/main/java/com/nextcloud/talk/controllers/ChatController.kt
  app/src/main/res/drawable/ic_content_copy.xml
  app/src/main/res/drawable/ic_delete.xml
  app/src/main/res/drawable/ic_reply.xml
  app/src/main/res/menu/chat_message_menu.xml
  app/src/main/res/values/strings.xml
Labels: 3. to review, enhancement, feature: 🗨️ chat

#1245 ✉️ & ⭕ Allow to add emails and circles as particpants
  app/src/main/java/com/nextcloud/talk/activities/MainActivity.kt
  app/src/main/java/com/nextcloud/talk/adapters/items/UserItem.java
  app/src/main/java/com/nextcloud/talk/controllers/ChatController.kt
  app/src/main/java/com/nextcloud/talk/controllers/ContactsController.java
  app/src/main/java/com/nextcloud/talk/controllers/bottomsheet/OperationsMenuController.java
  app/src/main/java/com/nextcloud/talk/jobs/AddParticipantsToConversation.java
  app/src/main/java/com/nextcloud/talk/models/json/converters/EnumActorTypeConverter.kt
  app/src/main/java/com/nextcloud/talk/models/json/participants/Participant.java
  app/src/main/java/com/nextcloud/talk/utils/ApiUtils.java
  app/src/main/java/com/nextcloud/talk/utils/bundle/BundleKeys.kt
  app/src/main/res/values/strings.xml
Labels: 3. to review, enhancement

#1258 Remove new line from translatable string
  app/src/main/res/values/strings.xml
Labels: backport-request

#1262 remove ExtraTranslation flags
  app/src/main/res/values/strings.xml
Labels: 3. to review, backport-request

#1254 Use proper activity context to grab themed color for mentions
  app/src/main/java/com/nextcloud/talk/adapters/items/MentionAutocompleteItem.java
  app/src/main/java/com/nextcloud/talk/controllers/ChatController.kt
  app/src/main/java/com/nextcloud/talk/presenters/MentionAutocompletePresenter.java
  app/src/main/res/layout/rv_item_mention.xml
Labels: 3. to review

#1261 Codacy
  app/src/main/java/com/nextcloud/talk/adapters/ParticipantsAdapter.java
  app/src/main/java/com/nextcloud/talk/adapters/items/AdvancedUserItem.java
  app/src/main/java/com/nextcloud/talk/adapters/items/CallItem.java
  app/src/main/java/com/nextcloud/talk/adapters/messages/MagicPreviewMessageViewHolder.java
  app/src/main/java/com/nextcloud/talk/adapters/messages/MagicUnreadNoticeMessageViewHolder.java
  app/src/main/java/com/nextcloud/talk/adapters/messages/TalkMessagesListAdapter.java
  app/src/main/java/com/nextcloud/talk/callbacks/MentionAutocompleteCallback.java
  app/src/main/java/com/nextcloud/talk/components/filebrowser/controllers/BrowserController.java
  app/src/main/java/com/nextcloud/talk/components/filebrowser/models/properties/NCEncrypted.java
  app/src/main/java/com/nextcloud/talk/components/filebrowser/models/properties/NCEncrypted.kt
  app/src/main/java/com/nextcloud/talk/components/filebrowser/models/properties/NCPermission.java
  app/src/main/java/com/nextcloud/talk/components/filebrowser/models/properties/NCPermission.kt
  app/src/main/java/com/nextcloud/talk/components/filebrowser/models/properties/NCPreview.java
  app/src/main/java/com/nextcloud/talk/components/filebrowser/models/properties/NCPreview.kt
  app/src/main/java/com/nextcloud/talk/components/filebrowser/models/properties/OCFavorite.java
  app/src/main/java/com/nextcloud/talk/components/filebrowser/models/properties/OCFavorite.kt
  app/src/main/java/com/nextcloud/talk/components/filebrowser/models/properties/OCId.java
  app/src/main/java/com/nextcloud/talk/components/filebrowser/models/properties/OCId.kt
  app/src/main/java/com/nextcloud/talk/components/filebrowser/models/properties/OCSize.java
  app/src/main/java/com/nextcloud/talk/components/filebrowser/models/properties/OCSize.kt
  app/src/main/java/com/nextcloud/talk/controllers/AccountVerificationController.java
  app/src/main/java/com/nextcloud/talk/controllers/CallNotificationController.java
  app/src/main/java/com/nextcloud/talk/controllers/ConversationInfoController.kt
  app/src/main/java/com/nextcloud/talk/controllers/ConversationsListController.java
  app/src/main/java/com/nextcloud/talk/controllers/LockedController.java
  app/src/main/java/com/nextcloud/talk/controllers/ProfileController.java
  app/src/main/java/com/nextcloud/talk/controllers/ServerSelectionController.java
  app/src/main/java/com/nextcloud/talk/controllers/WebViewLoginController.java
  app/src/main/java/com/nextcloud/talk/dagger/modules/RestModule.java
  app/src/main/java/com/nextcloud/talk/jobs/SignalingSettingsWorker.java
  app/src/main/java/com/nextcloud/talk/jobs/UploadAndShareFilesWorker.kt
  app/src/main/java/com/nextcloud/talk/ui/dialog/ChooseAccountDialogFragment.java
  app/src/main/java/com/nextcloud/talk/utils/AuthenticatorService.java
  app/src/main/java/com/nextcloud/talk/utils/PushUtils.java
  app/src/main/java/com/nextcloud/talk/utils/preferences/AppPreferences.java
  app/src/main/java/com/nextcloud/talk/webrtc/MagicPeerConnectionWrapper.java
  app/src/main/java/com/nextcloud/talk/webrtc/WebSocketConnectionHelper.java
  app/src/test/java/com/nextcloud/talk/utils/DoNotDisturbUtilsTest.java
  app/src/test/java/com/nextcloud/talk/utils/ShareUtilsTest.java
  app/src/test/java/com/nextcloud/talk/utils/TextMatchersTest.java
Labels: 3. to review

#1264 Remove custom password animation and use default/component one
  app/src/main/java/com/nextcloud/talk/controllers/bottomsheet/EntryMenuController.java
  app/src/main/res/drawable/asl_password_visibility.xml
  app/src/main/res/drawable/avd_hide_password.xml
  app/src/main/res/drawable/avd_show_password.xml
  app/src/main/res/drawable/ic_password_masked.xml
  app/src/main/res/drawable/ic_password_visible.xml
  app/src/main/res/layout/controller_entry_menu.xml
  app/src/main/res/values/ints.xml
  app/src/main/res/values/strings.xml
Labels: 3. to review, backport-request

#1266 Use native view bindings in activities
  app/src/main/java/com/nextcloud/talk/activities/FullScreenImageActivity.kt
  app/src/main/java/com/nextcloud/talk/activities/FullScreenMediaActivity.kt
  app/src/main/java/com/nextcloud/talk/activities/FullScreenTextViewerActivity.kt
  app/src/main/java/com/nextcloud/talk/activities/MagicCallActivity.kt
  app/src/main/java/com/nextcloud/talk/activities/MainActivity.kt
  app/src/main/java/com/nextcloud/talk/controllers/ConversationsListController.java
  app/src/main/java/com/nextcloud/talk/controllers/base/BaseController.java
  app/src/main/res/layout/account_item.xml
  app/src/main/res/layout/activity_main.xml
  scripts/analysis/lint-results.txt
Labels: 3. to review

#1251 Use the stun urls array
  app/src/main/java/com/nextcloud/talk/controllers/CallController.java
  app/src/main/java/com/nextcloud/talk/controllers/CallNotificationController.java
  app/src/main/java/com/nextcloud/talk/controllers/bottomsheet/OperationsMenuController.java
  app/src/main/java/com/nextcloud/talk/jobs/SignalingSettingsWorker.java
  app/src/main/java/com/nextcloud/talk/models/json/signaling/settings/IceServer.java
  app/src/main/java/com/nextcloud/talk/utils/ApiUtils.java
  app/src/main/java/com/nextcloud/talk/webrtc/WebSocketConnectionHelper.java
  scripts/analysis/findbugs-results.txt
Labels: 3. to review, bug

#1277 Set user icon to have a fallback for account switcher icon in search bar
  app/src/main/java/com/nextcloud/talk/controllers/ConversationsListController.java
  app/src/main/res/drawable/ic_settings_white_24dp.xml
  app/src/main/res/drawable/ic_user.xml
  app/src/main/res/layout/search_layout.xml
Labels: 3. to review, backport-request

#1276 Make observer type save
  app/src/main/java/com/nextcloud/talk/controllers/bottomsheet/OperationsMenuController.java
Labels: 3. to review

#1282 [no-ci] Dev docs
  CONTRIBUTING.md
  README.md
  SETUP.md
  docs/branching.png
  docs/branching.svg
  docs/semantic_versioning_code.png
Labels: 3. to review

#1252 add ability to "share to" files to nextcloud talk app
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/nextcloud/talk/activities/MainActivity.kt
  app/src/main/java/com/nextcloud/talk/controllers/ChatController.kt
  app/src/main/java/com/nextcloud/talk/controllers/ConversationsListController.java
  app/src/main/java/com/nextcloud/talk/controllers/base/BaseController.java
  app/src/main/java/com/nextcloud/talk/jobs/UploadAndShareFilesWorker.kt
  app/src/main/java/com/nextcloud/talk/utils/UriUtils.kt
  app/src/main/java/com/nextcloud/talk/utils/bundle/BundleKeys.kt
  app/src/main/res/values/strings.xml
  scripts/analysis/findbugs-results.txt
Labels: 3. to review

#1291 Set fallback avatar icon on account chooser
  app/src/main/java/com/nextcloud/talk/adapters/items/AdvancedUserItem.java
  app/src/main/java/com/nextcloud/talk/ui/dialog/ChooseAccountDialogFragment.java
  app/src/main/res/drawable/account_circle_48dp.xml
  app/src/main/res/layout/account_item.xml
  drawable_resources/other/account-circle.svg
Labels: 3. to review

#1295 dont show deletion option for attachments
  app/src/main/java/com/nextcloud/talk/controllers/ChatController.kt
  app/src/main/java/com/nextcloud/talk/models/json/chat/ChatMessage.java
Labels: 3. to review

#1296 Add placeholder image to avatar for profile view
  app/src/main/res/layout/controller_profile.xml
Labels: 3. to review

#1298 Correct fix for not showing bold on read ConversationItem
  app/src/main/java/com/nextcloud/talk/adapters/items/ConversationItem.java
Labels: 3. to review

#1299 l10n: Delete unnecessary text strings
  app/src/main/res/values/strings.xml
  scripts/analysis/lint-results.txt
Labels: 3. to review

#1300 Rebase action: /rebase as comment
  .github/workflows/rebase.yml
Labels: 3. to review

#1302 Block fixup and squash commits
  .github/workflows/fixup.yml
Labels: 3. to review

#1303 Prevent text selection on messages
  app/src/main/res/layout/item_custom_incoming_text_message.xml
  app/src/main/res/layout/item_custom_outcoming_text_message.xml
  app/src/main/res/layout/item_message_quote.xml
Labels: 3. to review
