Repository nextcloud/talk-android, pull requests merged in 2021-09, with the labels that each got.

#1569 Hide own conversation in "forward to" selection screen
  app/src/main/java/com/nextcloud/talk/controllers/ChatController.kt
  app/src/main/java/com/nextcloud/talk/controllers/ConversationsListController.java
  app/src/main/java/com/nextcloud/talk/utils/bundle/BundleKeys.kt
Labels: 3. to review, backport-request

#1568 Fix scrolling and selection issue in RTL
  app/src/main/java/com/nextcloud/talk/components/filebrowser/controllers/BrowserController.java
  app/src/main/java/com/nextcloud/talk/controllers/ContactsController.java
  app/src/main/java/com/nextcloud/talk/controllers/ConversationsListController.java
  app/src/main/res/layout/controller_browser.xml
  app/src/main/res/layout/controller_conversations_rv.xml
  app/src/main/res/layout/controller_generic_rv.xml
  app/src/main/res/layout/fast_scroller.xml
  scripts/analysis/findbugs-results.txt
  scripts/analysis/lint-results.txt
Labels: 3. to review, backport-request

#1507 Dav test
  app/src/androidTest/java/com/nextcloud/talk/ExampleInstrumentedTest.java
  app/src/androidTest/java/com/nextcloud/talk/utils/ShareUtilsIT.kt
  app/src/test/java/com/nextcloud/talk/utils/ShareUtilsTest.java
  app/src/test/java/com/nextcloud/talk/utils/ShareUtilsTest.kt
Labels: 3. to review

#1546 Bump to SDK 30
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/nextcloud/talk/controllers/LocationPickerController.kt
  app/src/main/java/com/nextcloud/talk/jobs/UploadAndShareFilesWorker.kt
  app/src/main/java/com/nextcloud/talk/webrtc/MagicAudioManager.java
Labels: 3. to review

#1585 enable keyguard for toggle chat
  app/src/main/java/com/nextcloud/talk/activities/MagicCallActivity.kt
Labels: 3. to review

#1588 add unread mentions popup-bubble in conversations list
  app/src/main/java/com/nextcloud/talk/controllers/ConversationsListController.java
  app/src/main/res/layout/controller_conversations_rv.xml
  app/src/main/res/values/strings.xml
  scripts/analysis/lint-results.txt
Labels: 3. to review

#1589 Show lobby timer and description in lobby screen
  app/src/main/java/com/nextcloud/talk/controllers/ChatController.kt
  app/src/main/java/com/nextcloud/talk/utils/DateUtils.kt
  app/src/main/res/layout/lobby_view.xml
  app/src/main/res/values/strings.xml
Labels: 3. to review

#1594 differentiate unread counters
  app/src/main/java/com/nextcloud/talk/adapters/items/ConversationItem.java
  app/src/main/java/com/nextcloud/talk/controllers/ConversationsListController.java
  app/src/main/java/com/nextcloud/talk/models/json/conversations/Conversation.java
Labels: 3. to review

#1595 Extend notification testing docs
  docs/notifications.md
Labels: 3. to review, feature: 🔔 notifications

#1598 catch NPE for popup bubble
  app/src/main/java/com/nextcloud/talk/controllers/ConversationsListController.java
Labels: 3. to review

#1600 Also account for unread 1on1 messages for unreadMessages bubbleClicked
  app/src/main/java/com/nextcloud/talk/controllers/ConversationsListController.java
Labels: 3. to review

#1607 Clear message field after sharing
  app/src/main/java/com/nextcloud/talk/controllers/ConversationsListController.java
Labels: 3. to review
