Repository nextcloud/talk-android, pull requests merged in 2021-02, with the labels that each got.

#985 add ability to delete messages
  app/src/main/java/com/nextcloud/talk/adapters/messages/MagicIncomingTextMessageViewHolder.kt
  app/src/main/java/com/nextcloud/talk/adapters/messages/MagicOutcomingTextMessageViewHolder.kt
  app/src/main/java/com/nextcloud/talk/api/NcApi.java
  app/src/main/java/com/nextcloud/talk/controllers/ChatController.kt
  app/src/main/java/com/nextcloud/talk/models/json/chat/ChatMessage.java
  app/src/main/java/com/nextcloud/talk/models/json/chat/ChatOCSSingleMessage.java
  app/src/main/java/com/nextcloud/talk/models/json/chat/ChatOverallSingleMessage.java
  app/src/main/java/com/nextcloud/talk/models/json/conversations/Conversation.java
  app/src/main/java/com/nextcloud/talk/models/json/converters/EnumSystemMessageTypeConverter.kt
  app/src/main/java/com/nextcloud/talk/utils/ApiUtils.java
  app/src/main/res/drawable/ic_delete_white_24dp.xml
  app/src/main/res/menu/chat_message_menu.xml
  app/src/main/res/values-night/colors.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: 3. to review

#1003 bump google-webrtc to 1.0.32006
  app/build.gradle
  app/src/main/java/com/nextcloud/talk/adapters/items/UserItem.java
  app/src/main/java/com/nextcloud/talk/adapters/messages/MagicIncomingTextMessageViewHolder.kt
  app/src/main/java/com/nextcloud/talk/adapters/messages/MagicOutcomingTextMessageViewHolder.kt
  app/src/main/java/com/nextcloud/talk/application/NextcloudTalkApplication.kt
  app/src/main/java/com/nextcloud/talk/controllers/AccountVerificationController.java
  app/src/main/java/com/nextcloud/talk/controllers/CallController.java
  app/src/main/java/com/nextcloud/talk/controllers/CallNotificationController.java
  app/src/main/java/com/nextcloud/talk/controllers/ChatController.kt
  app/src/main/java/com/nextcloud/talk/controllers/base/ButterKnifeController.kt
  app/src/main/java/com/nextcloud/talk/jobs/UploadAndShareFilesWorker.kt
  app/src/main/java/com/nextcloud/talk/ui/dialog/AttachmentDialog.kt
  app/src/main/java/com/nextcloud/talk/utils/ApiUtils.java
  app/src/main/java/com/nextcloud/talk/utils/DisplayUtils.java
  app/src/main/java/com/nextcloud/talk/utils/NotificationUtils.kt
  app/src/main/res/layout/item_message_quote.xml
  drawable_resources/icon-background.svg
  drawable_resources/icon-foreground.svg
  drawable_resources/other/file-icon-black-24h.svg
  drawable_resources/other/file-icon.svg
  drawable_resources/other/file-password-request.svg
  scripts/analysis/lint-results.txt
Labels: 3. to review

#1009 add confirm dialog before sharing files
  app/src/main/java/com/nextcloud/talk/controllers/ChatController.kt
  app/src/main/java/com/nextcloud/talk/jobs/UploadAndShareFilesWorker.kt
  app/src/main/java/com/nextcloud/talk/utils/UriUtils.kt
  app/src/main/res/values-night/colors.xml
  app/src/main/res/values/strings.xml
Labels: 3. to review

#1012 Run drone also on master broken
  .drone.yml
  scripts/analysis/lint-results.txt
Labels: 2. developing

#1014 Drone signs its comments
  scripts/analysis/lint-up.rb
Labels: 3. to review

#1015 Add lint.xml
  app/lint.xml
  scripts/analysis/lint-results.txt
Labels: 3. to review

#1010 Login Textfield design
  app/src/main/java/com/nextcloud/talk/newarch/features/account/serverentry/ServerEntryView.kt
  app/src/main/res/layout/server_entry_view.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
  scripts/analysis/lint-results.txt
Labels: 3. to review, design
