Repository nextcloud/talk-android, pull requests merged in 2021-08, with the labels that each got.

#1520 fix displaying of message delete-button
  app/src/main/java/com/nextcloud/talk/controllers/ChatController.kt
Labels: 3. to review, backport-request

#1527 There can only be one background #highlander
  app/src/main/res/drawable/ic_launcher_background.xml
Labels: 3. to review, backport-request

#1513 Adding upload from camera action
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/nextcloud/talk/activities/TakePhotoActivity.java
  app/src/main/java/com/nextcloud/talk/controllers/ChatController.kt
  app/src/main/java/com/nextcloud/talk/controllers/bottomsheet/CallMenuController.java
  app/src/main/java/com/nextcloud/talk/models/TakePictureViewModel.java
  app/src/main/java/com/nextcloud/talk/ui/dialog/AttachmentDialog.kt
  app/src/main/java/com/nextcloud/talk/utils/FileUtils.java
  app/src/main/java/com/nextcloud/talk/webrtc/MagicPeerConnectionWrapper.java
  app/src/main/res/drawable/ic_baseline_camera_front_24.xml
  app/src/main/res/drawable/ic_baseline_camera_rear_24.xml
  app/src/main/res/drawable/ic_baseline_flash_off_24.xml
  app/src/main/res/drawable/ic_baseline_flash_on_24.xml
  app/src/main/res/drawable/ic_baseline_photo_camera_24.xml
  app/src/main/res/layout/activity_take_picture.xml
  app/src/main/res/layout/dialog_attachment.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
  scripts/analysis/findbugs-results.txt
  scripts/analysis/lint-results.txt
Labels: 2. developing

#1556 Bump ImagePicker
  app/build.gradle
Labels: 3. to review
