Repository nextcloud/talk-android, pull requests merged in 2022-10, with the labels that each got.

#2455 Like Android Files we should rely on generic camera feature, but not required.
  app/src/main/AndroidManifest.xml
Labels: 3. to review

#2450 toast when Direct Video Upload fails to start
  app/src/main/java/com/nextcloud/talk/controllers/ChatController.kt
Labels: 3. to review

#2467 bump kotlin to 17.0.20 and mark declaration usage as opt-in
  app/src/main/java/com/nextcloud/talk/callbacks/MentionAutocompleteCallback.java
  build.gradle
Labels: 3. to review, dependencies

#2481 Remove duplicate exifinterface dependency definition
  app/build.gradle
Labels: 3. to review, dependencies

#2482 Housekeeping Part 2
  app/src/main/java/com/nextcloud/talk/activities/CallNotificationActivity.java
  app/src/main/java/com/nextcloud/talk/utils/DisplayUtils.java
  docs/notifications.md
Labels: 3. to review

#2485 Use already fetched capabilities for user
  app/src/main/java/com/nextcloud/talk/controllers/AccountVerificationController.kt
Labels: 3. to review, backport-request

#2484 Fix computing new sessions in call
  app/src/main/java/com/nextcloud/talk/activities/CallActivity.java
Labels: bug, 2. developing, regression, backport-request, feature: ☎️ call

#2493 improve link preview design, add link description
  app/src/main/java/com/nextcloud/talk/adapters/messages/LinkPreview.kt
  app/src/main/res/layout/reference_inside_message.xml
Labels: 3. to review

#2509 Add version 15.0.0 to `CHANGELOG.md`
  CHANGELOG.md
Labels: 3. to review

#2490 improve fetching of user statuses in conversation list
  app/src/main/java/com/nextcloud/talk/activities/CallActivity.java
  app/src/main/java/com/nextcloud/talk/adapters/items/ConversationItem.java
  app/src/main/java/com/nextcloud/talk/api/NcApi.java
  app/src/main/java/com/nextcloud/talk/controllers/ChatController.kt
  app/src/main/java/com/nextcloud/talk/controllers/ConversationsListController.kt
  app/src/main/java/com/nextcloud/talk/models/json/conversations/Conversation.kt
  app/src/main/java/com/nextcloud/talk/models/json/statuses/StatusesOCS.kt
  app/src/main/java/com/nextcloud/talk/models/json/statuses/StatusesOverall.kt
  app/src/main/java/com/nextcloud/talk/ui/dialog/ConversationsListBottomDialog.kt
Labels: 3. to review, backport-request

#2518 simplify logic for server selection screen
  app/src/main/java/com/nextcloud/talk/controllers/ServerSelectionController.kt
  app/src/main/java/com/nextcloud/talk/controllers/SwitchAccountController.kt
  app/src/main/java/com/nextcloud/talk/utils/AccountUtils.kt
  app/src/main/res/layout/controller_server_selection.xml
Labels: 3. to review

#2532 File upload always fails for 1MB+
  app/src/main/java/com/nextcloud/talk/jobs/UploadAndShareFilesWorker.kt
  app/src/main/java/com/nextcloud/talk/upload/chunked/ChunkedFileUploader.kt
Labels: bug, 3. to review, feature: 🗨️ chat
