Repository nextcloud/talk-android, pull requests merged in 2022-02, with the labels that each got.

#1796 Bump constraint layout to 2.1.3
  app/build.gradle
  scripts/analysis/lint-results.txt
Labels: technical debt, dependencies

#1797 Bump okhttp to 4.9.3
  app/build.gradle
Labels: dependencies

#1798 Bump eventbus to 3.3.1
  app/build.gradle
Labels: dependencies

#1799 Bump dagger to 2.40.5
  app/build.gradle
Labels: dependencies

#1804 Update dependabot script
  .github/dependabot.yml
Labels: 3. to review, technical debt, feature: 🏗️ CI

#1805 fix dependabot yaml formatting
  .github/dependabot.yml
Labels: approved

#1809 bump open pr count to 20
  .github/dependabot.yml
Labels: feature: 🏗️ CI

#1285 fix design when keyboard is shown
  app/build.gradle
  app/src/gplay/java/com/nextcloud/talk/services/firebase/MagicFirebaseMessagingService.kt
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/nextcloud/talk/activities/MainActivity.kt
  app/src/main/java/com/nextcloud/talk/controllers/ChatController.kt
  app/src/main/java/com/nextcloud/talk/controllers/ContactsController.java
  app/src/main/java/com/nextcloud/talk/controllers/ConversationInfoController.kt
  app/src/main/java/com/nextcloud/talk/controllers/ConversationsListController.java
  app/src/main/java/com/nextcloud/talk/controllers/base/ButterKnifeController.kt
  app/src/main/java/com/nextcloud/talk/controllers/bottomsheet/CallMenuController.java
  app/src/main/java/com/nextcloud/talk/controllers/bottomsheet/ConversationOperationEnum.kt
  app/src/main/java/com/nextcloud/talk/controllers/bottomsheet/EntryMenuController.java
  app/src/main/java/com/nextcloud/talk/controllers/bottomsheet/OperationsMenuController.java
  app/src/main/java/com/nextcloud/talk/events/BottomSheetLockEvent.java
  app/src/main/java/com/nextcloud/talk/events/ConversationsListFetchDataEvent.kt
  app/src/main/java/com/nextcloud/talk/events/OpenConversationEvent.kt
  app/src/main/java/com/nextcloud/talk/jobs/LeaveConversationWorker.java
  app/src/main/java/com/nextcloud/talk/models/json/conversations/Conversation.java
  app/src/main/java/com/nextcloud/talk/ui/bottom/sheet/ProfileBottomSheet.kt
  app/src/main/java/com/nextcloud/talk/ui/dialog/ContactsBottomDialog.kt
  app/src/main/java/com/nextcloud/talk/ui/dialog/ConversationsListBottomDialog.kt
  app/src/main/java/com/nextcloud/talk/utils/KeyboardUtils.java
  app/src/main/java/com/nextcloud/talk/utils/ShareUtils.java
  app/src/main/res/drawable/ic_mimetype_folder_public.xml
  app/src/main/res/drawable/ic_mimetype_folder_starred.xml
  app/src/main/res/layout/controller_entry_menu.xml
  app/src/main/res/layout/controller_operations_menu.xml
  app/src/main/res/layout/dialog_bottom_contacts.xml
  app/src/main/res/layout/dialog_conversation_operations.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
  scripts/analysis/findbugs-results.txt
  scripts/analysis/lint-results.txt
Labels: 3. to review

#1819 Kotlin controller migration
  app/src/main/java/com/nextcloud/talk/adapters/items/AdvancedUserItem.java
  app/src/main/java/com/nextcloud/talk/controllers/ProfileController.java
  app/src/main/java/com/nextcloud/talk/controllers/ServerSelectionController.java
  app/src/main/java/com/nextcloud/talk/controllers/ServerSelectionController.kt
  app/src/main/java/com/nextcloud/talk/controllers/SwitchAccountController.java
  app/src/main/java/com/nextcloud/talk/controllers/SwitchAccountController.kt
  scripts/analysis/findbugs-results.txt
  scripts/analysis/lint-results.txt
Labels: 3. to review

#1821 Remove Parceler from model autocomplete and capabilities
  app/src/main/java/com/nextcloud/talk/models/json/autocomplete/AutocompleteOCS.java
  app/src/main/java/com/nextcloud/talk/models/json/autocomplete/AutocompleteOCS.kt
  app/src/main/java/com/nextcloud/talk/models/json/autocomplete/AutocompleteOverall.java
  app/src/main/java/com/nextcloud/talk/models/json/autocomplete/AutocompleteOverall.kt
  app/src/main/java/com/nextcloud/talk/models/json/autocomplete/AutocompleteUser.java
  app/src/main/java/com/nextcloud/talk/models/json/autocomplete/AutocompleteUser.kt
  app/src/main/java/com/nextcloud/talk/models/json/capabilities/Capabilities.java
  app/src/main/java/com/nextcloud/talk/models/json/capabilities/Capabilities.kt
  app/src/main/java/com/nextcloud/talk/models/json/capabilities/CapabilitiesList.java
  app/src/main/java/com/nextcloud/talk/models/json/capabilities/CapabilitiesList.kt
  app/src/main/java/com/nextcloud/talk/models/json/capabilities/CapabilitiesOCS.java
  app/src/main/java/com/nextcloud/talk/models/json/capabilities/CapabilitiesOCS.kt
  app/src/main/java/com/nextcloud/talk/models/json/capabilities/CapabilitiesOverall.java
  app/src/main/java/com/nextcloud/talk/models/json/capabilities/CapabilitiesOverall.kt
  app/src/main/java/com/nextcloud/talk/models/json/capabilities/NotificationsCapability.java
  app/src/main/java/com/nextcloud/talk/models/json/capabilities/NotificationsCapability.kt
  app/src/main/java/com/nextcloud/talk/models/json/capabilities/ProvisioningCapability.java
  app/src/main/java/com/nextcloud/talk/models/json/capabilities/ProvisioningCapability.kt
  app/src/main/java/com/nextcloud/talk/models/json/capabilities/SpreedCapability.java
  app/src/main/java/com/nextcloud/talk/models/json/capabilities/SpreedCapability.kt
  app/src/main/java/com/nextcloud/talk/models/json/capabilities/ThemingCapability.java
  app/src/main/java/com/nextcloud/talk/models/json/capabilities/ThemingCapability.kt
  scripts/analysis/findbugs-results.txt
Labels: 3. to review

#1824 Fix klint errors
  app/src/main/java/com/nextcloud/talk/controllers/ServerSelectionController.kt
Labels: bug, 3. to review

#1774 Android update WebRTC library
  app/build.gradle
  app/src/main/java/com/nextcloud/talk/activities/CallActivity.java
  app/src/main/java/com/nextcloud/talk/webrtc/PeerConnectionWrapper.java
  scripts/analysis/lint-up.rb
Labels: 3. to review

#1832 Migrate view items to native view bindings
  app/src/main/java/com/nextcloud/talk/adapters/items/AdvancedUserItem.java
  app/src/main/java/com/nextcloud/talk/adapters/items/AppItem.java
  app/src/main/java/com/nextcloud/talk/adapters/items/ContactItem.java
  app/src/main/java/com/nextcloud/talk/adapters/items/ConversationItem.java
  app/src/main/java/com/nextcloud/talk/adapters/items/GenericTextHeaderItem.java
  app/src/main/java/com/nextcloud/talk/adapters/items/MentionAutocompleteItem.java
  app/src/main/java/com/nextcloud/talk/adapters/items/MenuItem.java
  app/src/main/java/com/nextcloud/talk/adapters/items/NotificationSoundItem.java
  app/src/main/java/com/nextcloud/talk/adapters/items/ParticipantItem.java
  app/src/main/java/com/nextcloud/talk/adapters/items/ProgressItem.java
  app/src/main/java/com/nextcloud/talk/adapters/items/UserItem.java
  app/src/main/java/com/nextcloud/talk/controllers/ContactsController.java
  app/src/main/java/com/nextcloud/talk/controllers/ConversationInfoController.kt
  app/src/main/res/layout/rv_item_app.xml
  app/src/main/res/layout/rv_item_conversation_info_participant.xml
  app/src/main/res/layout/rv_item_menu.xml
  app/src/main/res/layout/rv_item_progress.xml
  app/src/main/res/values/strings.xml
  scripts/analysis/findbugs-results.txt
  scripts/analysis/lint-results.txt
Labels: 3. to review

#1836 Migrate EntryMenuController to Kotlin
  app/src/main/java/com/nextcloud/talk/controllers/bottomsheet/EntryMenuController.java
  app/src/main/java/com/nextcloud/talk/controllers/bottomsheet/EntryMenuController.kt
  scripts/analysis/findbugs-results.txt
  scripts/analysis/lint-results.txt
Labels: 3. to review

#1837 Migrate AccountVerificationController to kotlin
  app/src/main/java/com/nextcloud/talk/controllers/AccountVerificationController.java
  app/src/main/java/com/nextcloud/talk/controllers/AccountVerificationController.kt
  scripts/analysis/findbugs-results.txt
  scripts/analysis/lint-results.txt
Labels: 3. to review
