Repository nextcloud/talk-android, pull requests merged in 2022-07, with the labels that each got.

#2154 Add room database layer
  app/build.gradle
  app/schemas/com.nextcloud.talk.data.source.local.TalkDatabase/8.json
  app/src/androidTest/java/com/nextcloud/talk/activities/MainActivityTest.kt
  app/src/androidTest/java/com/nextcloud/talk/ui/LoginIT.java
  app/src/main/java/com/nextcloud/talk/activities/MainActivity.kt
  app/src/main/java/com/nextcloud/talk/adapters/items/ConversationItem.java
  app/src/main/java/com/nextcloud/talk/arbitrarystorage/ArbitraryStorageManager.kt
  app/src/main/java/com/nextcloud/talk/controllers/ConversationsListController.java
  app/src/main/java/com/nextcloud/talk/controllers/SettingsController.kt
  app/src/main/java/com/nextcloud/talk/dagger/modules/DatabaseModule.java
  app/src/main/java/com/nextcloud/talk/dagger/modules/RepositoryModule.kt
  app/src/main/java/com/nextcloud/talk/data/source/local/Migrations.kt
  app/src/main/java/com/nextcloud/talk/data/source/local/TalkDatabase.kt
  app/src/main/java/com/nextcloud/talk/data/source/local/converters/CapabilitiesConverter.kt
  app/src/main/java/com/nextcloud/talk/data/source/local/converters/ExternalSignalingServerConverter.kt
  app/src/main/java/com/nextcloud/talk/data/source/local/converters/HashMapHashMapConverter.kt
  app/src/main/java/com/nextcloud/talk/data/source/local/converters/PushConfigurationConverter.kt
  app/src/main/java/com/nextcloud/talk/data/source/local/converters/SignalingSettingsConverter.kt
  app/src/main/java/com/nextcloud/talk/data/storage/ArbitraryStorageMapper.kt
  app/src/main/java/com/nextcloud/talk/data/storage/ArbitraryStoragesDao.kt
  app/src/main/java/com/nextcloud/talk/data/storage/ArbitraryStoragesRepository.kt
  app/src/main/java/com/nextcloud/talk/data/storage/ArbitraryStoragesRepositoryImpl.kt
  app/src/main/java/com/nextcloud/talk/data/storage/model/ArbitraryStorage.kt
  app/src/main/java/com/nextcloud/talk/data/storage/model/ArbitraryStorageEntity.kt
  app/src/main/java/com/nextcloud/talk/data/user/UserMapper.kt
  app/src/main/java/com/nextcloud/talk/data/user/UsersDao.kt
  app/src/main/java/com/nextcloud/talk/data/user/UsersRepository.kt
  app/src/main/java/com/nextcloud/talk/data/user/UsersRepositoryImpl.kt
  app/src/main/java/com/nextcloud/talk/data/user/model/User.kt
  app/src/main/java/com/nextcloud/talk/data/user/model/UserEntity.kt
  app/src/main/java/com/nextcloud/talk/models/database/ArbitraryStorage.java
  app/src/main/java/com/nextcloud/talk/models/database/CapabilitiesUtil.java
  app/src/main/java/com/nextcloud/talk/models/database/User.java
  app/src/main/java/com/nextcloud/talk/models/json/capabilities/NotificationsCapability.kt
  app/src/main/java/com/nextcloud/talk/models/json/capabilities/ProvisioningCapability.kt
  app/src/main/java/com/nextcloud/talk/models/json/capabilities/SpreedCapability.kt
  app/src/main/java/com/nextcloud/talk/models/json/capabilities/ThemingCapability.kt
  app/src/main/java/com/nextcloud/talk/models/json/capabilities/UserStatusCapability.kt
  app/src/main/java/com/nextcloud/talk/models/json/signaling/settings/IceServer.kt
  app/src/main/java/com/nextcloud/talk/models/json/signaling/settings/SignalingSettings.kt
  app/src/main/java/com/nextcloud/talk/models/json/signaling/settings/SignalingSettingsOcs.kt
  app/src/main/java/com/nextcloud/talk/users/UserManager.kt
  app/src/main/java/com/nextcloud/talk/utils/ApiUtils.java
  app/src/main/java/com/nextcloud/talk/utils/DisplayUtils.java
  app/src/main/java/com/nextcloud/talk/utils/LegacyUserEntityMapper.kt
  app/src/main/java/com/nextcloud/talk/utils/database/arbitrarystorage/ArbitraryStorageModule.java
  app/src/main/java/com/nextcloud/talk/utils/database/arbitrarystorage/ArbitraryStorageUtils.java
  app/src/main/java/com/nextcloud/talk/utils/database/user/CapabilitiesUtilNew.kt
  app/src/main/java/com/nextcloud/talk/utils/database/user/CurrentUserProviderNew.kt
  app/src/main/java/com/nextcloud/talk/utils/database/user/UserModule.kt
  app/src/main/java/com/nextcloud/talk/utils/database/user/UserUtils.java
  app/src/main/java/com/nextcloud/talk/utils/preferences/AppPreferences.java
  app/src/main/java/com/nextcloud/talk/utils/preferences/preferencestorage/DatabaseStorageModule.java
  build.gradle
  scripts/analysis/findbugs-results.txt
  spotbugs-filter.xml
Labels: 3. to review, technical debt

#2190 Bump androidx.camera from 1.1.0-rc02 to 1.1.0
  app/build.gradle
Labels: 3. to review, dependencies

#2172 Upload profile picture from camera
  app/src/main/java/com/nextcloud/talk/application/NextcloudTalkApplication.kt
  app/src/main/java/com/nextcloud/talk/controllers/ChatController.kt
  app/src/main/java/com/nextcloud/talk/controllers/ProfileController.kt
  app/src/main/java/com/nextcloud/talk/dagger/modules/UtilsModule.kt
  app/src/main/java/com/nextcloud/talk/utils/permissions/PlatformPermissionUtil.kt
  app/src/main/java/com/nextcloud/talk/utils/permissions/PlatformPermissionUtilImpl.kt
  app/src/main/res/layout/controller_profile.xml
  app/src/main/res/values/strings.xml
Labels: 3. to review

#2194 Nullcheck disposable
  app/src/main/java/com/nextcloud/talk/controllers/ConversationsListController.java
Labels: 3. to review

#2196 14.1 RC2
  app/build.gradle
Labels: 3. to review

#2202 catch NPE for binding (loadCurrentStatus#onError)
  app/src/main/java/com/nextcloud/talk/ui/dialog/ChooseAccountDialogFragment.java
Labels: 3. to review

#2201 catch NPE for binding in toggleCallHeader
  app/src/main/java/com/nextcloud/talk/controllers/ContactsController.kt
Labels: 3. to review

#2207 fix NPE for binding in onEmojiClickListener
  app/src/main/java/com/nextcloud/talk/controllers/ChatController.kt
Labels: backport-request

#2211 Make private broadcast permission depend on applicationId
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/nextcloud/talk/activities/CallActivity.java
  app/src/main/java/com/nextcloud/talk/utils/permissions/PlatformPermissionUtil.kt
  app/src/main/java/com/nextcloud/talk/utils/permissions/PlatformPermissionUtilImpl.kt
Labels: 3. to review

#2210 Add method in NewBaseController to handle NPE catches for viewbinding
  app/src/main/java/com/nextcloud/talk/controllers/ContactsController.kt
  app/src/main/java/com/nextcloud/talk/controllers/base/NewBaseController.kt
Labels: 3. to review

#2199 Mark as read via notification
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/nextcloud/talk/jobs/NotificationWorker.java
  app/src/main/java/com/nextcloud/talk/models/json/push/DecryptedPushMessage.kt
  app/src/main/java/com/nextcloud/talk/receivers/MarkAsReadReceiver.kt
  scripts/analysis/findbugs-results.txt
Labels: 3. to review

#2219 Migrate calls and used classes/methods from requery to room
  app/src/gplay/java/com/nextcloud/talk/services/firebase/ChatAndCallMessagingService.kt
  app/src/main/java/com/nextcloud/talk/activities/CallActivity.java
  app/src/main/java/com/nextcloud/talk/activities/CallNotificationActivity.java
  app/src/main/java/com/nextcloud/talk/jobs/NotificationWorker.java
  app/src/main/java/com/nextcloud/talk/models/SignatureVerification.kt
  app/src/main/java/com/nextcloud/talk/ui/dialog/ChooseAccountDialogFragment.java
  app/src/main/java/com/nextcloud/talk/users/UserManager.kt
  app/src/main/java/com/nextcloud/talk/utils/ApiUtils.java
  app/src/main/java/com/nextcloud/talk/utils/NotificationUtils.kt
  app/src/main/java/com/nextcloud/talk/utils/PushUtils.java
  app/src/main/java/com/nextcloud/talk/webrtc/MagicWebSocketInstance.java
  app/src/main/java/com/nextcloud/talk/webrtc/WebSocketConnectionHelper.java
  scripts/analysis/findbugs-results.txt
Labels: 3. to review

#2221 Migrate contacts and creation of talk rooms from requery to room
  app/src/main/java/com/nextcloud/talk/adapters/items/ContactItem.java
  app/src/main/java/com/nextcloud/talk/controllers/ContactsController.kt
  app/src/main/java/com/nextcloud/talk/controllers/bottomsheet/OperationsMenuController.kt
  app/src/main/java/com/nextcloud/talk/ui/bottom/sheet/ProfileBottomSheet.kt
  scripts/analysis/findbugs-results.txt
Labels: 3. to review

#2222 Migrate further areas to room
  app/src/main/java/com/nextcloud/talk/adapters/items/AdvancedUserItem.java
  app/src/main/java/com/nextcloud/talk/controllers/ProfileController.kt
  app/src/main/java/com/nextcloud/talk/controllers/SettingsController.kt
  app/src/main/java/com/nextcloud/talk/controllers/SwitchAccountController.kt
  app/src/main/java/com/nextcloud/talk/ui/dialog/ChooseAccountDialogFragment.java
  app/src/main/java/com/nextcloud/talk/ui/dialog/SetStatusDialogFragment.kt
  app/src/main/java/com/nextcloud/talk/users/UserManager.kt
  app/src/main/java/com/nextcloud/talk/utils/AccountUtils.kt
  scripts/analysis/findbugs-results.txt
Labels: 3. to review

#2165 Improvements to analysis scripts and Drone configuration
  .drone.yml
  scripts/analysis/analysis-wrapper.sh
  scripts/analysis/getBranchName.sh
Labels: 3. to review, discussion

#2233 bump devcontainer to java11
  .devcontainer/Dockerfile
Labels: backport-request

#2232 Push token recovery should not use the standard httpClient object
  app/src/main/java/com/nextcloud/talk/jobs/PushRegistrationWorker.java
  app/src/main/java/com/nextcloud/talk/utils/PushUtils.java
Labels: 3. to review, backport-request

#2237 PushRegistrationWorker: fix missing injection causing NPE during login
  app/src/main/java/com/nextcloud/talk/jobs/PushRegistrationWorker.java
Labels: 3. to review, backport-request

#2223 Migrate remaining controllers from requery to room
  app/src/main/java/com/nextcloud/talk/controllers/AccountVerificationController.kt
  app/src/main/java/com/nextcloud/talk/controllers/ChatController.kt
  app/src/main/java/com/nextcloud/talk/controllers/GeocodingController.kt
  app/src/main/java/com/nextcloud/talk/controllers/LocationPickerController.kt
  app/src/main/java/com/nextcloud/talk/controllers/ServerSelectionController.kt
  app/src/main/java/com/nextcloud/talk/controllers/WebViewLoginController.kt
  app/src/main/java/com/nextcloud/talk/data/user/UsersDao.kt
  app/src/main/java/com/nextcloud/talk/data/user/UsersRepository.kt
  app/src/main/java/com/nextcloud/talk/data/user/UsersRepositoryImpl.kt
  app/src/main/java/com/nextcloud/talk/users/UserManager.kt
  app/src/main/java/com/nextcloud/talk/utils/AccountUtils.kt
Labels: 3. to review

#2245 Organize imports
  app/src/main/java/com/nextcloud/talk/utils/database/user/UserModule.kt
Labels: 3. to review

#2247 Organize imports
  app/src/main/java/com/nextcloud/talk/utils/database/user/UserModule.kt
Labels: 2. developing

#2251 Persistence cleanup
  app/build.gradle
  app/src/androidTest/java/com/nextcloud/talk/activities/MainActivityTest.kt
  app/src/main/java/com/nextcloud/talk/data/user/UsersDao.kt
  app/src/main/java/com/nextcloud/talk/data/user/UsersRepository.kt
  app/src/main/java/com/nextcloud/talk/data/user/UsersRepositoryImpl.kt
  app/src/main/java/com/nextcloud/talk/jobs/WebsocketConnectionsWorker.java
  app/src/main/java/com/nextcloud/talk/users/UserManager.kt
  app/src/main/java/com/nextcloud/talk/webrtc/MagicProximitySensor.java
Labels: 3. to review

#2254 update video icon in line with files client
  app/src/main/res/drawable/ic_mimetype_video.xml
Labels: 3. to review
