Repository nextcloud/talk-android, pull requests merged in 2022-08, with the labels that each got.

#2259 📊 Polishing polls
  app/src/main/java/com/nextcloud/talk/polls/adapters/PollCreateOptionViewHolder.kt
  app/src/main/java/com/nextcloud/talk/polls/adapters/PollCreateOptionsAdapter.kt
  app/src/main/java/com/nextcloud/talk/polls/adapters/PollResultVotersOverviewViewHolder.kt
  app/src/main/java/com/nextcloud/talk/polls/ui/PollCreateDialogFragment.kt
  app/src/main/res/layout/dialog_poll_create.xml
  app/src/main/res/layout/dialog_poll_results.xml
  app/src/main/res/layout/dialog_poll_vote.xml
  app/src/main/res/layout/poll_create_options_item.xml
  app/src/main/res/layout/poll_result_header_item.xml
  app/src/main/res/values-night/colors.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
Labels: 3. to review, feature: 📊 polls

#2268 Update AGP to 7.2.2
  build.gradle
Labels: 3. to review, backport-request

#2267 Fix status visibility in conversation list
  app/src/main/java/com/nextcloud/talk/adapters/items/ConversationItem.java
Labels: 3. to review, backport-request

#2277 Use singular and plural for vote(s) string
  app/src/main/java/com/nextcloud/talk/polls/ui/PollMainDialogFragment.kt
  app/src/main/res/values/strings.xml
Labels: 3. to review

#2274 Make equals null-safe in case no status is set
  app/src/main/java/com/nextcloud/talk/adapters/items/ConversationItem.java
Labels: 3. to review, backport-request

#2282 Fix branch detection for drone PRs
  .drone.yml
  scripts/analysis/analysis-wrapper.sh
  scripts/analysis/findbugs-results.txt
  scripts/analysis/getBranchName.sh
Labels: bug, 3. to review

#2285 ChatController: fix crash when opening conversation from notification
  app/src/main/java/com/nextcloud/talk/adapters/messages/IncomingPollMessageViewHolder.kt
  app/src/main/java/com/nextcloud/talk/adapters/messages/MessagePayload.kt
  app/src/main/java/com/nextcloud/talk/adapters/messages/OutcomingPollMessageViewHolder.kt
  app/src/main/java/com/nextcloud/talk/controllers/ChatController.kt
  scripts/analysis/lint-results.txt
Labels: 3. to review

#2289 Make sure to set swipe-to-reply after the room info has been loaded
  app/src/main/java/com/nextcloud/talk/controllers/ChatController.kt
Labels: 3. to review, backport-request

#2296 Fix some easy detekt issues and detekt.yml syntax
  app/src/main/java/com/nextcloud/talk/controllers/ChatController.kt
  app/src/main/java/com/nextcloud/talk/controllers/RingtoneSelectionController.kt
  app/src/main/java/com/nextcloud/talk/jobs/UploadAndShareFilesWorker.kt
  app/src/main/java/com/nextcloud/talk/models/json/converters/EnumSystemMessageTypeConverter.kt
  app/src/main/java/com/nextcloud/talk/ui/dialog/ShowReactionsDialog.kt
  app/src/main/java/com/nextcloud/talk/utils/AccountUtils.kt
  detekt.yml
Labels: 3. to review

#2294 Use issue form for bug report
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/config.yml
Labels: 3. to review

#2304 Load higher resoliton avatars in conversation list
  app/src/main/java/com/nextcloud/talk/controllers/ConversationsListController.java
Labels: 3. to review, backport-request

#2306 Load higher resoliton avatars in conversation list (2)
  app/src/main/java/com/nextcloud/talk/adapters/items/ConversationItem.java
Labels: 3. to review

#2310 Remove lovely dialogs uses
  app/src/main/java/com/nextcloud/talk/controllers/ConversationsListController.java
  app/src/main/java/com/nextcloud/talk/controllers/SettingsController.kt
  app/src/main/java/com/nextcloud/talk/interfaces/ConversationMenuInterface.kt
  app/src/main/java/com/nextcloud/talk/ui/dialog/ConversationsListBottomDialog.kt
Labels: 3. to review

#2313 Convert ConversationsListController to Kotlin, and get rid of ButterKnife
  app/build.gradle
  app/lint.xml
  app/src/main/java/com/nextcloud/talk/controllers/AccountVerificationController.kt
  app/src/main/java/com/nextcloud/talk/controllers/ChatController.kt
  app/src/main/java/com/nextcloud/talk/controllers/ContactsController.kt
  app/src/main/java/com/nextcloud/talk/controllers/ConversationInfoController.kt
  app/src/main/java/com/nextcloud/talk/controllers/ConversationsListController.java
  app/src/main/java/com/nextcloud/talk/controllers/ConversationsListController.kt
  app/src/main/java/com/nextcloud/talk/controllers/GeocodingController.kt
  app/src/main/java/com/nextcloud/talk/controllers/LocationPickerController.kt
  app/src/main/java/com/nextcloud/talk/controllers/LockedController.kt
  app/src/main/java/com/nextcloud/talk/controllers/ProfileController.kt
  app/src/main/java/com/nextcloud/talk/controllers/RingtoneSelectionController.kt
  app/src/main/java/com/nextcloud/talk/controllers/ServerSelectionController.kt
  app/src/main/java/com/nextcloud/talk/controllers/SettingsController.kt
  app/src/main/java/com/nextcloud/talk/controllers/SwitchAccountController.kt
  app/src/main/java/com/nextcloud/talk/controllers/WebViewLoginController.kt
  app/src/main/java/com/nextcloud/talk/controllers/base/BaseController.java
  app/src/main/java/com/nextcloud/talk/controllers/base/BaseController.kt
  app/src/main/java/com/nextcloud/talk/controllers/base/ButterKnifeController.kt
  app/src/main/java/com/nextcloud/talk/controllers/bottomsheet/EntryMenuController.kt
  app/src/main/java/com/nextcloud/talk/controllers/bottomsheet/OperationsMenuController.kt
  app/src/main/java/com/nextcloud/talk/ui/dialog/ConversationsListBottomDialog.kt
  detekt.yml
Labels: 3. to review

#2316 Replace lovelyDialogs with Material 3
  app/build.gradle
  app/src/main/java/com/nextcloud/talk/controllers/ConversationInfoController.kt
Labels: 3. to review, technical debt

#2318 Update to new home of forked libs
  app/build.gradle
Labels: 3. to review, technical debt, backport-request

#2327 prevent NPE if UI has already been teared down
  app/src/main/java/com/nextcloud/talk/controllers/ChatController.kt
Labels: 3. to review, backport-request

#2307 handle expiring messages
  app/src/main/java/com/nextcloud/talk/api/NcApi.java
  app/src/main/java/com/nextcloud/talk/controllers/ChatController.kt
  app/src/main/java/com/nextcloud/talk/controllers/ConversationInfoController.kt
  app/src/main/java/com/nextcloud/talk/models/json/chat/ChatMessage.kt
  app/src/main/java/com/nextcloud/talk/models/json/chat/ChatUtils.kt
  app/src/main/java/com/nextcloud/talk/models/json/conversations/Conversation.kt
  app/src/main/java/com/nextcloud/talk/models/json/converters/EnumSystemMessageTypeConverter.kt
  app/src/main/java/com/nextcloud/talk/utils/ApiUtils.java
  app/src/main/java/com/nextcloud/talk/utils/preferences/preferencestorage/DatabaseStorageModule.java
  app/src/main/res/layout/controller_conversation_info.xml
  app/src/main/res/values/arrays.xml
  app/src/main/res/values/strings.xml
Labels: enhancement, 3. to review, feature: 🗨️ chat, feature: ⚙️ settings

#2330 Update last forked lib reference to new home
  app/build.gradle
Labels: 3. to review

#2334 i18n: Change style of sentence
  app/src/main/res/values/strings.xml
Labels: backport-request

#2343 Remove duplicated copyright explanation
  CONTRIBUTING.md
  contribute/HowToApplyALicense.md
Labels: 3. to review
