Repository nextcloud/talk-android, pull requests merged in 2022-05, with the labels that each got.

#1952 fix NumberFormatException
  app/src/main/java/com/nextcloud/talk/adapters/SharedItemsListAdapter.kt
  app/src/main/java/com/nextcloud/talk/controllers/ChatController.kt
  app/src/main/java/com/nextcloud/talk/jobs/DownloadFileToCacheWorker.kt
  app/src/main/java/com/nextcloud/talk/repositories/SharedItem.kt
  app/src/main/java/com/nextcloud/talk/utils/FileViewerUtils.kt
  app/src/main/java/com/nextcloud/talk/viewmodels/SharedItemsViewModel.kt
Labels: 3. to review

#1951 Fix typo in name of method to check if video should not be received
  app/src/main/java/com/nextcloud/talk/webrtc/PeerConnectionWrapper.java
Labels: bug, 3. to review

#1955 Update screenshots
  fastlane/metadata/android/en-US/phoneScreenshots/conversationList_dark.png
  fastlane/metadata/android/en-US/phoneScreenshots/conversationList_light.png
  fastlane/metadata/android/en-US/phoneScreenshots/searchParticipant_light.png
  fastlane/metadata/android/en-US/phoneScreenshots/voiceRecord_light.png
Labels: 3. to review

#1964 fix to load conversations when servers status app is disabled
  app/src/main/java/com/nextcloud/talk/adapters/items/ConversationItem.java
  app/src/main/java/com/nextcloud/talk/controllers/ConversationsListController.java
Labels: 3. to review

#1965 Catch NPEs on view bindings
  app/src/main/java/com/nextcloud/talk/controllers/ChatController.kt
  app/src/main/java/com/nextcloud/talk/controllers/ProfileController.kt
  app/src/main/java/com/nextcloud/talk/controllers/ServerSelectionController.kt
  app/src/main/java/com/nextcloud/talk/controllers/WebViewLoginController.kt
Labels: 3. to review

#1973 Reduce number of Detekt issues
  app/src/main/java/com/nextcloud/talk/controllers/LocationPickerController.kt
  app/src/main/java/com/nextcloud/talk/models/json/chat/ChatUtils.kt
  detekt.yml
Labels: 3. to review

#1979 Add handling for "event.participants.update.all"
  app/src/main/java/com/nextcloud/talk/activities/CallActivity.java
  app/src/main/java/com/nextcloud/talk/webrtc/Globals.java
  app/src/main/java/com/nextcloud/talk/webrtc/MagicWebSocketInstance.java
  scripts/analysis/findbugs-results.txt
Labels: 3. to review, backport-request, don't merge

#1969 Add old screenshot from F-Droid
  fastlane/metadata/android/en-US/phoneScreenshots/contacts_selection.jpg
  fastlane/metadata/android/en-US/phoneScreenshots/conversations.jpg
  fastlane/metadata/android/en-US/phoneScreenshots/receive_gifs.jpg
  fastlane/metadata/android/en-US/phoneScreenshots/receive_screenshare.jpg
  fastlane/metadata/android/en-US/phoneScreenshots/server_login.jpg
Labels: 3. to review, backport-request

#1989 Always show reaction count
  app/src/main/java/com/nextcloud/talk/adapters/messages/Reaction.kt
Labels: 3. to review, backport-request

#1950 Hide shared items toolbar on scroll
  app/src/main/res/layout/activity_shared_items.xml
Labels: 3. to review, backport-request

#1957 Hide reactions from menu if conversation is read-only
  app/src/main/java/com/nextcloud/talk/ui/dialog/MessageActionsDialog.kt
Labels: 3. to review, backport-request

#2002 avoid NPE
  app/src/main/java/com/nextcloud/talk/controllers/ConversationsListController.java
Labels: 3. to review

#2001 make attributes of file nullable and handle null values
  app/src/main/java/com/nextcloud/talk/adapters/SharedItemsGridAdapter.kt
  app/src/main/java/com/nextcloud/talk/adapters/SharedItemsListAdapter.kt
  app/src/main/java/com/nextcloud/talk/adapters/messages/MagicPreviewMessageViewHolder.java
  app/src/main/java/com/nextcloud/talk/repositories/SharedItem.kt
  app/src/main/java/com/nextcloud/talk/utils/DrawableUtils.kt
  app/src/main/java/com/nextcloud/talk/utils/FileViewerUtils.kt
  app/src/main/java/com/nextcloud/talk/viewmodels/SharedItemsViewModel.kt
Labels: 3. to review

#1922 Migrate OperationsMenuController to kotlin
  app/src/main/java/com/nextcloud/talk/controllers/bottomsheet/OperationsMenuController.java
  app/src/main/java/com/nextcloud/talk/controllers/bottomsheet/OperationsMenuController.kt
  scripts/analysis/findbugs-results.txt
  scripts/analysis/lint-results.txt
Labels: 3. to review, technical debt

#2006 Bugfix/1977/fix NPE in BrowserFile
  app/src/main/java/com/nextcloud/talk/components/filebrowser/models/BrowserFile.java
Labels: 3. to review, backport-request

#2005 Bugfix/1978/fix npe in peerConnectionWrapper
  app/src/main/java/com/nextcloud/talk/activities/CallActivity.java
Labels: 3. to review, backport-request

#2007 Hide actions reaction on deleted messages
  app/src/main/java/com/nextcloud/talk/adapters/messages/Reaction.kt
  app/src/main/java/com/nextcloud/talk/controllers/ChatController.kt
  app/src/main/java/com/nextcloud/talk/controllers/ProfileController.kt
  app/src/main/java/com/nextcloud/talk/controllers/ServerSelectionController.kt
  app/src/main/java/com/nextcloud/talk/controllers/WebViewLoginController.kt
  app/src/main/java/com/nextcloud/talk/models/json/chat/ChatMessage.java
  app/src/main/java/com/nextcloud/talk/ui/dialog/MessageActionsDialog.kt
  detekt.yml
Labels: 3. to review, backport-request, feature: 🗨️ chat

#1993 disable call buttons if calls are disabled by capability
  app/src/main/java/com/nextcloud/talk/controllers/ChatController.kt
  app/src/main/java/com/nextcloud/talk/models/database/CapabilitiesUtil.java
Labels: 3. to review

#2019 Feature/1948/respect chat permission
  app/src/main/java/com/nextcloud/talk/controllers/ChatController.kt
  app/src/main/java/com/nextcloud/talk/controllers/ConversationsListController.java
  app/src/main/java/com/nextcloud/talk/models/json/conversations/Conversation.java
  app/src/main/java/com/nextcloud/talk/ui/dialog/MessageActionsDialog.kt
  app/src/main/java/com/nextcloud/talk/ui/dialog/ShowReactionsDialog.kt
  app/src/main/java/com/nextcloud/talk/utils/AttendeePermissionsUtil.kt
  app/src/main/res/values/strings.xml
  app/src/test/java/com/nextcloud/talk/utils/AttendeePermissionsUtilTest.kt
Labels: 3. to review

#2016 TakePhotoActivity: Use full field of view
  app/src/main/java/com/nextcloud/talk/activities/TakePhotoActivity.java
Labels: 3. to review

#1923 Reply from notification
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/nextcloud/talk/jobs/NotificationWorker.java
  app/src/main/java/com/nextcloud/talk/receivers/DirectReplyReceiver.kt
  app/src/main/java/com/nextcloud/talk/utils/NotificationUtils.kt
  app/src/main/java/com/nextcloud/talk/utils/bundle/BundleKeys.kt
  scripts/analysis/findbugs-results.txt
Labels: enhancement, 3. to review, feature: 🔔 notifications

#2025 build: Improve handling of webrtc download
  app/build.gradle
  buildSrc/build.gradle
  buildSrc/src/main/groovy/com/nextcloud/talk/gradle/DownloadWebRtcTask.groovy
Labels: 3. to review

#2039 Make bottom_sheets initial state collapsed for the rounded top corners
  app/src/main/java/com/nextcloud/talk/ui/dialog/AttachmentDialog.kt
  app/src/main/java/com/nextcloud/talk/ui/dialog/AudioOutputDialog.kt
  app/src/main/java/com/nextcloud/talk/ui/dialog/ContactsBottomDialog.kt
  app/src/main/java/com/nextcloud/talk/ui/dialog/ConversationsListBottomDialog.kt
  app/src/main/java/com/nextcloud/talk/ui/dialog/MessageActionsDialog.kt
  app/src/main/java/com/nextcloud/talk/ui/dialog/ScopeDialog.kt
  app/src/main/java/com/nextcloud/talk/ui/dialog/ShowReactionsDialog.kt
  app/src/main/res/values/styles.xml
Labels: 3. to review

#2041 Add execution flag
  scripts/hooks/pre-commit
  scripts/hooks/pre-push
Labels: 3. to review

#2045 Updating command-rebase.yml workflow from template
  .github/workflows/command-rebase.yml
Labels: dependencies

#2043 Migrate SettingsController to kotlin + viewbinding
  app/src/main/java/com/nextcloud/talk/controllers/SettingsController.java
  app/src/main/java/com/nextcloud/talk/controllers/SettingsController.kt
  app/src/main/java/com/nextcloud/talk/models/json/generic/GenericOverall.kt
  detekt.yml
  scripts/analysis/findbugs-results.txt
  scripts/analysis/lint-results.txt
Labels: 3. to review, technical debt

#2053 add silent send option
  app/src/main/java/com/nextcloud/talk/api/NcApi.java
  app/src/main/java/com/nextcloud/talk/controllers/ChatController.kt
  app/src/main/java/com/nextcloud/talk/receivers/DirectReplyReceiver.kt
  app/src/main/res/drawable/ic_baseline_notifications_off_24.xml
  app/src/main/res/menu/chat_send_menu.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: 3. to review

#2058 avoid NPE when initializing chat permission
  app/src/main/java/com/nextcloud/talk/controllers/ChatController.kt
Labels: 3. to review

#2048 Reply from notification - initial error handling
  app/src/main/java/com/nextcloud/talk/receivers/DirectReplyReceiver.kt
  app/src/main/res/values/strings.xml
Labels: design, 2. developing

#2063 build: Fix/optimize gradle repo configuration
  build.gradle
Labels: 3. to review

#2065 Remove parceler annotation processor
  app/build.gradle
  app/src/main/java/com/nextcloud/talk/activities/CallActivity.java
Labels: 3. to review

#2068 Bump gradle 7.3.3 -> 7.4.2
  gradle/wrapper/gradle-wrapper.properties
Labels: 3. to review

#2072 Revert compile sdk to 30
  app/build.gradle
Labels: 3. to review

#2073 Bump compile sdk to 31
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/nextcloud/talk/activities/MainActivity.kt
  app/src/main/java/com/nextcloud/talk/controllers/ChatController.kt
  app/src/main/java/com/nextcloud/talk/jobs/ContactAddressBookWorker.kt
  app/src/main/java/com/nextcloud/talk/utils/ContactUtils.kt
  app/src/main/java/com/nextcloud/talk/utils/UriUtils.kt
  app/src/main/java/com/nextcloud/talk/webrtc/MagicBluetoothManager.java
Labels: 2. developing

#2079 bump camera to 1.1.0RC01 and unify version info
  app/build.gradle
Labels: 3. to review, technical debt, dependencies

#2081 Revert material back to 1.5.0
  app/build.gradle
Labels: 3. to review

#2015 Implement points from "Shared items" review
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/nextcloud/talk/adapters/SharedItemsGridAdapter.kt
  app/src/main/java/com/nextcloud/talk/adapters/SharedItemsListAdapter.kt
  app/src/main/java/com/nextcloud/talk/application/NextcloudTalkApplication.kt
  app/src/main/java/com/nextcloud/talk/controllers/ChatController.kt
  app/src/main/java/com/nextcloud/talk/controllers/ConversationInfoController.kt
  app/src/main/java/com/nextcloud/talk/dagger/modules/RepositoryModule.kt
  app/src/main/java/com/nextcloud/talk/dagger/modules/ViewModelModule.kt
  app/src/main/java/com/nextcloud/talk/repositories/SharedItem.kt
  app/src/main/java/com/nextcloud/talk/repositories/SharedItemType.kt
  app/src/main/java/com/nextcloud/talk/repositories/SharedItemsRepository.kt
  app/src/main/java/com/nextcloud/talk/repositories/SharedMediaItems.kt
  app/src/main/java/com/nextcloud/talk/shareditems/activities/SharedItemsActivity.kt
  app/src/main/java/com/nextcloud/talk/shareditems/adapters/SharedItemsAdapter.kt
  app/src/main/java/com/nextcloud/talk/shareditems/adapters/SharedItemsGridViewHolder.kt
  app/src/main/java/com/nextcloud/talk/shareditems/adapters/SharedItemsListViewHolder.kt
  app/src/main/java/com/nextcloud/talk/shareditems/adapters/SharedItemsViewHolder.kt
  app/src/main/java/com/nextcloud/talk/shareditems/model/SharedItem.kt
  app/src/main/java/com/nextcloud/talk/shareditems/model/SharedItemType.kt
  app/src/main/java/com/nextcloud/talk/shareditems/model/SharedMediaItems.kt
  app/src/main/java/com/nextcloud/talk/shareditems/repositories/SharedItemsRepository.kt
  app/src/main/java/com/nextcloud/talk/shareditems/repositories/SharedItemsRepositoryImpl.kt
  app/src/main/java/com/nextcloud/talk/shareditems/viewmodels/SharedItemsViewModel.kt
  app/src/main/java/com/nextcloud/talk/utils/FileViewerUtils.kt
  app/src/main/java/com/nextcloud/talk/viewmodels/SharedItemsViewModel.kt
  app/src/main/res/layout/activity_shared_items.xml
  app/src/main/res/values/strings.xml
Labels: 3. to review

#2091 Add release 14.0.2 to CHANGELOG
  CHANGELOG.md
Labels: 3. to review

#2094 Remove kotlin option jvmTarget = "1.8"
  app/build.gradle
Labels: 3. to review

#2097 Add old screenshot from F-Droid (missed one)
  fastlane/metadata/android/en-US/phoneScreenshots/contacts_search.jpg
Labels: 3. to review

#2098 Externalize string in 'menu_conversation.xml'
  app/src/main/res/menu/menu_conversation.xml
Labels: 3. to review

#2093 add silent call feature
  app/src/main/java/com/nextcloud/talk/activities/CallActivity.java
  app/src/main/java/com/nextcloud/talk/api/NcApi.java
  app/src/main/java/com/nextcloud/talk/controllers/ChatController.kt
  app/src/main/java/com/nextcloud/talk/utils/bundle/BundleKeys.kt
  app/src/main/res/menu/chat_call_menu.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: 3. to review

#2100 Catch RuntimeException thrown by NotificationManager
  app/src/main/java/com/nextcloud/talk/controllers/ChatController.kt
Labels: 3. to review
