Repository nextcloud/talk-android, pull requests merged in 2022-03, with the labels that each got.

#1845 Migrate remaining status models to kotlin
  app/src/main/java/com/nextcloud/talk/models/json/status/StatusOCS.java
  app/src/main/java/com/nextcloud/talk/models/json/status/StatusOCS.kt
  app/src/main/java/com/nextcloud/talk/models/json/status/StatusOverall.java
  app/src/main/java/com/nextcloud/talk/models/json/status/StatusOverall.kt
  app/src/main/java/com/nextcloud/talk/ui/dialog/ChooseAccountDialogFragment.java
Labels: 3. to review, technical debt

#1847 Migrate statuses overall to kotlin data classes
  app/src/main/java/com/nextcloud/talk/models/json/statuses/StatusesOCS.java
  app/src/main/java/com/nextcloud/talk/models/json/statuses/StatusesOCS.kt
  app/src/main/java/com/nextcloud/talk/models/json/statuses/StatusesOverall.java
  app/src/main/java/com/nextcloud/talk/models/json/statuses/StatusesOverall.kt
Labels: 3. to review

#1846 Bugfix/noid/fix can leave api check
  app/src/main/java/com/nextcloud/talk/controllers/ConversationInfoController.kt
  app/src/main/java/com/nextcloud/talk/models/json/conversations/Conversation.java
  app/src/main/java/com/nextcloud/talk/ui/dialog/ConversationsListBottomDialog.kt
Labels: 3. to review

#1854 Updating command-rebase.yml workflow from template
  .github/workflows/command-rebase.yml
Labels: dependencies

#1851 add groups and circles to system messages ("add"+"remove")
  app/src/main/java/com/nextcloud/talk/adapters/messages/MagicSystemMessageViewHolder.java
  app/src/main/java/com/nextcloud/talk/models/json/chat/ChatMessage.java
  app/src/main/java/com/nextcloud/talk/models/json/chat/ChatUtils.kt
  app/src/main/java/com/nextcloud/talk/models/json/converters/EnumSystemMessageTypeConverter.kt
Labels: bug, 3. to review, feature: 🗨️ chat

#1841 Bugfix/1839/fail to set empty status message
  app/src/main/java/com/nextcloud/talk/ui/dialog/SetStatusDialogFragment.kt
Labels: 3. to review

#1864 Detekt improvements
  app/src/gplay/java/com/nextcloud/talk/services/firebase/MagicFirebaseMessagingService.kt
  app/src/gplay/java/com/nextcloud/talk/utils/ClosedInterfaceImpl.kt
  app/src/main/java/com/nextcloud/talk/activities/MainActivity.kt
  app/src/main/java/com/nextcloud/talk/adapters/messages/IncomingLocationMessageViewHolder.kt
  app/src/main/java/com/nextcloud/talk/adapters/messages/OutcomingLocationMessageViewHolder.kt
  app/src/main/java/com/nextcloud/talk/controllers/AccountVerificationController.kt
  app/src/main/java/com/nextcloud/talk/controllers/ChatController.kt
  app/src/main/java/com/nextcloud/talk/controllers/LocationPickerController.kt
  app/src/main/java/com/nextcloud/talk/controllers/ServerSelectionController.kt
  app/src/main/java/com/nextcloud/talk/controllers/SwitchAccountController.kt
  app/src/main/java/com/nextcloud/talk/controllers/bottomsheet/EntryMenuController.kt
  app/src/main/java/com/nextcloud/talk/jobs/ContactAddressBookWorker.kt
  app/src/main/java/com/nextcloud/talk/jobs/UploadAndShareFilesWorker.kt
  app/src/main/java/com/nextcloud/talk/ui/dialog/SetStatusDialogFragment.kt
  app/src/main/java/com/nextcloud/talk/utils/AccountUtils.kt
  app/src/main/java/com/nextcloud/talk/utils/ImageEmojiEditText.kt
  app/src/main/java/com/nextcloud/talk/utils/NotificationUtils.kt
  app/src/main/java/com/nextcloud/talk/utils/UriUtils.kt
  detekt.yml
  scripts/analysis/lint-results.txt
Labels: 3. to review, technical debt

#1870 Workaround for crash when loading avatar
  app/src/main/java/com/nextcloud/talk/controllers/ChatController.kt
Labels: bug, 3. to review, feature: 🗨️ chat

#1865 Conversation view shows search bar when opened from notification
  app/src/main/java/com/nextcloud/talk/activities/MainActivity.kt
  app/src/main/java/com/nextcloud/talk/utils/ConductorRemapping.kt
  detekt.yml
Labels: bug, 3. to review, feature: 🔔 notifications

#1862 Migrate controllers to kotlin
  app/src/androidTest/java/com/nextcloud/talk/utils/ShareUtilsIT.kt
  app/src/gplay/java/com/nextcloud/talk/services/firebase/MagicFirebaseMessagingService.kt
  app/src/gplay/java/com/nextcloud/talk/utils/ClosedInterfaceImpl.kt
  app/src/main/java/com/nextcloud/talk/adapters/messages/IncomingVoiceMessageViewHolder.kt
  app/src/main/java/com/nextcloud/talk/adapters/messages/MagicIncomingTextMessageViewHolder.kt
  app/src/main/java/com/nextcloud/talk/adapters/messages/MagicOutcomingTextMessageViewHolder.kt
  app/src/main/java/com/nextcloud/talk/adapters/messages/OutcomingVoiceMessageViewHolder.kt
  app/src/main/java/com/nextcloud/talk/application/NextcloudTalkApplication.kt
  app/src/main/java/com/nextcloud/talk/controllers/AccountVerificationController.kt
  app/src/main/java/com/nextcloud/talk/controllers/ChatController.kt
  app/src/main/java/com/nextcloud/talk/controllers/ConversationInfoController.kt
  app/src/main/java/com/nextcloud/talk/controllers/RingtoneSelectionController.java
  app/src/main/java/com/nextcloud/talk/controllers/RingtoneSelectionController.kt
  app/src/main/java/com/nextcloud/talk/controllers/ServerSelectionController.kt
  app/src/main/java/com/nextcloud/talk/controllers/SwitchAccountController.kt
  app/src/main/java/com/nextcloud/talk/controllers/WebViewLoginController.java
  app/src/main/java/com/nextcloud/talk/controllers/WebViewLoginController.kt
  app/src/main/java/com/nextcloud/talk/controllers/bottomsheet/EntryMenuController.kt
  app/src/main/java/com/nextcloud/talk/jobs/ContactAddressBookWorker.kt
  app/src/main/java/com/nextcloud/talk/jobs/DownloadFileToCacheWorker.kt
  app/src/main/java/com/nextcloud/talk/utils/AccountUtils.kt
  app/src/main/java/com/nextcloud/talk/utils/DateConstants.kt
  app/src/main/java/com/nextcloud/talk/utils/DateUtils.kt
  app/src/main/java/com/nextcloud/talk/utils/ssl/SSLSocketFactoryCompat.kt
  detekt.yml
  scripts/analysis/findbugs-results.txt
  scripts/analysis/lint-results.txt
Labels: 3. to review, technical debt

#1874 Use ktlint plugin instead of manual ktlint tasks
  .github/workflows/check.yml
  app/build.gradle
  app/src/main/java/com/nextcloud/talk/controllers/ServerSelectionController.kt
  app/src/main/java/com/nextcloud/talk/controllers/WebViewLoginController.kt
  app/src/main/java/com/nextcloud/talk/ui/dialog/SetStatusDialogFragment.kt
  build.gradle
  scripts/hooks/pre-commit
  scripts/hooks/pre-push
Labels: 3. to review, technical debt

#1876 Bugfix/1853/fix query map
  app/src/gplay/java/com/nextcloud/talk/services/firebase/MagicFirebaseMessagingService.kt
  app/src/main/java/com/nextcloud/talk/activities/CallActivity.java
  app/src/main/java/com/nextcloud/talk/activities/CallNotificationActivity.java
  app/src/main/java/com/nextcloud/talk/api/NcApi.java
  app/src/main/java/com/nextcloud/talk/controllers/ConversationInfoController.kt
Labels: 3. to review

#1875 Use correct API endpoint for predefined status
  app/src/main/java/com/nextcloud/talk/ui/dialog/SetStatusDialogFragment.kt
  app/src/main/java/com/nextcloud/talk/utils/ApiUtils.java
  detekt.yml
Labels: 3. to review

#1886 Use Transceivers instead of constraints to discard received video tracks
  app/src/main/java/com/nextcloud/talk/adapters/ParticipantsAdapter.java
  app/src/main/java/com/nextcloud/talk/webrtc/PeerConnectionWrapper.java
Labels: 3. to review
