Repository nextcloud/talk-android, pull requests merged in 2022-12, with the labels that each got.

#2601 Fix reconnection when the web socket was abruptly closed
  app/src/main/java/com/nextcloud/talk/activities/CallActivity.java
Labels: bug, 3. to review, feature: ☎️ call

#2596 Feature/2537/react to given reactions
  app/src/main/java/com/nextcloud/talk/adapters/messages/CommonMessageInterface.kt
  app/src/main/java/com/nextcloud/talk/adapters/messages/IncomingLinkPreviewMessageViewHolder.kt
  app/src/main/java/com/nextcloud/talk/adapters/messages/IncomingLocationMessageViewHolder.kt
  app/src/main/java/com/nextcloud/talk/adapters/messages/IncomingPollMessageViewHolder.kt
  app/src/main/java/com/nextcloud/talk/adapters/messages/IncomingPreviewMessageViewHolder.java
  app/src/main/java/com/nextcloud/talk/adapters/messages/IncomingTextMessageViewHolder.kt
  app/src/main/java/com/nextcloud/talk/adapters/messages/IncomingVoiceMessageViewHolder.kt
  app/src/main/java/com/nextcloud/talk/adapters/messages/MagicPreviewMessageViewHolder.java
  app/src/main/java/com/nextcloud/talk/adapters/messages/OutcomingLinkPreviewMessageViewHolder.kt
  app/src/main/java/com/nextcloud/talk/adapters/messages/OutcomingLocationMessageViewHolder.kt
  app/src/main/java/com/nextcloud/talk/adapters/messages/OutcomingPollMessageViewHolder.kt
  app/src/main/java/com/nextcloud/talk/adapters/messages/OutcomingPreviewMessageViewHolder.java
  app/src/main/java/com/nextcloud/talk/adapters/messages/OutcomingTextMessageViewHolder.kt
  app/src/main/java/com/nextcloud/talk/adapters/messages/OutcomingVoiceMessageViewHolder.kt
  app/src/main/java/com/nextcloud/talk/adapters/messages/PreviewMessageViewHolder.kt
  app/src/main/java/com/nextcloud/talk/adapters/messages/Reaction.kt
  app/src/main/java/com/nextcloud/talk/adapters/messages/SystemMessageViewHolder.java
  app/src/main/java/com/nextcloud/talk/adapters/messages/TalkMessagesListAdapter.java
  app/src/main/java/com/nextcloud/talk/adapters/messages/UnreadNoticeMessageViewHolder.java
  app/src/main/java/com/nextcloud/talk/controllers/ChatController.kt
  app/src/main/java/com/nextcloud/talk/dagger/modules/RepositoryModule.kt
  app/src/main/java/com/nextcloud/talk/models/domain/ReactionAddedModel.kt
  app/src/main/java/com/nextcloud/talk/models/domain/ReactionDeletedModel.kt
  app/src/main/java/com/nextcloud/talk/repositories/reactions/ReactionsRepository.kt
  app/src/main/java/com/nextcloud/talk/repositories/reactions/ReactionsRepositoryImpl.kt
  app/src/main/java/com/nextcloud/talk/ui/dialog/MessageActionsDialog.kt
  app/src/main/java/com/nextcloud/talk/utils/FileViewerUtils.kt
  app/src/main/res/layout/reactions_inside_message.xml
Labels: 3. to review

#2566 Bugfix/1724followup/improve notification sound handling
  app/src/main/java/com/nextcloud/talk/activities/CallNotificationActivity.kt
  app/src/main/java/com/nextcloud/talk/jobs/NotificationWorker.kt
  app/src/main/java/com/nextcloud/talk/utils/DoNotDisturbUtils.kt
  app/src/main/java/com/nextcloud/talk/utils/NotificationUtils.kt
  app/src/main/java/com/nextcloud/talk/utils/bundle/BundleKeys.kt
  app/src/test/java/com/nextcloud/talk/utils/DoNotDisturbUtilsTest.java
Labels: 3. to review, don't merge

#2613 fix crash when joining call while silent ringtone is set
  app/src/main/java/com/nextcloud/talk/activities/CallActivity.java
Labels: 3. to review

#2616 🐻‍❄️ Support latest emojis
  app/build.gradle
  app/src/main/java/com/nextcloud/talk/adapters/messages/IncomingPreviewMessageViewHolder.java
  app/src/main/java/com/nextcloud/talk/adapters/messages/OutcomingPreviewMessageViewHolder.java
  app/src/main/java/com/nextcloud/talk/adapters/messages/PreviewMessageViewHolder.kt
  app/src/main/java/com/nextcloud/talk/application/NextcloudTalkApplication.kt
  app/src/main/java/com/nextcloud/talk/controllers/ChatController.kt
  app/src/main/java/com/nextcloud/talk/jobs/NotificationWorker.kt
  app/src/main/java/com/nextcloud/talk/ui/theme/TalkSpecificViewThemeUtils.kt
  app/src/main/java/com/nextcloud/talk/utils/DisplayUtils.java
  app/src/main/java/com/nextcloud/talk/utils/EmojiTextInputEditText.java
  app/src/main/java/com/nextcloud/talk/utils/FileViewerUtils.kt
  app/src/main/java/com/nextcloud/talk/utils/ImageEmojiEditText.kt
  app/src/main/res/layout/account_item.xml
  app/src/main/res/layout/controller_conversation_info.xml
  app/src/main/res/layout/controller_profile.xml
  app/src/main/res/layout/controller_settings.xml
  app/src/main/res/layout/current_account_item.xml
  app/src/main/res/layout/dialog_poll_main.xml
  app/src/main/res/layout/item_custom_incoming_link_preview_message.xml
  app/src/main/res/layout/item_custom_incoming_location_message.xml
  app/src/main/res/layout/item_custom_incoming_poll_message.xml
  app/src/main/res/layout/item_custom_incoming_preview_message.xml
  app/src/main/res/layout/item_custom_incoming_text_message.xml
  app/src/main/res/layout/item_custom_incoming_voice_message.xml
  app/src/main/res/layout/item_custom_outcoming_link_preview_message.xml
  app/src/main/res/layout/item_custom_outcoming_location_message.xml
  app/src/main/res/layout/item_custom_outcoming_poll_message.xml
  app/src/main/res/layout/item_custom_outcoming_preview_message.xml
  app/src/main/res/layout/item_custom_outcoming_text_message.xml
  app/src/main/res/layout/item_message_quote.xml
  app/src/main/res/layout/item_reactions_tab.xml
  app/src/main/res/layout/item_system_message.xml
  app/src/main/res/layout/reaction_item.xml
  app/src/main/res/layout/reference_inside_message.xml
  app/src/main/res/layout/rv_item_contact.xml
  app/src/main/res/layout/rv_item_conversation_info_participant.xml
  app/src/main/res/layout/rv_item_conversation_with_last_message.xml
  app/src/main/res/layout/rv_item_search_message.xml
  app/src/main/res/layout/shared_item_list.xml
Labels: 3. to review

#2622 🕰️Localize time formatting
  app/src/main/java/com/nextcloud/talk/adapters/messages/IncomingLinkPreviewMessageViewHolder.kt
  app/src/main/java/com/nextcloud/talk/adapters/messages/IncomingLocationMessageViewHolder.kt
  app/src/main/java/com/nextcloud/talk/adapters/messages/IncomingPollMessageViewHolder.kt
  app/src/main/java/com/nextcloud/talk/adapters/messages/IncomingTextMessageViewHolder.kt
  app/src/main/java/com/nextcloud/talk/adapters/messages/IncomingVoiceMessageViewHolder.kt
  app/src/main/java/com/nextcloud/talk/adapters/messages/OutcomingLinkPreviewMessageViewHolder.kt
  app/src/main/java/com/nextcloud/talk/adapters/messages/OutcomingLocationMessageViewHolder.kt
  app/src/main/java/com/nextcloud/talk/adapters/messages/OutcomingPollMessageViewHolder.kt
  app/src/main/java/com/nextcloud/talk/adapters/messages/OutcomingTextMessageViewHolder.kt
  app/src/main/java/com/nextcloud/talk/adapters/messages/OutcomingVoiceMessageViewHolder.kt
  app/src/main/java/com/nextcloud/talk/adapters/messages/PreviewMessageViewHolder.kt
  app/src/main/java/com/nextcloud/talk/adapters/messages/SystemMessageViewHolder.java
  app/src/main/java/com/nextcloud/talk/controllers/ChatController.kt
  app/src/main/java/com/nextcloud/talk/controllers/ConversationInfoController.kt
  app/src/main/java/com/nextcloud/talk/dagger/modules/RepositoryModule.kt
  app/src/main/java/com/nextcloud/talk/dagger/modules/UtilsModule.kt
  app/src/main/java/com/nextcloud/talk/remotefilebrowser/activities/RemoteFileBrowserActivity.kt
  app/src/main/java/com/nextcloud/talk/remotefilebrowser/adapters/RemoteFileBrowserItemsAdapter.kt
  app/src/main/java/com/nextcloud/talk/remotefilebrowser/adapters/RemoteFileBrowserItemsListViewHolder.kt
  app/src/main/java/com/nextcloud/talk/shareditems/repositories/SharedItemsRepositoryImpl.kt
  app/src/main/java/com/nextcloud/talk/utils/DateUtils.kt
  scripts/analysis/findbugs-results.txt
  scripts/analysis/findbugs-up.rb
  spotbugs-filter.xml
Labels: enhancement, 3. to review, feature: 🗨️ chat

#2620 Bugfix/2181/fix conversation title
  app/src/main/java/com/nextcloud/talk/activities/MainActivity.kt
  app/src/main/java/com/nextcloud/talk/controllers/ChatController.kt
  app/src/main/java/com/nextcloud/talk/controllers/ContactsController.kt
  app/src/main/java/com/nextcloud/talk/controllers/ConversationsListController.kt
  app/src/main/java/com/nextcloud/talk/ui/bottom/sheet/ProfileBottomSheet.kt
  app/src/main/java/com/nextcloud/talk/utils/remapchat/ConductorRemapping.kt
  app/src/main/java/com/nextcloud/talk/utils/remapchat/RemapChatModel.kt
Labels: 3. to review, backport-request

#2581 Bugfix/2446/fix disappearing accounts
  app/src/main/java/com/nextcloud/talk/activities/CallActivity.java
  app/src/main/java/com/nextcloud/talk/controllers/AccountVerificationController.kt
  app/src/main/java/com/nextcloud/talk/controllers/ConversationsListController.kt
  app/src/main/java/com/nextcloud/talk/data/user/UsersDao.kt
  app/src/main/java/com/nextcloud/talk/data/user/UsersRepository.kt
  app/src/main/java/com/nextcloud/talk/data/user/UsersRepositoryImpl.kt
  app/src/main/java/com/nextcloud/talk/ui/dialog/ChooseAccountDialogFragment.java
  app/src/main/java/com/nextcloud/talk/users/UserManager.kt
  app/src/main/java/com/nextcloud/talk/utils/PushUtils.java
  app/src/main/java/com/nextcloud/talk/utils/database/user/CurrentUserProviderImpl.kt
  app/src/main/java/com/nextcloud/talk/utils/ssl/MagicKeyManager.java
Labels: 3. to review

#2634 Add hashes to github action versions
  .github/workflows/analysis.yml
  .github/workflows/assembleFlavors.yml
  .github/workflows/autoApproveDependabot.yml
  .github/workflows/check.yml
  .github/workflows/command-rebase.yml
  .github/workflows/fixup.yml
  .github/workflows/gradle-wrapper-validation.yml
  .github/workflows/qa.yml
  .github/workflows/stale.yml
Labels: 3. to review, technical debt

#2636 Bump version to 15.2
  app/build.gradle
Labels: 3. to review

#2635 Spotbugs: fix all bad practice warnings
  app/src/main/java/com/nextcloud/talk/adapters/items/GenericTextHeaderItem.java
  app/src/main/java/com/nextcloud/talk/adapters/items/MentionAutocompleteItem.java
  app/src/main/java/com/nextcloud/talk/utils/ssl/MagicTrustManager.java
Labels: 3. to review, technical debt

#2639 RepositoryModule: fix wrong injection for dateUtils
  app/src/main/java/com/nextcloud/talk/dagger/modules/RepositoryModule.kt
Labels: 3. to review, backport-request

#2648 avoid NPE in processAutocompleteUserList
  app/src/main/java/com/nextcloud/talk/controllers/ContactsController.kt
Labels: 3. to review, backport-request

#2586 Fix joining call when signaling messages overtake the response
  app/src/main/java/com/nextcloud/talk/activities/CallActivity.java
Labels: bug, 3. to review, feature: ☎️ call

#2646 Analysis: Also publish summary to GITHUB_STEP_SUMMARY
  scripts/analysis/analysis-wrapper.sh
Labels: 2. developing

#2651 Analysis branch
  scripts/analysis/analysis-wrapper.sh
Labels: 2. developing

#2536 Add listeners for signaling messages
  app/src/main/java/com/nextcloud/talk/activities/CallActivity.java
  app/src/main/java/com/nextcloud/talk/signaling/CallParticipantMessageNotifier.java
  app/src/main/java/com/nextcloud/talk/signaling/OfferMessageNotifier.java
  app/src/main/java/com/nextcloud/talk/signaling/ParticipantListMessageNotifier.java
  app/src/main/java/com/nextcloud/talk/signaling/SignalingMessageReceiver.java
  app/src/main/java/com/nextcloud/talk/signaling/WebRtcMessageNotifier.java
  app/src/main/java/com/nextcloud/talk/utils/MagicMap.kt
  app/src/main/java/com/nextcloud/talk/webrtc/Globals.java
  app/src/main/java/com/nextcloud/talk/webrtc/MagicWebSocketInstance.java
  app/src/main/java/com/nextcloud/talk/webrtc/PeerConnectionWrapper.java
  app/src/test/java/com/nextcloud/talk/signaling/SignalingMessageReceiverCallParticipantTest.java
  app/src/test/java/com/nextcloud/talk/signaling/SignalingMessageReceiverOfferTest.java
  app/src/test/java/com/nextcloud/talk/signaling/SignalingMessageReceiverParticipantListTest.java
  app/src/test/java/com/nextcloud/talk/signaling/SignalingMessageReceiverTest.java
  app/src/test/java/com/nextcloud/talk/signaling/SignalingMessageReceiverWebRtcTest.java
Labels: 3. to review, feature: ☎️ call

#2543 Add interface for sending signaling messages
  app/src/main/java/com/nextcloud/talk/activities/CallActivity.java
  app/src/main/java/com/nextcloud/talk/events/SessionDescriptionSendEvent.java
  app/src/main/java/com/nextcloud/talk/models/json/signaling/NCMessageWrapper.kt
  app/src/main/java/com/nextcloud/talk/models/json/signaling/Signaling.kt
  app/src/main/java/com/nextcloud/talk/models/json/websocket/RequestOfferOverallWebSocketMessage.kt
  app/src/main/java/com/nextcloud/talk/models/json/websocket/RequestOfferSignalingMessage.kt
  app/src/main/java/com/nextcloud/talk/models/json/websocket/SignalingDataWebSocketMessageForOffer.kt
  app/src/main/java/com/nextcloud/talk/signaling/SignalingMessageSender.java
  app/src/main/java/com/nextcloud/talk/webrtc/MagicWebSocketInstance.java
  app/src/main/java/com/nextcloud/talk/webrtc/PeerConnectionWrapper.java
  app/src/main/java/com/nextcloud/talk/webrtc/WebSocketConnectionHelper.java
  scripts/analysis/lint-results.txt
Labels: 3. to review, backport-request, feature: ☎️ call

#2545 Add listener for data channel messages
  app/src/main/java/com/nextcloud/talk/activities/CallActivity.java
  app/src/main/java/com/nextcloud/talk/adapters/ParticipantDisplayItem.java
  app/src/main/java/com/nextcloud/talk/events/PeerConnectionEvent.java
  app/src/main/java/com/nextcloud/talk/models/json/signaling/DataChannelMessage.kt
  app/src/main/java/com/nextcloud/talk/models/json/signaling/DataChannelMessageNick.kt
  app/src/main/java/com/nextcloud/talk/webrtc/DataChannelMessageNotifier.java
  app/src/main/java/com/nextcloud/talk/webrtc/MagicWebSocketInstance.java
  app/src/main/java/com/nextcloud/talk/webrtc/PeerConnectionWrapper.java
Labels: 3. to review, feature: ☎️ call

#2590 Add observer for peer connections
  app/src/main/java/com/nextcloud/talk/activities/CallActivity.java
  app/src/main/java/com/nextcloud/talk/events/MediaStreamEvent.java
  app/src/main/java/com/nextcloud/talk/events/PeerConnectionEvent.java
  app/src/main/java/com/nextcloud/talk/events/ProximitySensorEvent.java
  app/src/main/java/com/nextcloud/talk/webrtc/MagicWebSocketInstance.java
  app/src/main/java/com/nextcloud/talk/webrtc/PeerConnectionNotifier.java
  app/src/main/java/com/nextcloud/talk/webrtc/PeerConnectionWrapper.java
  app/src/main/java/com/nextcloud/talk/webrtc/WebRtcAudioManager.java
Labels: 3. to review, backport-request, feature: ☎️ call

#2656 Spotbugs improvements
  app/src/main/java/com/nextcloud/talk/activities/CallActivity.java
  app/src/main/java/com/nextcloud/talk/activities/CallBaseActivity.java
  app/src/main/java/com/nextcloud/talk/adapters/items/AdvancedUserItem.java
  app/src/main/java/com/nextcloud/talk/adapters/items/ContactItem.java
  app/src/main/java/com/nextcloud/talk/adapters/items/NotificationSoundItem.java
  app/src/main/java/com/nextcloud/talk/adapters/items/ParticipantItem.java
  app/src/main/java/com/nextcloud/talk/callbacks/MentionAutocompleteCallback.java
  app/src/main/java/com/nextcloud/talk/components/filebrowser/models/DavResponse.java
  app/src/main/java/com/nextcloud/talk/components/filebrowser/webdav/DavUtils.java
  app/src/main/java/com/nextcloud/talk/components/filebrowser/webdav/ReadFilesystemOperation.java
  app/src/main/java/com/nextcloud/talk/dagger/modules/RestModule.java
  app/src/main/java/com/nextcloud/talk/events/EventStatus.java
  app/src/main/java/com/nextcloud/talk/events/MoreMenuClickEvent.java
  app/src/main/java/com/nextcloud/talk/events/NetworkEvent.java
  app/src/main/java/com/nextcloud/talk/events/UserMentionClickEvent.java
  app/src/main/java/com/nextcloud/talk/events/WebSocketCommunicationEvent.java
  app/src/main/java/com/nextcloud/talk/models/ImportAccount.java
  app/src/main/java/com/nextcloud/talk/presenters/MentionAutocompletePresenter.java
  app/src/main/java/com/nextcloud/talk/ui/StatusDrawable.java
  app/src/main/java/com/nextcloud/talk/ui/dialog/SortingOrderDialogFragment.java
  app/src/main/java/com/nextcloud/talk/utils/AuthenticatorService.java
  app/src/main/java/com/nextcloud/talk/utils/DeviceUtils.java
  app/src/main/java/com/nextcloud/talk/utils/DisplayUtils.java
  app/src/main/java/com/nextcloud/talk/utils/MagicCharPolicy.java
  app/src/main/java/com/nextcloud/talk/utils/preferences/preferencestorage/DatabaseStorageModule.java
  app/src/main/java/com/nextcloud/talk/utils/text/Spans.java
  app/src/main/java/com/nextcloud/talk/webrtc/Globals.java
  app/src/main/java/com/nextcloud/talk/webrtc/MagicWebSocketInstance.java
  app/src/main/java/com/nextcloud/talk/webrtc/PeerConnectionWrapper.java
  app/src/main/java/com/nextcloud/talk/webrtc/WebRtcAudioManager.java
  app/src/main/java/com/nextcloud/talk/webrtc/WebRtcBluetoothManager.java
  app/src/main/java/com/nextcloud/talk/webrtc/WebSocketConnectionHelper.java
Labels: 3. to review, backport-request
