Repository nextcloud/talk-android, pull requests merged in 2022-09, with the labels that each got.

#2344 System message improvements and timestamps
  app/src/main/java/com/nextcloud/talk/adapters/messages/MagicSystemMessageViewHolder.java
  app/src/main/res/layout/item_custom_incoming_preview_message.xml
  app/src/main/res/layout/item_custom_incoming_text_message.xml
  app/src/main/res/layout/item_custom_outcoming_location_message.xml
  app/src/main/res/layout/item_custom_outcoming_preview_message.xml
  app/src/main/res/layout/item_custom_outcoming_text_message.xml
  app/src/main/res/layout/item_system_message.xml
Labels: bug, 3. to review

#2350 Restore executable permissions for getBranchName.sh
  scripts/analysis/getBranchName.sh
Labels: 3. to review

#2352 Add versions 14.1.1 and 14.2.0
  CHANGELOG.md
Labels: 3. to review

#2364 Improve chat bubble sizes
  app/src/main/java/com/nextcloud/talk/adapters/messages/Reaction.kt
  app/src/main/res/drawable/shape_incoming_message.xml
  app/src/main/res/drawable/shape_outcoming_message.xml
  app/src/main/res/layout/controller_chat.xml
  app/src/main/res/layout/item_custom_outcoming_location_message.xml
  app/src/main/res/layout/item_custom_outcoming_poll_message.xml
  app/src/main/res/layout/item_custom_outcoming_text_message.xml
  app/src/main/res/layout/item_custom_outcoming_voice_message.xml
  app/src/main/res/values/dimens.xml
Labels: design, 3. to review

#2387 Fix crash after hangup due to modifying a list while iterating over it
  app/src/main/java/com/nextcloud/talk/activities/CallActivity.java
Labels: bug, 3. to review, regression, backport-request, feature: ☎️ call

#2388 Fix issues when leaving calls
  app/src/main/java/com/nextcloud/talk/activities/CallActivity.java
Labels: bug, 3. to review, regression, backport-request, feature: ☎️ call

#2394 Fix call not joined again if reconnecting while in PiP mode
  app/src/main/java/com/nextcloud/talk/activities/CallActivity.java
Labels: bug, 3. to review, backport-request, feature: ☎️ call

#2389 Fix self video size after coming back from pip mode
  app/src/main/java/com/nextcloud/talk/activities/CallActivity.java
  app/src/main/res/layout/call_activity.xml
  app/src/main/res/values/dimens.xml
Labels: bug, 3. to review, backport-request, feature: ☎️ call

#2390 Provide visual feeback when a participant is not connected
  app/src/main/java/com/nextcloud/talk/activities/CallActivity.java
  app/src/main/java/com/nextcloud/talk/adapters/ParticipantDisplayItem.java
  app/src/main/java/com/nextcloud/talk/adapters/ParticipantsAdapter.java
  app/src/main/java/com/nextcloud/talk/events/PeerConnectionEvent.java
  app/src/main/java/com/nextcloud/talk/webrtc/PeerConnectionWrapper.java
  app/src/main/res/layout/call_activity.xml
  app/src/main/res/layout/call_item.xml
  app/src/main/res/values/dimens.xml
Labels: enhancement, 3. to review, backport-request, feature: ☎️ call

#2391 Fix checking lobby state from chat controller while in a call
  app/src/main/java/com/nextcloud/talk/controllers/ChatController.kt
Labels: bug, 3. to review, backport-request, feature: 🗨️ chat

#2392 Fix disposing local stream when the call activity is not being left
  app/src/main/java/com/nextcloud/talk/activities/CallActivity.java
Labels: bug, 3. to review, backport-request, feature: ☎️ call

#2393 Fix icon not visible in call state message
  app/src/main/res/layout/call_states.xml
Labels: bug, 3. to review, backport-request, feature: ☎️ call

#2395 Show message in call state when the publisher failed
  app/src/main/java/com/nextcloud/talk/activities/CallActivity.java
Labels: bug, 3. to review, backport-request, feature: ☎️ call

#2406 Determine base branch with 'jq'
  scripts/analysis/getBranchName.sh
Labels: 3. to review, backport-request

#2405 Theme toolbar for m3 for Text preview activity
  app/src/main/java/com/nextcloud/talk/activities/FullScreenTextViewerActivity.kt
  app/src/main/res/layout/activity_full_screen_text.xml
Labels: 3. to review, backport-request

#2414 hide poll creation for 1:1 conversations
  app/src/main/java/com/nextcloud/talk/controllers/ChatController.kt
  app/src/main/java/com/nextcloud/talk/ui/dialog/AttachmentDialog.kt
Labels: 3. to review, backport-request

#2413 add account switcher for "share to"
  app/src/main/java/com/nextcloud/talk/controllers/ConversationsListController.kt
  app/src/main/java/com/nextcloud/talk/ui/dialog/ChooseAccountDialogFragment.java
  app/src/main/java/com/nextcloud/talk/ui/dialog/ChooseAccountShareToDialogFragment.kt
  app/src/main/res/layout/dialog_choose_account_share_to.xml
  app/src/main/res/menu/menu_conversation_plus_filter.xml
  app/src/main/res/values/strings.xml
Labels: 3. to review, backport-request

#2411 Added monochrome icon for Android 13 "Themed icons" support.
  app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  app/src/qa/res/mipmap-anydpi-v26/ic_launcher.xml
Labels: 3. to review, backport-request

#2367 Respect participant permissions
  app/src/main/java/com/nextcloud/talk/activities/CallActivity.java
  app/src/main/java/com/nextcloud/talk/activities/CallNotificationActivity.java
  app/src/main/java/com/nextcloud/talk/controllers/ChatController.kt
  app/src/main/java/com/nextcloud/talk/controllers/ConversationsListController.kt
  app/src/main/java/com/nextcloud/talk/jobs/AddParticipantsToConversation.java
  app/src/main/java/com/nextcloud/talk/jobs/CapabilitiesWorker.java
  app/src/main/java/com/nextcloud/talk/jobs/DeleteConversationWorker.java
  app/src/main/java/com/nextcloud/talk/jobs/LeaveConversationWorker.java
  app/src/main/java/com/nextcloud/talk/jobs/NotificationWorker.java
  app/src/main/java/com/nextcloud/talk/jobs/SignalingSettingsWorker.java
  app/src/main/java/com/nextcloud/talk/models/json/conversations/Conversation.kt
  app/src/main/java/com/nextcloud/talk/utils/AttendeePermissionsUtil.kt
  app/src/main/java/com/nextcloud/talk/utils/ParticipantPermissions.kt
  app/src/main/java/com/nextcloud/talk/utils/bundle/BundleKeys.kt
  app/src/main/java/com/nextcloud/talk/webrtc/MagicWebSocketInstance.java
  app/src/main/res/values/strings.xml
  app/src/test/java/com/nextcloud/talk/utils/AttendeePermissionsUtilTest.kt
  app/src/test/java/com/nextcloud/talk/utils/ParticipantPermissionsTest.kt
Labels: 3. to review, backport-request

#2430 change poll buttons to vertical orientation
  app/src/main/res/layout/dialog_poll_results.xml
  app/src/main/res/layout/dialog_poll_vote.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/styles.xml
Labels: 3. to review, backport-request

#2433 Fix wrong guests access option status
  app/src/main/java/com/nextcloud/talk/conversation/info/GuestAccessHelper.kt
Labels: 3. to review, backport-request

#2437 fix to show reactionsEmojiWrapper
  app/src/main/java/com/nextcloud/talk/adapters/messages/Reaction.kt
Labels: 3. to review, backport-request

#2438 set participantPermissions in CallNotificationActivity
  app/src/main/java/com/nextcloud/talk/activities/CallNotificationActivity.java
Labels: 3. to review, backport-request

#2436 Feature/noid/improve polls buttons
  app/src/main/java/com/nextcloud/talk/polls/ui/PollVoteFragment.kt
  app/src/main/java/com/nextcloud/talk/polls/viewmodels/PollMainViewModel.kt
  app/src/main/res/layout/dialog_poll_results.xml
  app/src/main/res/layout/dialog_poll_vote.xml
Labels: 3. to review, backport-request

#2370 Set minSdkVersion to 23 (Android 6)
  app/build.gradle
  app/src/main/java/com/nextcloud/talk/adapters/items/ConversationItem.java
  app/src/main/java/com/nextcloud/talk/adapters/items/ConversationItem.kt
  app/src/main/java/com/nextcloud/talk/adapters/items/MessageResultItem.kt
  app/src/main/java/com/nextcloud/talk/controllers/ConversationsListController.kt
  app/src/main/java/com/nextcloud/talk/extensions/ImageViewExtensions.kt
  app/src/main/java/com/nextcloud/talk/utils/DisplayUtils.java
  app/src/main/java/com/nextcloud/talk/utils/NotificationUtils.kt
  app/src/main/res/layout/rv_item_conversation_with_last_message.xml
  app/src/main/res/layout/rv_item_search_message.xml
Labels: 2. developing

#2444 Get branch name from head instead of base
  scripts/analysis/getBranchName.sh
Labels: 3. to review

#2448 Revert "Set minSdkVersion to 23 (Android 6)"
  app/build.gradle
  app/src/main/java/com/nextcloud/talk/adapters/items/ConversationItem.java
  app/src/main/java/com/nextcloud/talk/adapters/items/ConversationItem.kt
  app/src/main/java/com/nextcloud/talk/adapters/items/MessageResultItem.kt
  app/src/main/java/com/nextcloud/talk/controllers/ConversationsListController.kt
  app/src/main/java/com/nextcloud/talk/extensions/ImageViewExtensions.kt
  app/src/main/java/com/nextcloud/talk/utils/DisplayUtils.java
  app/src/main/java/com/nextcloud/talk/utils/NotificationUtils.kt
  app/src/main/res/layout/rv_item_conversation_with_last_message.xml
  app/src/main/res/layout/rv_item_search_message.xml
  scripts/analysis/findbugs-results.txt
Labels: 3. to review
