Repository nextcloud/talk-android, pull requests merged in 2022-06, with the labels that each got.

#2119 Override emoji search field hint text to be translatable
  app/src/main/res/values/strings.xml
Labels: 3. to review

#2121 Bump androidxCameraVersion from 1.1.0-rc01 to 1.1.0-rc02
  app/build.gradle
Labels: technical debt, dependencies

#2127 Disable lint check 'PrivateResource'
  app/build.gradle
  app/src/main/res/values/strings.xml
Labels: 3. to review

#2128 Use unique request code to create PendingIntent
  app/src/main/java/com/nextcloud/talk/jobs/NotificationWorker.java
Labels: 3. to review

#2140 Centralize mime type definitions
  app/src/main/java/com/nextcloud/talk/activities/FullScreenImageActivity.kt
  app/src/main/java/com/nextcloud/talk/activities/FullScreenMediaActivity.kt
  app/src/main/java/com/nextcloud/talk/activities/FullScreenTextViewerActivity.kt
  app/src/main/java/com/nextcloud/talk/activities/TakePhotoActivity.java
  app/src/main/java/com/nextcloud/talk/components/filebrowser/models/BrowserFile.kt
  app/src/main/java/com/nextcloud/talk/components/filebrowser/webdav/ReadFolderListingOperation.kt
  app/src/main/java/com/nextcloud/talk/controllers/ConversationsListController.java
  app/src/main/java/com/nextcloud/talk/controllers/ProfileController.kt
  app/src/main/java/com/nextcloud/talk/remotefilebrowser/adapters/RemoteFileBrowserItemsListViewHolder.kt
  app/src/main/java/com/nextcloud/talk/remotefilebrowser/viewmodels/RemoteFileBrowserItemsViewModel.kt
  app/src/main/java/com/nextcloud/talk/ui/dialog/ConversationsListBottomDialog.kt
  app/src/main/java/com/nextcloud/talk/utils/DrawableUtils.kt
  app/src/main/java/com/nextcloud/talk/utils/FileViewerUtils.kt
  app/src/main/java/com/nextcloud/talk/utils/ImageEmojiEditText.kt
  app/src/main/java/com/nextcloud/talk/utils/LoggingUtils.kt
  app/src/main/java/com/nextcloud/talk/utils/Mimetype.kt
Labels: 3. to review

#2144 Updating command-rebase.yml workflow from template
  .github/workflows/command-rebase.yml
Labels: dependencies

#2142 fix to load conversation list (restricted user status)
  app/src/main/java/com/nextcloud/talk/controllers/ConversationsListController.java
  app/src/main/java/com/nextcloud/talk/ui/dialog/ChooseAccountDialogFragment.java
Labels: 3. to review

#2139 Android build dependend bluetooth permissions
  app/build.gradle
  app/src/gplay/AndroidManifest.xml
  app/src/gplay/java/com/nextcloud/talk/services/firebase/ChatAndCallMessagingService.kt
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/nextcloud/talk/activities/CallActivity.java
  app/src/main/java/com/nextcloud/talk/jobs/NotificationWorker.java
  app/src/main/java/com/nextcloud/talk/ui/dialog/AudioOutputDialog.kt
  app/src/main/java/com/nextcloud/talk/webrtc/WebRtcAudioManger.java
  app/src/main/java/com/nextcloud/talk/webrtc/WebRtcBluetoothManager.java
  scripts/analysis/lint-results.txt
Labels: 3. to review

#2160 Implement comments by PR #2139
  app/src/gplay/java/com/nextcloud/talk/services/firebase/ChatAndCallMessagingService.kt
  app/src/main/java/com/nextcloud/talk/activities/CallActivity.java
  app/src/main/java/com/nextcloud/talk/ui/dialog/AudioOutputDialog.kt
  app/src/main/java/com/nextcloud/talk/webrtc/WebRtcAudioManager.java
  app/src/main/java/com/nextcloud/talk/webrtc/WebRtcBluetoothManager.java
Labels: 3. to review, backport-request
