Repository nextcloud/talk-android, pull requests merged in 2022-04, with the labels that each got.

#1925 Catch NPE when UI is already teared down
  app/src/main/java/com/nextcloud/talk/ui/dialog/ChooseAccountDialogFragment.java
Labels: 3. to review

#1926 Move to a more hardened null-handling profile data handling
  app/src/main/java/com/nextcloud/talk/adapters/messages/OutcomingVoiceMessageViewHolder.kt
  app/src/main/java/com/nextcloud/talk/controllers/ProfileController.kt
Labels: 3. to review

#1932 13.0.0 Changelog
  CHANGELOG.md
Labels: 3. to review

#1936 fix text for reaction notification + hide content title for one2one rooms and reactions
  app/src/main/java/com/nextcloud/talk/jobs/NotificationWorker.java
Labels: 3. to review

#1934 Show own reactions
  app/src/main/java/com/nextcloud/talk/adapters/messages/IncomingLocationMessageViewHolder.kt
  app/src/main/java/com/nextcloud/talk/adapters/messages/IncomingVoiceMessageViewHolder.kt
  app/src/main/java/com/nextcloud/talk/adapters/messages/MagicIncomingTextMessageViewHolder.kt
  app/src/main/java/com/nextcloud/talk/adapters/messages/MagicPreviewMessageViewHolder.java
  app/src/main/java/com/nextcloud/talk/adapters/messages/OutcomingLocationMessageViewHolder.kt
  app/src/main/java/com/nextcloud/talk/adapters/messages/OutcomingVoiceMessageViewHolder.kt
  app/src/main/java/com/nextcloud/talk/adapters/messages/Reaction.kt
  app/src/main/java/com/nextcloud/talk/controllers/ChatController.kt
  app/src/main/java/com/nextcloud/talk/models/json/chat/ChatMessage.java
  app/src/main/java/com/nextcloud/talk/ui/dialog/MessageActionsDialog.kt
  app/src/main/java/com/nextcloud/talk/ui/dialog/ShowReactionsDialog.kt
  app/src/main/res/drawable/reaction_self_background.xml
  app/src/main/res/drawable/reaction_self_bottom_sheet_background.xml
  app/src/main/res/layout/dialog_attachment.xml
  app/src/main/res/layout/dialog_audio_output.xml
  app/src/main/res/layout/dialog_choose_account.xml
  app/src/main/res/layout/dialog_conversation_operations.xml
  app/src/main/res/layout/dialog_message_actions.xml
  app/src/main/res/layout/dialog_scope.xml
  app/src/main/res/layout/reaction_item.xml
  app/src/main/res/values-night/colors.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/dimens.xml
Labels: enhancement, 3. to review, feature: 🗨️ chat

#1940 Fix trying to establish a connection before a participant joins the call
  app/src/main/java/com/nextcloud/talk/activities/CallActivity.java
Labels: bug, 3. to review, feature: ☎️ call

#1942 add workaround to avoid emoji picker to take the full screen height
  app/src/main/java/com/nextcloud/talk/ui/dialog/MessageActionsDialog.kt
Labels: 3. to review

#1943 Fix npe if message has no self reactions initially
  app/src/main/java/com/nextcloud/talk/ui/dialog/MessageActionsDialog.kt
Labels: 3. to review

#1941 Fix call flags in video calls
  app/src/main/java/com/nextcloud/talk/activities/CallActivity.java
Labels: bug, 3. to review, feature: ☎️ call

#1947 Updating command-rebase.yml workflow from template
  .github/workflows/command-rebase.yml
Labels: dependencies

#1946 media overview
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/nextcloud/talk/activities/MainActivity.kt
  app/src/main/java/com/nextcloud/talk/activities/SharedItemsActivity.kt
  app/src/main/java/com/nextcloud/talk/adapters/SharedItemsGridAdapter.kt
  app/src/main/java/com/nextcloud/talk/adapters/SharedItemsListAdapter.kt
  app/src/main/java/com/nextcloud/talk/adapters/messages/MagicPreviewMessageViewHolder.java
  app/src/main/java/com/nextcloud/talk/api/NcApi.java
  app/src/main/java/com/nextcloud/talk/controllers/ChatController.kt
  app/src/main/java/com/nextcloud/talk/controllers/ConversationInfoController.kt
  app/src/main/java/com/nextcloud/talk/models/json/chat/ChatMessage.java
  app/src/main/java/com/nextcloud/talk/models/json/chat/ChatShareOCS.java
  app/src/main/java/com/nextcloud/talk/models/json/chat/ChatShareOverall.java
  app/src/main/java/com/nextcloud/talk/models/json/chat/ChatShareOverviewOCS.java
  app/src/main/java/com/nextcloud/talk/models/json/chat/ChatShareOverviewOverall.java
  app/src/main/java/com/nextcloud/talk/repositories/SharedItem.kt
  app/src/main/java/com/nextcloud/talk/repositories/SharedItemType.kt
  app/src/main/java/com/nextcloud/talk/repositories/SharedItemsRepository.kt
  app/src/main/java/com/nextcloud/talk/repositories/SharedMediaItems.kt
  app/src/main/java/com/nextcloud/talk/utils/ApiUtils.java
  app/src/main/java/com/nextcloud/talk/utils/FileViewerUtils.kt
  app/src/main/java/com/nextcloud/talk/viewmodels/SharedItemsViewModel.kt
  app/src/main/res/drawable/ic_folder_multiple_image.xml
  app/src/main/res/layout/activity_shared_items.xml
  app/src/main/res/layout/controller_conversation_info.xml
  app/src/main/res/layout/rv_item_browser_file.xml
  app/src/main/res/layout/shared_item_grid.xml
  app/src/main/res/layout/shared_item_list.xml
  app/src/main/res/menu/menu_conversation.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
  scripts/analysis/lint-results.txt
Labels: 2. developing, feature: 🤝 sharing, feature: 📄 conversations
