Repository nextcloud/talk-android, pull requests merged in 2022-01, with the labels that each got.

#1749 Image keyboard support in chat
  app/src/main/java/com/nextcloud/talk/controllers/ChatController.kt
  app/src/main/java/com/nextcloud/talk/utils/ImageEmojiEditText.kt
  app/src/main/res/layout/view_message_input.xml
Labels: enhancement, 3. to review, feature: 🗨️ chat

#1751 Additional fixes related to notification channels
  app/src/main/java/com/nextcloud/talk/controllers/RingtoneSelectionController.java
  app/src/main/java/com/nextcloud/talk/controllers/SettingsController.java
  app/src/main/java/com/nextcloud/talk/jobs/NotificationWorker.java
  app/src/main/java/com/nextcloud/talk/receivers/PackageReplacedReceiver.kt
  app/src/main/java/com/nextcloud/talk/utils/NotificationUtils.kt
Labels: bug, 3. to review, feature: 🔔 notifications

#1767 only show mark as unread in debug mode
  app/src/main/java/com/nextcloud/talk/controllers/ChatController.kt
Labels: 3. to review

#1780 Bump android-gif-drawable from 1.2.23 to 1.2.24
  app/build.gradle
Labels: 3. to review, technical debt, backport-request

#1776 Feature/1740/recover from deleted push token
  app/build.gradle
  app/src/generic/java/com/nextcloud/talk/utils/ClosedInterfaceImpl.java
  app/src/gplay/java/com/nextcloud/talk/jobs/GetFirebasePushTokenWorker.kt
  app/src/gplay/java/com/nextcloud/talk/services/firebase/MagicFirebaseMessagingService.kt
  app/src/gplay/java/com/nextcloud/talk/utils/ClosedInterfaceImpl.java
  app/src/gplay/java/com/nextcloud/talk/utils/ClosedInterfaceImpl.kt
  app/src/main/java/com/nextcloud/talk/api/NcApi.java
  app/src/main/java/com/nextcloud/talk/application/NextcloudTalkApplication.kt
  app/src/main/java/com/nextcloud/talk/controllers/AccountVerificationController.java
  app/src/main/java/com/nextcloud/talk/controllers/ConversationsListController.java
  app/src/main/java/com/nextcloud/talk/controllers/WebViewLoginController.java
  app/src/main/java/com/nextcloud/talk/interfaces/ClosedInterface.kt
  app/src/main/java/com/nextcloud/talk/jobs/PushRegistrationWorker.java
  app/src/main/java/com/nextcloud/talk/utils/PushUtils.java
  app/src/main/res/values/setup.xml
  app/src/qa/java/com/nextcloud/talk/utils/ClosedInterfaceImpl.java
  scripts/analysis/findbugs-results.txt
  scripts/analysis/lint-results.txt
Labels: 3. to review
