Repository nextcloud/talk-android, pull requests merged in 2023-02, with the labels that each got.

#2721 Show raised hands by remote participants
  app/src/main/java/com/nextcloud/talk/activities/CallActivity.java
  app/src/main/java/com/nextcloud/talk/adapters/ParticipantDisplayItem.java
  app/src/main/java/com/nextcloud/talk/adapters/ParticipantsAdapter.java
  app/src/main/java/com/nextcloud/talk/call/CallParticipant.java
  app/src/main/java/com/nextcloud/talk/call/CallParticipantModel.java
  app/src/main/java/com/nextcloud/talk/call/MutableCallParticipantModel.java
  app/src/main/java/com/nextcloud/talk/call/RaisedHand.kt
  app/src/main/java/com/nextcloud/talk/models/json/signaling/NCMessagePayload.kt
  app/src/main/java/com/nextcloud/talk/signaling/CallParticipantMessageNotifier.java
  app/src/main/java/com/nextcloud/talk/signaling/SignalingMessageReceiver.java
  app/src/main/res/drawable/ic_hand_back_left.xml
  app/src/main/res/layout/call_item.xml
  app/src/main/res/values/strings.xml
  app/src/test/java/com/nextcloud/talk/call/CallParticipantModelTest.kt
  app/src/test/java/com/nextcloud/talk/signaling/SignalingMessageReceiverCallParticipantTest.java
Labels: 2. developing, backport-request, feature: ☎️ call

#2725 Added A scroll down button + new icon + some styles for the button
  app/src/main/java/com/nextcloud/talk/controllers/ChatController.kt
  app/src/main/res/drawable/ic_baseline_keyboard_double_arrow_down_24.xml
  app/src/main/res/layout/controller_chat.xml
  app/src/main/res/values-night/colors.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: enhancement, 3. to review

#2742 Activate mark-as-unread on message level for everyone
  app/src/main/java/com/nextcloud/talk/ui/dialog/MessageActionsDialog.kt
Labels: 3. to review, feature: 🗨️ chat

#2743 Add ability to mark a room as unread
  app/src/main/java/com/nextcloud/talk/api/NcApi.java
  app/src/main/java/com/nextcloud/talk/controllers/ChatController.kt
  app/src/main/java/com/nextcloud/talk/controllers/bottomsheet/ConversationOperationEnum.kt
  app/src/main/java/com/nextcloud/talk/controllers/bottomsheet/OperationsMenuController.kt
  app/src/main/java/com/nextcloud/talk/receivers/MarkAsReadReceiver.kt
  app/src/main/java/com/nextcloud/talk/ui/dialog/ConversationsListBottomDialog.kt
  app/src/main/java/com/nextcloud/talk/utils/ApiUtils.java
  app/src/main/java/com/nextcloud/talk/utils/database/user/CapabilitiesUtilNew.kt
  app/src/main/res/layout/dialog_conversation_operations.xml
Labels: 3. to review, feature: 📄 conversations

#2741 Optimize scroll-to-bottom
  app/src/main/java/com/nextcloud/talk/controllers/ChatController.kt
  app/src/main/res/drawable/ic_keyboard_double_arrow_down.xml
  app/src/main/res/layout/controller_chat.xml
  app/src/main/res/values-night/colors.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/styles.xml
Labels: design, 3. to review

#2745 Bugfix/noid/fix exceptions
  app/src/main/java/com/nextcloud/talk/activities/CallActivity.java
  app/src/main/java/com/nextcloud/talk/controllers/ChatController.kt
  app/src/main/java/com/nextcloud/talk/controllers/ConversationInfoController.kt
  app/src/main/java/com/nextcloud/talk/controllers/LockedController.kt
  app/src/main/java/com/nextcloud/talk/webrtc/PeerConnectionWrapper.java
Labels: backport-request

#2750 Update GH actions to latest master versions
  .github/workflows/analysis.yml
  .github/workflows/assembleFlavors.yml
  .github/workflows/autoApproveSync.yml
  .github/workflows/check.yml
  .github/workflows/codeql.yml
  .github/workflows/command-rebase.yml
  .github/workflows/gradle-wrapper-validation.yml
  .github/workflows/qa.yml
  .github/workflows/scorecards.yml
  .github/workflows/stale.yml
Labels: technical debt

#2754 hide scroll-to-bottom upon click
  app/src/main/java/com/nextcloud/talk/controllers/ChatController.kt
Labels: 3. to review

#2752 Fix to show thumbnails in FileBrowser
  app/src/main/java/com/nextcloud/talk/extensions/ImageViewExtensions.kt
  app/src/main/java/com/nextcloud/talk/remotefilebrowser/activities/RemoteFileBrowserActivity.kt
  app/src/main/java/com/nextcloud/talk/remotefilebrowser/adapters/RemoteFileBrowserItemsListViewHolder.kt
  scripts/analysis/lint-results.txt
Labels: backport-request

#2759 Bugfix/1756/fix active account after switch by notification
  app/src/main/java/com/nextcloud/talk/activities/CallNotificationActivity.kt
  app/src/main/java/com/nextcloud/talk/activities/MainActivity.kt
Labels: backport-request

#2761 Fix to show back button when message opened by notification
  app/src/main/java/com/nextcloud/talk/controllers/base/BaseController.kt
Labels: backport-request

#2764 Delete scorecards.yml
  .github/workflows/scorecards.yml
Labels: 3. to review

#2766 add support for FORMER_ONE_TO_ONE conversations
  app/src/main/java/com/nextcloud/talk/adapters/items/ConversationItem.kt
  app/src/main/java/com/nextcloud/talk/adapters/messages/IncomingLinkPreviewMessageViewHolder.kt
  app/src/main/java/com/nextcloud/talk/adapters/messages/IncomingLocationMessageViewHolder.kt
  app/src/main/java/com/nextcloud/talk/adapters/messages/IncomingPollMessageViewHolder.kt
  app/src/main/java/com/nextcloud/talk/adapters/messages/IncomingTextMessageViewHolder.kt
  app/src/main/java/com/nextcloud/talk/adapters/messages/IncomingVoiceMessageViewHolder.kt
  app/src/main/java/com/nextcloud/talk/controllers/ChatController.kt
  app/src/main/java/com/nextcloud/talk/models/json/chat/ChatMessage.kt
  app/src/main/java/com/nextcloud/talk/models/json/conversations/Conversation.kt
  app/src/main/java/com/nextcloud/talk/models/json/converters/EnumRoomTypeConverter.java
Labels: 3. to review

#2776 Reformat code
  app/src/main/java/com/nextcloud/talk/activities/BaseActivity.kt
  app/src/main/java/com/nextcloud/talk/activities/CallNotificationActivity.kt
  app/src/main/java/com/nextcloud/talk/activities/MainActivity.kt
  app/src/main/java/com/nextcloud/talk/adapters/items/ConversationItem.kt
  app/src/main/java/com/nextcloud/talk/adapters/messages/IncomingTextMessageViewHolder.kt
  app/src/main/java/com/nextcloud/talk/adapters/messages/OutcomingLinkPreviewMessageViewHolder.kt
  app/src/main/java/com/nextcloud/talk/adapters/messages/OutcomingLocationMessageViewHolder.kt
  app/src/main/java/com/nextcloud/talk/adapters/messages/OutcomingPollMessageViewHolder.kt
  app/src/main/java/com/nextcloud/talk/adapters/messages/OutcomingTextMessageViewHolder.kt
  app/src/main/java/com/nextcloud/talk/adapters/messages/OutcomingVoiceMessageViewHolder.kt
  app/src/main/java/com/nextcloud/talk/adapters/messages/PreviewMessageViewHolder.kt
  app/src/main/java/com/nextcloud/talk/adapters/messages/Reaction.kt
  app/src/main/java/com/nextcloud/talk/application/NextcloudTalkApplication.kt
  app/src/main/java/com/nextcloud/talk/controllers/ChatController.kt
  app/src/main/java/com/nextcloud/talk/controllers/ContactsController.kt
  app/src/main/java/com/nextcloud/talk/controllers/ConversationInfoController.kt
  app/src/main/java/com/nextcloud/talk/controllers/ConversationsListController.kt
  app/src/main/java/com/nextcloud/talk/controllers/LocationPickerController.kt
  app/src/main/java/com/nextcloud/talk/controllers/LockedController.kt
  app/src/main/java/com/nextcloud/talk/controllers/ServerSelectionController.kt
  app/src/main/java/com/nextcloud/talk/controllers/WebViewLoginController.kt
  app/src/main/java/com/nextcloud/talk/controllers/bottomsheet/OperationsMenuController.kt
  app/src/main/java/com/nextcloud/talk/controllers/bottomsheet/items/MagicBottomSheets.kt
  app/src/main/java/com/nextcloud/talk/conversation/info/GuestAccessHelper.kt
  app/src/main/java/com/nextcloud/talk/data/source/local/TalkDatabase.kt
  app/src/main/java/com/nextcloud/talk/data/storage/model/ArbitraryStorageEntity.kt
  app/src/main/java/com/nextcloud/talk/jobs/NotificationWorker.kt
  app/src/main/java/com/nextcloud/talk/models/json/chat/ChatMessage.kt
  app/src/main/java/com/nextcloud/talk/polls/repositories/PollRepositoryImpl.kt
  app/src/main/java/com/nextcloud/talk/shareditems/adapters/SharedItemsViewHolder.kt
  app/src/main/java/com/nextcloud/talk/shareditems/repositories/SharedItemsRepositoryImpl.kt
  app/src/main/java/com/nextcloud/talk/ui/recyclerview/MessageSwipeCallback.kt
  app/src/main/java/com/nextcloud/talk/utils/ShareUtils.kt
Labels: 2. developing

#2777 bump android common to 0.6.0
  app/build.gradle
Labels: 3. to review, dependencies

#2771 avoid NPE for voice message playback
  app/src/main/java/com/nextcloud/talk/controllers/ChatController.kt
Labels: backport-request

#2715 add handling for breakout rooms
  app/src/main/java/com/nextcloud/talk/activities/CallActivity.java
  app/src/main/java/com/nextcloud/talk/activities/MainActivity.kt
  app/src/main/java/com/nextcloud/talk/api/NcApi.java
  app/src/main/java/com/nextcloud/talk/controllers/ChatController.kt
  app/src/main/java/com/nextcloud/talk/dagger/modules/RepositoryModule.kt
  app/src/main/java/com/nextcloud/talk/dagger/modules/ViewModelModule.kt
  app/src/main/java/com/nextcloud/talk/models/json/chat/ChatMessage.kt
  app/src/main/java/com/nextcloud/talk/models/json/converters/EnumSystemMessageTypeConverter.kt
  app/src/main/java/com/nextcloud/talk/raisehand/RequestAssistanceModel.kt
  app/src/main/java/com/nextcloud/talk/raisehand/RequestAssistanceRepository.kt
  app/src/main/java/com/nextcloud/talk/raisehand/RequestAssistanceRepositoryImpl.kt
  app/src/main/java/com/nextcloud/talk/raisehand/WithdrawRequestAssistanceModel.kt
  app/src/main/java/com/nextcloud/talk/raisehand/viewmodel/RaiseHandViewModel.kt
  app/src/main/java/com/nextcloud/talk/signaling/LocalParticipantMessageNotifier.java
  app/src/main/java/com/nextcloud/talk/signaling/SignalingMessageReceiver.java
  app/src/main/java/com/nextcloud/talk/ui/dialog/MoreCallActionsDialog.kt
  app/src/main/java/com/nextcloud/talk/utils/ApiUtils.java
  app/src/main/java/com/nextcloud/talk/utils/bundle/BundleKeys.kt
  app/src/main/java/com/nextcloud/talk/webrtc/PeerConnectionWrapper.java
  app/src/main/java/com/nextcloud/talk/webrtc/WebSocketInstance.kt
  app/src/main/res/drawable/ic_baseline_do_not_touch_24.xml
  app/src/main/res/layout/call_activity.xml
  app/src/main/res/layout/call_item.xml
  app/src/main/res/layout/dialog_more_call_actions.xml
  app/src/main/res/values/strings.xml
  app/src/test/java/com/nextcloud/talk/signaling/SignalingMessageReceiverLocalParticipantTest.java
Labels: 3. to review

#2796 Update material icons to latest revisions
  app/src/main/res/drawable/ic_account_plus.xml
  app/src/main/res/drawable/ic_edit.xml
  app/src/main/res/drawable/ic_settings.xml
Labels: design, 3. to review

#2795 Feature/2722/add recording file notification
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/nextcloud/talk/api/NcApi.java
  app/src/main/java/com/nextcloud/talk/jobs/NotificationWorker.kt
  app/src/main/java/com/nextcloud/talk/receivers/DismissRecordingAvailableReceiver.kt
  app/src/main/java/com/nextcloud/talk/receivers/ShareRecordingToChatReceiver.kt
  app/src/main/java/com/nextcloud/talk/utils/ApiUtils.java
  app/src/main/java/com/nextcloud/talk/utils/NotificationUtils.kt
  app/src/main/java/com/nextcloud/talk/utils/VibrationUtils.kt
  app/src/main/java/com/nextcloud/talk/utils/bundle/BundleKeys.kt
Labels: 3. to review

#2800 Bugfix/noid/avoid npe for unread bubble
  app/src/main/java/com/nextcloud/talk/controllers/ChatController.kt
Labels: backport-request

#2802 Implemented automatic scrolling to quoted messages on tap
  app/src/main/java/com/nextcloud/talk/adapters/messages/IncomingTextMessageViewHolder.kt
  app/src/main/java/com/nextcloud/talk/controllers/ChatController.kt
Labels: 3. to review, backport-request
