Repository nextcloud/talk-android, pull requests merged in 2023-05, with the labels that each got.

#2988 Bump main to 17.0.0 Alpha
  app/build.gradle
Labels: 3. to review

#2995 Handle received signaling messages for call reactions
  app/src/main/java/com/nextcloud/talk/activities/CallActivity.java
  app/src/main/java/com/nextcloud/talk/adapters/ParticipantDisplayItem.java
  app/src/main/java/com/nextcloud/talk/call/CallParticipant.java
  app/src/main/java/com/nextcloud/talk/call/CallParticipantModel.java
  app/src/main/java/com/nextcloud/talk/call/CallParticipantModelNotifier.java
  app/src/main/java/com/nextcloud/talk/call/MutableCallParticipantModel.java
  app/src/main/java/com/nextcloud/talk/models/json/signaling/NCMessagePayload.kt
  app/src/main/java/com/nextcloud/talk/signaling/CallParticipantMessageNotifier.java
  app/src/main/java/com/nextcloud/talk/signaling/SignalingMessageReceiver.java
  app/src/test/java/com/nextcloud/talk/call/CallParticipantModelTest.kt
  app/src/test/java/com/nextcloud/talk/signaling/SignalingMessageReceiverCallParticipantTest.java
Labels: 3. to review, feature: ☎️ call

#2997 hide delete button if no custom avatar is set
  app/src/main/java/com/nextcloud/talk/adapters/items/ConversationItem.kt
  app/src/main/java/com/nextcloud/talk/conversationinfo/ConversationInfoActivity.kt
  app/src/main/java/com/nextcloud/talk/conversationinfoedit/ConversationInfoEditActivity.kt
  app/src/main/java/com/nextcloud/talk/extensions/ImageViewExtensions.kt
  app/src/main/java/com/nextcloud/talk/models/json/conversations/Conversation.kt
  app/src/main/java/com/nextcloud/talk/utils/ApiUtils.java
  app/src/main/res/drawable/ic_avatar_link.xml
Labels: 3. to review

#2984 Reactions in calls
  app/src/main/java/com/nextcloud/talk/activities/CallActivity.java
  app/src/main/java/com/nextcloud/talk/call/ReactionAnimator.kt
  app/src/main/java/com/nextcloud/talk/ui/dialog/MoreCallActionsDialog.kt
  app/src/main/java/com/nextcloud/talk/utils/database/user/CapabilitiesUtilNew.kt
  app/src/main/java/com/nextcloud/talk/webrtc/PeerConnectionWrapper.java
  app/src/main/res/layout/call_activity.xml
  app/src/main/res/layout/dialog_more_call_actions.xml
Labels: 3. to review

#3011 Build(deps): Bump com.fasterxml.jackson.core:jackson-core to 2.14.3
  app/build.gradle
Labels: 3. to review

#3025 🔣 Translate chat message
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/nextcloud/talk/api/NcApi.java
  app/src/main/java/com/nextcloud/talk/chat/ChatActivity.kt
  app/src/main/java/com/nextcloud/talk/models/json/translations/TranslateData.kt
  app/src/main/java/com/nextcloud/talk/models/json/translations/TranslateOCS.kt
  app/src/main/java/com/nextcloud/talk/models/json/translations/TranslationsOverall.kt
  app/src/main/java/com/nextcloud/talk/translate/TranslateActivity.kt
  app/src/main/java/com/nextcloud/talk/ui/dialog/MessageActionsDialog.kt
  app/src/main/java/com/nextcloud/talk/ui/theme/TalkSpecificViewThemeUtils.kt
  app/src/main/java/com/nextcloud/talk/utils/ApiUtils.java
  app/src/main/java/com/nextcloud/talk/utils/bundle/BundleKeys.kt
  app/src/main/java/com/nextcloud/talk/utils/database/user/CapabilitiesUtilNew.kt
  app/src/main/res/drawable-night/ic_chevron_right.xml
  app/src/main/res/drawable/ic_baseline_translate_24.xml
  app/src/main/res/drawable/ic_chevron_right.xml
  app/src/main/res/layout-land/activity_translate.xml
  app/src/main/res/layout/activity_translate.xml
  app/src/main/res/layout/dialog_message_actions.xml
  app/src/main/res/values/strings.xml
Labels: enhancement, 3. to review, feature: 🗨️ chat

#3030 issue 2931 - follow up fixes
  app/src/main/java/com/nextcloud/talk/translate/TranslateActivity.kt
  app/src/main/java/com/nextcloud/talk/utils/bundle/BundleKeys.kt
Labels: bug, 3. to review, backport-request

#3033 Add copy to clipboard action for translations
  app/src/main/java/com/nextcloud/talk/translate/TranslateActivity.kt
  app/src/main/res/layout-land/activity_translate.xml
  app/src/main/res/layout/activity_translate.xml
  app/src/main/res/values/strings.xml
Labels: enhancement, 3. to review, backport-request, feature: 🗨️ chat

#3029 ✍️ Typing indicators
  app/src/main/java/com/nextcloud/talk/api/NcApi.java
  app/src/main/java/com/nextcloud/talk/chat/ChatActivity.kt
  app/src/main/java/com/nextcloud/talk/settings/SettingsActivity.kt
  app/src/main/java/com/nextcloud/talk/signaling/ConversationMessageNotifier.kt
  app/src/main/java/com/nextcloud/talk/signaling/SignalingMessageReceiver.java
  app/src/main/java/com/nextcloud/talk/utils/DisplayUtils.java
  app/src/main/java/com/nextcloud/talk/utils/database/user/CapabilitiesUtilNew.kt
  app/src/main/java/com/nextcloud/talk/utils/preferences/AppPreferences.java
  app/src/main/java/com/nextcloud/talk/webrtc/WebSocketInstance.kt
  app/src/main/res/layout/activity_chat.xml
  app/src/main/res/layout/activity_settings.xml
  app/src/main/res/values/strings.xml
Labels: 3. to review, backport-request

#3038 rewriting translate feature to use MVVM
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/nextcloud/talk/api/NcApi.java
  app/src/main/java/com/nextcloud/talk/chat/ChatActivity.kt
  app/src/main/java/com/nextcloud/talk/dagger/modules/RepositoryModule.kt
  app/src/main/java/com/nextcloud/talk/dagger/modules/ViewModelModule.kt
  app/src/main/java/com/nextcloud/talk/translate/repositories/TranslateRepository.kt
  app/src/main/java/com/nextcloud/talk/translate/repositories/TranslateRepositoryImpl.kt
  app/src/main/java/com/nextcloud/talk/translate/repositories/model/TranslateData.kt
  app/src/main/java/com/nextcloud/talk/translate/repositories/model/TranslateOCS.kt
  app/src/main/java/com/nextcloud/talk/translate/repositories/model/TranslationsOverall.kt
  app/src/main/java/com/nextcloud/talk/translate/ui/TranslateActivity.kt
  app/src/main/java/com/nextcloud/talk/translate/viewmodels/TranslateViewModel.kt
Labels: 3. to review, backport-request

#3041 Migrate theme API calls
  app/src/main/java/com/nextcloud/talk/activities/FullScreenTextViewerActivity.kt
  app/src/main/java/com/nextcloud/talk/adapters/items/ConversationItem.kt
  app/src/main/java/com/nextcloud/talk/adapters/messages/IncomingLinkPreviewMessageViewHolder.kt
  app/src/main/java/com/nextcloud/talk/adapters/messages/IncomingLocationMessageViewHolder.kt
  app/src/main/java/com/nextcloud/talk/adapters/messages/IncomingPollMessageViewHolder.kt
  app/src/main/java/com/nextcloud/talk/adapters/messages/IncomingTextMessageViewHolder.kt
  app/src/main/java/com/nextcloud/talk/adapters/messages/IncomingVoiceMessageViewHolder.kt
  app/src/main/java/com/nextcloud/talk/adapters/messages/OutcomingVoiceMessageViewHolder.kt
  app/src/main/java/com/nextcloud/talk/adapters/messages/PreviewMessageViewHolder.kt
  app/src/main/java/com/nextcloud/talk/call/ReactionAnimator.kt
  app/src/main/java/com/nextcloud/talk/chat/ChatActivity.kt
  app/src/main/java/com/nextcloud/talk/contacts/ContactsActivity.kt
  app/src/main/java/com/nextcloud/talk/controllers/bottomsheet/EntryMenuController.kt
  app/src/main/java/com/nextcloud/talk/controllers/bottomsheet/OperationsMenuController.kt
  app/src/main/java/com/nextcloud/talk/conversationinfo/ConversationInfoActivity.kt
  app/src/main/java/com/nextcloud/talk/conversationinfoedit/ConversationInfoEditActivity.kt
  app/src/main/java/com/nextcloud/talk/conversationlist/ConversationsListActivity.kt
  app/src/main/java/com/nextcloud/talk/jobs/NotificationWorker.kt
  app/src/main/java/com/nextcloud/talk/location/GeocodingActivity.kt
  app/src/main/java/com/nextcloud/talk/location/LocationPickerActivity.kt
  app/src/main/java/com/nextcloud/talk/polls/ui/PollCreateDialogFragment.kt
  app/src/main/java/com/nextcloud/talk/polls/ui/PollLoadingFragment.kt
  app/src/main/java/com/nextcloud/talk/profile/ProfileActivity.kt
  app/src/main/java/com/nextcloud/talk/remotefilebrowser/activities/RemoteFileBrowserActivity.kt
  app/src/main/java/com/nextcloud/talk/settings/SettingsActivity.kt
  app/src/main/java/com/nextcloud/talk/shareditems/activities/SharedItemsActivity.kt
  app/src/main/java/com/nextcloud/talk/translate/ui/TranslateActivity.kt
  app/src/main/java/com/nextcloud/talk/ui/dialog/AudioOutputDialog.kt
  app/src/main/java/com/nextcloud/talk/ui/dialog/ChooseAccountShareToDialogFragment.kt
  app/src/main/java/com/nextcloud/talk/ui/dialog/SetStatusDialogFragment.kt
  app/src/main/java/com/nextcloud/talk/ui/theme/TalkSpecificViewThemeUtils.kt
Labels: 3. to review, technical debt

#3046 Changed reply length to have a max of 250 characters
  app/src/main/java/com/nextcloud/talk/adapters/messages/IncomingTextMessageViewHolder.kt
  app/src/main/java/com/nextcloud/talk/adapters/messages/OutcomingTextMessageViewHolder.kt
  app/src/main/res/layout/item_message_quote.xml
Labels: 3. to review, backport-request

#3036 Replace deprecated onBackPressed
  app/build.gradle
  app/src/main/java/com/nextcloud/talk/activities/CallBaseActivity.java
  app/src/main/java/com/nextcloud/talk/activities/FullScreenImageActivity.kt
  app/src/main/java/com/nextcloud/talk/activities/FullScreenMediaActivity.kt
  app/src/main/java/com/nextcloud/talk/activities/FullScreenTextViewerActivity.kt
  app/src/main/java/com/nextcloud/talk/activities/MainActivity.kt
  app/src/main/java/com/nextcloud/talk/activities/TakePhotoActivity.java
  app/src/main/java/com/nextcloud/talk/chat/ChatActivity.kt
  app/src/main/java/com/nextcloud/talk/contacts/ContactsActivity.kt
  app/src/main/java/com/nextcloud/talk/conversationinfo/ConversationInfoActivity.kt
  app/src/main/java/com/nextcloud/talk/conversationinfoedit/ConversationInfoEditActivity.kt
  app/src/main/java/com/nextcloud/talk/conversationlist/ConversationsListActivity.kt
  app/src/main/java/com/nextcloud/talk/location/GeocodingActivity.kt
  app/src/main/java/com/nextcloud/talk/location/LocationPickerActivity.kt
  app/src/main/java/com/nextcloud/talk/messagesearch/MessageSearchActivity.kt
  app/src/main/java/com/nextcloud/talk/profile/ProfileActivity.kt
  app/src/main/java/com/nextcloud/talk/remotefilebrowser/activities/RemoteFileBrowserActivity.kt
  app/src/main/java/com/nextcloud/talk/settings/SettingsActivity.kt
  app/src/main/java/com/nextcloud/talk/shareditems/activities/SharedItemsActivity.kt
  app/src/main/java/com/nextcloud/talk/translate/ui/TranslateActivity.kt
Labels: 3. to review

#3057 Shows an empty subline when the last message expires instead of "No messages yet"
  app/src/main/java/com/nextcloud/talk/adapters/items/ConversationItem.kt
  app/src/main/res/values/strings.xml
Labels: 3. to review
