Repository nextcloud/talk-android, pull requests merged in 2023-09, with the labels that each got.

#3284 Implemented media/photo share functionality
  app/src/main/java/com/nextcloud/talk/adapters/messages/PreviewMessageViewHolder.kt
  app/src/main/java/com/nextcloud/talk/chat/ChatActivity.kt
  app/src/main/java/com/nextcloud/talk/models/json/chat/ChatMessage.kt
  app/src/main/java/com/nextcloud/talk/shareditems/adapters/SharedItemsViewHolder.kt
  app/src/main/java/com/nextcloud/talk/ui/dialog/MessageActionsDialog.kt
  app/src/main/java/com/nextcloud/talk/utils/FileViewerUtils.kt
  app/src/main/res/layout/dialog_message_actions.xml
Labels: enhancement, 3. to review, feature: 🗨️ chat, feature: 🤝 sharing

#3296 group system messages followup
  app/src/main/res/drawable/baseline_unfold_less_24.xml
  app/src/main/res/drawable/baseline_unfold_more_24.xml
Labels: backport-request

#3298 detect when user is talking and send data channel message
  app/src/main/java/com/nextcloud/talk/activities/CallActivity.kt
  app/src/main/java/com/nextcloud/talk/shareditems/adapters/SharedItemsViewHolder.kt
  app/src/main/java/com/nextcloud/talk/utils/FileViewerUtils.kt
  app/src/main/res/layout/item_system_message.xml
  scripts/analysis/lint-results.txt
Labels: 3. to review, backport-request

#3320 Add unit test execution
  .github/workflows/unit-tests.yml
Labels: 3. to review, technical debt

#3321 Fixed bug with continuous voice recording
  app/src/main/java/com/nextcloud/talk/chat/ChatActivity.kt
Labels: bug, 3. to review

#3332 TimePicker format matches locale of device
  app/src/main/java/com/nextcloud/talk/ui/dialog/DateTimePickerFragment.kt
Labels: bug, 3. to review, feature: 🔔 notifications

#3329 Open internal file share links in chat via files client
  app/src/androidTest/java/com/nextcloud/talk/utils/UriUtilsIT.kt
  app/src/main/java/com/nextcloud/talk/adapters/messages/IncomingLocationMessageViewHolder.kt
  app/src/main/java/com/nextcloud/talk/adapters/messages/OutcomingLocationMessageViewHolder.kt
  app/src/main/java/com/nextcloud/talk/chat/ChatActivity.kt
  app/src/main/java/com/nextcloud/talk/controllers/AccountVerificationController.kt
  app/src/main/java/com/nextcloud/talk/controllers/ServerSelectionController.kt
  app/src/main/java/com/nextcloud/talk/controllers/bottomsheet/EntryMenuController.kt
  app/src/main/java/com/nextcloud/talk/utils/AccountUtils.kt
  app/src/main/java/com/nextcloud/talk/utils/UriUtils.kt
  app/src/test/java/com/nextcloud/talk/utils/UriUtilsTest.kt
  detekt.yml
Labels: enhancement, 3. to review, feature: 🗨️ chat, feature: 🧩 integration

#3333 Save filter state
  app/schemas/com.nextcloud.talk.data.source.local.TalkDatabase/9.json
  app/src/main/java/com/nextcloud/talk/arbitrarystorage/ArbitraryStorageManager.kt
  app/src/main/java/com/nextcloud/talk/conversationlist/ConversationsListActivity.kt
  app/src/main/java/com/nextcloud/talk/data/source/local/Migrations.kt
  app/src/main/java/com/nextcloud/talk/data/source/local/TalkDatabase.kt
  app/src/main/java/com/nextcloud/talk/data/storage/ArbitraryStoragesDao.kt
  app/src/main/java/com/nextcloud/talk/data/storage/ArbitraryStoragesRepository.kt
  app/src/main/java/com/nextcloud/talk/data/storage/ArbitraryStoragesRepositoryImpl.kt
  app/src/main/java/com/nextcloud/talk/data/storage/model/ArbitraryStorage.kt
  app/src/main/java/com/nextcloud/talk/data/storage/model/ArbitraryStorageEntity.kt
  app/src/main/java/com/nextcloud/talk/ui/dialog/FilterConversationFragment.kt
  app/src/main/res/layout/item_guest_access_settings.xml
  scripts/analysis/lint-results.txt
Labels: 3. to review, feature: ⚙️ settings, feature: 📄 conversations

#3322 Replaced ListView with RecyclerView
  app/src/main/java/com/nextcloud/talk/adapters/GeocodingAdapter.kt
  app/src/main/java/com/nextcloud/talk/location/GeocodingActivity.kt
  app/src/main/res/layout/activity_geocoding.xml
  app/src/main/res/layout/geocoding_item.xml
  scripts/analysis/lint-results.txt
Labels: 3. to review, technical debt

#3346 fix endless loop when opening urls and files app is not installed.
  app/src/main/java/com/nextcloud/talk/chat/ChatActivity.kt
Labels: 3. to review
