Repository nextcloud/talk-android, pull requests merged in 2023-10, with the labels that each got.

#3319 FIxed deletion of voice, video, image, contact and location messages
  app/src/main/java/com/nextcloud/talk/adapters/messages/PreviewMessageViewHolder.kt
  app/src/main/java/com/nextcloud/talk/chat/ChatActivity.kt
  app/src/main/res/menu/chat_preview_message_menu.xml
Labels: 3. to review

#3307 Show accept call button in chat
  app/src/main/java/com/nextcloud/talk/adapters/messages/CallStartedMessageInterface.kt
  app/src/main/java/com/nextcloud/talk/adapters/messages/CallStartedViewHolder.kt
  app/src/main/java/com/nextcloud/talk/adapters/messages/TalkMessagesListAdapter.java
  app/src/main/java/com/nextcloud/talk/chat/ChatActivity.kt
  app/src/main/res/layout/call_started_message.xml
  app/src/main/res/values/strings.xml
Labels: enhancement, 3. to review, feature: 🗨️ chat, feature: ☎️ call

#3349 use MVVM for Geocoding
  app/src/main/java/com/nextcloud/talk/adapters/GeocodingAdapter.kt
  app/src/main/java/com/nextcloud/talk/location/GeocodingActivity.kt
  app/src/main/java/com/nextcloud/talk/viewmodels/GeoCodingViewModel.kt
Labels: 3. to review, technical debt

#3354 Use primary color for quoted, own messages
  app/src/main/java/com/nextcloud/talk/adapters/messages/IncomingLinkPreviewMessageViewHolder.kt
  app/src/main/java/com/nextcloud/talk/adapters/messages/IncomingLocationMessageViewHolder.kt
  app/src/main/java/com/nextcloud/talk/adapters/messages/IncomingPollMessageViewHolder.kt
  app/src/main/java/com/nextcloud/talk/adapters/messages/IncomingTextMessageViewHolder.kt
  app/src/main/java/com/nextcloud/talk/adapters/messages/IncomingVoiceMessageViewHolder.kt
Labels: bug, 3. to review, backport-request

#3357 Bug fix for accept call message
  app/src/main/java/com/nextcloud/talk/adapters/messages/CallStartedViewHolder.kt
  app/src/main/res/layout/call_started_message.xml
Labels: bug, 3. to review

#3356 Fixes newline characters not creating new lines
  app/src/main/java/com/nextcloud/talk/utils/message/MessageUtils.kt
Labels: bug, 3. to review

#3364 Small Bug fix - Privacy button in settings not working
  app/src/main/java/com/nextcloud/talk/settings/SettingsActivity.kt
Labels: bug, 3. to review, backport-request

#3313 Remove EntryMenuController and OperationMenuController
  app/src/main/java/com/nextcloud/talk/contacts/ContactsActivity.kt
  app/src/main/java/com/nextcloud/talk/controllers/bottomsheet/ConversationOperationEnum.kt
  app/src/main/java/com/nextcloud/talk/controllers/bottomsheet/EntryMenuController.kt
  app/src/main/java/com/nextcloud/talk/controllers/bottomsheet/OperationsMenuController.kt
  app/src/main/java/com/nextcloud/talk/conversation/CreateConversationDialogFragment.kt
  app/src/main/java/com/nextcloud/talk/conversation/RenameConversationDialogFragment.kt
  app/src/main/java/com/nextcloud/talk/conversation/repository/ConversationRepository.kt
  app/src/main/java/com/nextcloud/talk/conversation/repository/ConversationRepositoryImpl.kt
  app/src/main/java/com/nextcloud/talk/conversation/viewmodel/ConversationViewModel.kt
  app/src/main/java/com/nextcloud/talk/conversation/viewmodel/RenameConversationViewModel.kt
  app/src/main/java/com/nextcloud/talk/conversationlist/ConversationsListActivity.kt
  app/src/main/java/com/nextcloud/talk/dagger/modules/RepositoryModule.kt
  app/src/main/java/com/nextcloud/talk/dagger/modules/ViewModelModule.kt
  app/src/main/java/com/nextcloud/talk/jobs/AddParticipantsToConversation.java
  app/src/main/java/com/nextcloud/talk/ui/dialog/ContactsBottomDialog.kt
  app/src/main/java/com/nextcloud/talk/ui/dialog/ConversationsListBottomDialog.kt
  app/src/main/java/com/nextcloud/talk/utils/remapchat/RemapChatModel.kt
  app/src/main/res/drawable/ic_check_circle_black_24dp.xml
  app/src/main/res/drawable/ic_public_black_24px.xml
  app/src/main/res/layout/activity_contacts.xml
  app/src/main/res/layout/activity_conversation_info.xml
  app/src/main/res/layout/controller_operations_menu.xml
  app/src/main/res/layout/dialog_bottom_contacts.xml
  app/src/main/res/layout/dialog_conversation_operations.xml
  app/src/main/res/layout/dialog_create_conversation.xml
  app/src/main/res/layout/dialog_rename_conversation.xml
  app/src/main/res/values-night/colors.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  scripts/analysis/lint-results.txt
Labels: 3. to review, technical debt

#3378 fix emoji size in markdown headlines
  app/build.gradle
  app/src/main/java/com/nextcloud/talk/ui/MicInputCloud.kt
  app/src/main/java/com/nextcloud/talk/ui/WaveformSeekBar.kt
Labels: 3. to review, backport-request

#3379 fix emoji size in markdown headlines
  app/build.gradle
  app/src/main/java/com/nextcloud/talk/ui/MicInputCloud.kt
  app/src/main/java/com/nextcloud/talk/ui/WaveformSeekBar.kt
Labels: 3. to review

#3380 Fixes not able to execute audio messages
  app/src/main/java/com/nextcloud/talk/chat/ChatActivity.kt
  app/src/main/java/com/nextcloud/talk/utils/AudioUtils.kt
Labels: bug, 3. to review, backport-request

#3396 Bump room to 2.6.0
  app/build.gradle
  app/src/main/java/com/nextcloud/talk/data/source/local/Migrations.kt
Labels: 3. to review, technical debt, dependencies

#3398 Add changelog infos for 17.1.0 and 17.1.2
  CHANGELOG.md
Labels: 3. to review

#3397 Revert Android Auto support
  app/src/main/AndroidManifest.xml
  app/src/main/res/xml/automotive_app_desc.xml
Labels: 3. to review

#3351 Note To Self ✏️
  app/src/main/java/com/nextcloud/talk/adapters/items/ConversationItem.kt
  app/src/main/java/com/nextcloud/talk/chat/ChatActivity.kt
  app/src/main/java/com/nextcloud/talk/conversationinfo/ConversationInfoActivity.kt
  app/src/main/java/com/nextcloud/talk/extensions/ImageViewExtensions.kt
  app/src/main/java/com/nextcloud/talk/models/json/conversations/Conversation.kt
  app/src/main/java/com/nextcloud/talk/utils/ConversationUtils.kt
  app/src/main/res/drawable/ic_note_to_self.xml
Labels: enhancement, 3. to review, feature: 📄 conversations

#3249 Migrating away from StoreBox to DataStore
  app/build.gradle
  app/src/main/java/com/nextcloud/talk/dagger/modules/DatabaseModule.java
  app/src/main/java/com/nextcloud/talk/remotefilebrowser/viewmodels/RemoteFileBrowserItemsViewModel.kt
  app/src/main/java/com/nextcloud/talk/settings/SettingsActivity.kt
  app/src/main/java/com/nextcloud/talk/utils/preferences/AppPreferences.java
  app/src/main/java/com/nextcloud/talk/utils/preferences/AppPreferencesImpl.kt
  app/src/main/res/values/strings.xml
Labels: 3. to review, technical debt

#3414 Rename message expiration title
  app/src/main/res/layout/activity_conversation_info.xml
  app/src/main/res/values/strings.xml
Labels: 3. to review

#3413 Feature/3289/recording consent
  app/src/main/java/com/nextcloud/talk/activities/CallActivity.kt
  app/src/main/java/com/nextcloud/talk/api/NcApi.java
  app/src/main/java/com/nextcloud/talk/conversationinfo/ConversationInfoActivity.kt
  app/src/main/java/com/nextcloud/talk/models/json/conversations/Conversation.kt
  app/src/main/java/com/nextcloud/talk/utils/ApiUtils.java
  app/src/main/java/com/nextcloud/talk/utils/database/user/CapabilitiesUtilNew.kt
  app/src/main/res/layout/activity_conversation_info.xml
  app/src/main/res/layout/item_recording_consent.xml
  app/src/main/res/values/strings.xml
Labels: 3. to review
