Repository nextcloud/talk-android, pull requests merged in 2023-06, with the labels that each got.

#3064 File util fixes
  app/src/main/java/com/nextcloud/talk/jobs/UploadAndShareFilesWorker.kt
  app/src/main/java/com/nextcloud/talk/utils/FileUtils.kt
Labels: 3. to review

#3065 chore: update workflows from templates
  .github/workflows/fixup.yml
Labels: 3. to review, dependencies, automated

#3067 Migrate output variables to new GH output variables
  .github/workflows/analysis.yml
Labels: 2. developing, technical debt

#3068 Fix code style for variable declaration
  app/src/main/java/com/nextcloud/talk/activities/CallActivity.java
  app/src/main/java/com/nextcloud/talk/adapters/ParticipantDisplayItem.java
  app/src/main/java/com/nextcloud/talk/call/CallParticipantList.java
  app/src/main/java/com/nextcloud/talk/call/CallParticipantModel.java
  app/src/main/java/com/nextcloud/talk/webrtc/PeerConnectionWrapper.java
  app/src/test/java/com/nextcloud/talk/call/CallParticipantListExternalSignalingTest.java
  app/src/test/java/com/nextcloud/talk/call/CallParticipantListInternalSignalingTest.java
Labels: 3. to review, technical debt

#3069 Further code style improvements
  app/src/androidTest/java/com/nextcloud/talk/ui/LoginIT.java
  app/src/main/java/com/nextcloud/talk/adapters/ParticipantDisplayItemNotifier.java
  app/src/main/java/com/nextcloud/talk/call/CallParticipantModelNotifier.java
  app/src/main/java/com/nextcloud/talk/signaling/CallParticipantMessageNotifier.java
  app/src/main/java/com/nextcloud/talk/signaling/WebRtcMessageNotifier.java
  app/src/main/java/com/nextcloud/talk/utils/DisplayUtils.java
  app/src/test/java/com/nextcloud/talk/call/CallParticipantListExternalSignalingTest.java
  app/src/test/java/com/nextcloud/talk/call/CallParticipantListInternalSignalingTest.java
Labels: 3. to review, technical debt

#3075 Align typing indicator to new concept
  app/src/main/java/com/nextcloud/talk/chat/ChatActivity.kt
  app/src/main/java/com/nextcloud/talk/chat/TypingParticipant.kt
  app/src/main/java/com/nextcloud/talk/settings/SettingsActivity.kt
  app/src/main/java/com/nextcloud/talk/signaling/ConversationMessageNotifier.kt
  app/src/main/java/com/nextcloud/talk/signaling/SignalingMessageReceiver.java
  app/src/main/java/com/nextcloud/talk/webrtc/WebSocketInstance.kt
  app/src/main/res/layout/activity_settings.xml
  app/src/main/res/values/strings.xml
Labels: 3. to review, backport-request

#3078 fix to avoid linebreak in strings.xml
  app/src/main/res/values/strings.xml
Labels: backport-request

#3098 Filter Conversations List for Unread/Mention
  app/build.gradle
  app/src/main/java/com/nextcloud/talk/conversationlist/ConversationsListActivity.kt
  app/src/main/java/com/nextcloud/talk/ui/dialog/FilterConversationFragment.kt
  app/src/main/res/drawable/ic_baseline_filter_list_24.xml
  app/src/main/res/layout/controller_conversations_rv.xml
  app/src/main/res/layout/dialog_filter_conversation.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  scripts/analysis/lint-results.txt
Labels: 3. to review

#3104 Fix to show other errors than HttpException (e.g. ConnectException)
  app/src/main/java/com/nextcloud/talk/conversationlist/ConversationsListActivity.kt
Labels: 3. to review

#3102 Feature/3070/list open conversations
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/nextcloud/talk/contacts/ContactsActivity.kt
  app/src/main/java/com/nextcloud/talk/dagger/modules/RepositoryModule.kt
  app/src/main/java/com/nextcloud/talk/dagger/modules/ViewModelModule.kt
  app/src/main/java/com/nextcloud/talk/openconversations/ListOpenConversationsActivity.kt
  app/src/main/java/com/nextcloud/talk/openconversations/adapters/OpenConversationsAdapter.kt
  app/src/main/java/com/nextcloud/talk/openconversations/data/JoinConversationModel.kt
  app/src/main/java/com/nextcloud/talk/openconversations/data/OpenConversation.kt
  app/src/main/java/com/nextcloud/talk/openconversations/data/OpenConversationsModel.kt
  app/src/main/java/com/nextcloud/talk/openconversations/data/OpenConversationsRepository.kt
  app/src/main/java/com/nextcloud/talk/openconversations/data/OpenConversationsRepositoryImpl.kt
  app/src/main/java/com/nextcloud/talk/openconversations/viewmodels/OpenConversationsViewModel.kt
  app/src/main/res/drawable/baseline_format_list_bulleted_24.xml
  app/src/main/res/drawable/baseline_info_24.xml
  app/src/main/res/layout/activity_contacts.xml
  app/src/main/res/layout/activity_open_conversations.xml
  app/src/main/res/layout/controller_contacts_rv.xml
  app/src/main/res/layout/conversation_privacy_toggle.xml
  app/src/main/res/layout/rv_item_open_conversation.xml
  app/src/main/res/values-night/colors.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: 3. to review

#3110 Bug fix to filter conversations
  app/src/main/java/com/nextcloud/talk/conversationlist/ConversationsListActivity.kt
Labels: bug, 3. to review

#3119 Authors Name is now above incoming previewed messages
  app/src/main/java/com/nextcloud/talk/adapters/messages/IncomingPreviewMessageViewHolder.java
  app/src/main/res/layout/item_custom_incoming_preview_message.xml
Labels: bug, 3. to review

#3112 WIP one-to-one behaves like mentioned
  app/src/main/java/com/nextcloud/talk/ui/dialog/FilterConversationFragment.kt
Labels: bug, 3. to review
