Repository nextcloud/talk-android, pull requests merged in 2023-08, with the labels that each got.

#3226 Build(deps): Bump com.google.firebase:firebase-messaging to 23.2.0
  app/build.gradle
Labels: technical debt

#3227 Migrate to newer gradle sdk setting
  app/build.gradle
Labels: technical debt

#3224 Message drafts are now saved
  app/src/main/java/com/nextcloud/talk/chat/ChatActivity.kt
  app/src/main/res/values/strings.xml
Labels: enhancement, 3. to review

#3234 Follow up fixes for the Waveform SeekBar
  app/src/main/java/com/nextcloud/talk/chat/ChatActivity.kt
  app/src/main/java/com/nextcloud/talk/ui/WaveformSeekBar.kt
  app/src/main/java/com/nextcloud/talk/utils/AudioUtils.kt
  app/src/main/res/layout/item_custom_incoming_voice_message.xml
  app/src/main/res/layout/item_custom_outcoming_voice_message.xml
Labels: bug, 3. to review

#3239 Update pr-feedback.yml
  .github/workflows/pr-feedback.yml
Labels: technical debt

#3235 Migration away from getScheme() calls
  app/src/main/java/com/nextcloud/talk/activities/CallActivity.kt
  app/src/main/java/com/nextcloud/talk/adapters/items/AdvancedUserItem.java
  app/src/main/java/com/nextcloud/talk/adapters/items/ContactItem.java
  app/src/main/java/com/nextcloud/talk/adapters/items/MentionAutocompleteItem.java
  app/src/main/java/com/nextcloud/talk/adapters/items/ParticipantItem.java
  app/src/main/java/com/nextcloud/talk/adapters/messages/IncomingLinkPreviewMessageViewHolder.kt
  app/src/main/java/com/nextcloud/talk/adapters/messages/IncomingLocationMessageViewHolder.kt
  app/src/main/java/com/nextcloud/talk/adapters/messages/IncomingPollMessageViewHolder.kt
  app/src/main/java/com/nextcloud/talk/adapters/messages/IncomingTextMessageViewHolder.kt
  app/src/main/java/com/nextcloud/talk/adapters/messages/IncomingVoiceMessageViewHolder.kt
  app/src/main/java/com/nextcloud/talk/adapters/messages/OutcomingLinkPreviewMessageViewHolder.kt
  app/src/main/java/com/nextcloud/talk/adapters/messages/OutcomingLocationMessageViewHolder.kt
  app/src/main/java/com/nextcloud/talk/adapters/messages/OutcomingPollMessageViewHolder.kt
  app/src/main/java/com/nextcloud/talk/adapters/messages/OutcomingTextMessageViewHolder.kt
  app/src/main/java/com/nextcloud/talk/adapters/messages/OutcomingVoiceMessageViewHolder.kt
  app/src/main/java/com/nextcloud/talk/adapters/messages/PreviewMessageViewHolder.kt
  app/src/main/java/com/nextcloud/talk/adapters/messages/Reaction.kt
  app/src/main/java/com/nextcloud/talk/chat/ChatActivity.kt
  app/src/main/java/com/nextcloud/talk/remotefilebrowser/activities/RemoteFileBrowserActivity.kt
  app/src/main/java/com/nextcloud/talk/ui/StatusDrawable.java
  app/src/main/java/com/nextcloud/talk/ui/dialog/ChooseAccountDialogFragment.java
  app/src/main/java/com/nextcloud/talk/ui/theme/TalkSpecificViewThemeUtils.kt
  app/src/main/java/com/nextcloud/talk/utils/DisplayUtils.java
  app/src/main/java/com/nextcloud/talk/utils/message/MessageUtils.kt
Labels: 3. to review, technical debt

#3246 Fix theming issues
  app/src/main/java/com/nextcloud/talk/ui/theme/TalkSpecificViewThemeUtils.kt
  app/src/main/java/com/nextcloud/talk/utils/message/MessageUtils.kt
Labels: bug, feature: 🗨️ chat, feature: 🌗 theming

#3254 migrate to media3
  app/build.gradle
  app/src/main/java/com/nextcloud/talk/activities/FullScreenMediaActivity.kt
  app/src/main/res/layout/activity_full_screen_media.xml
Labels: 3. to review, technical debt

#3268 avoid file storage permission warning.
  app/src/main/java/com/nextcloud/talk/activities/CallActivity.kt
  app/src/main/java/com/nextcloud/talk/chat/ChatActivity.kt
  app/src/main/java/com/nextcloud/talk/conversationinfo/ConversationInfoActivity.kt
  app/src/main/java/com/nextcloud/talk/conversationinfo/GuestAccessHelper.kt
  app/src/main/java/com/nextcloud/talk/conversationlist/ConversationsListActivity.kt
  app/src/main/java/com/nextcloud/talk/jobs/NotificationWorker.kt
Labels: 3. to review

#3271 Fixed media recorder bug
  app/src/main/java/com/nextcloud/talk/chat/ChatActivity.kt
Labels: bug, 3. to review

#3282 Message draft bug fix
  app/src/main/java/com/nextcloud/talk/chat/ChatActivity.kt
Labels: bug, 3. to review

#3256 Notify Me Later About a Message
  app/src/main/java/com/nextcloud/talk/api/NcApi.java
  app/src/main/java/com/nextcloud/talk/chat/ChatActivity.kt
  app/src/main/java/com/nextcloud/talk/chat/data/ChatRepository.kt
  app/src/main/java/com/nextcloud/talk/chat/data/ChatRepositoryImpl.kt
  app/src/main/java/com/nextcloud/talk/chat/viewmodels/ChatViewModel.kt
  app/src/main/java/com/nextcloud/talk/jobs/NotificationWorker.kt
  app/src/main/java/com/nextcloud/talk/models/json/reminder/Reminder.kt
  app/src/main/java/com/nextcloud/talk/models/json/reminder/ReminderOCS.kt
  app/src/main/java/com/nextcloud/talk/models/json/reminder/ReminderOverall.kt
  app/src/main/java/com/nextcloud/talk/ui/dialog/DateTimePickerFragment.kt
  app/src/main/java/com/nextcloud/talk/ui/dialog/MessageActionsDialog.kt
  app/src/main/java/com/nextcloud/talk/utils/ApiUtils.java
  app/src/main/java/com/nextcloud/talk/utils/database/user/CapabilitiesUtilNew.kt
  app/src/main/res/drawable/baseline_calendar_month_24.xml
  app/src/main/res/layout/dialog_date_time_picker.xml
  app/src/main/res/layout/dialog_message_actions.xml
  app/src/main/res/values/strings.xml
Labels: enhancement, medium, 3. to review, feature: 🗨️ chat, feature: 🔔 notifications

#3293 Feature/3073/group system messages from calls
  app/src/main/java/com/nextcloud/talk/adapters/messages/SystemMessageInterface.kt
  app/src/main/java/com/nextcloud/talk/adapters/messages/SystemMessageViewHolder.java
  app/src/main/java/com/nextcloud/talk/adapters/messages/SystemMessageViewHolder.kt
  app/src/main/java/com/nextcloud/talk/adapters/messages/TalkMessagesListAdapter.java
  app/src/main/java/com/nextcloud/talk/chat/ChatActivity.kt
  app/src/main/java/com/nextcloud/talk/models/json/chat/ChatMessage.kt
  app/src/main/res/drawable/baseline_unfold_less_24.xml
  app/src/main/res/drawable/baseline_unfold_more_24.xml
  app/src/main/res/layout/item_system_message.xml
  app/src/main/res/values/strings.xml
Labels: enhancement, 3. to review
