Repository nextcloud/talk-android, pull requests merged in 2023-12, with the labels that each got.

#3485 Add fixes and changes to push handling
  app/src/generic/java/com/nextcloud/talk/utils/ClosedInterfaceImpl.java
  app/src/gplay/java/com/nextcloud/talk/jobs/GetFirebasePushTokenWorker.kt
  app/src/gplay/java/com/nextcloud/talk/services/firebase/NCFirebaseMessagingService.kt
  app/src/gplay/java/com/nextcloud/talk/utils/ClosedInterfaceImpl.kt
  app/src/main/java/com/nextcloud/talk/account/AccountVerificationActivity.kt
  app/src/main/java/com/nextcloud/talk/activities/MainActivity.kt
  app/src/main/java/com/nextcloud/talk/api/NcApi.java
  app/src/main/java/com/nextcloud/talk/conversationlist/ConversationsListActivity.kt
  app/src/main/java/com/nextcloud/talk/jobs/PushRegistrationWorker.java
  app/src/main/java/com/nextcloud/talk/utils/PushUtils.java
  app/src/main/java/com/nextcloud/talk/utils/PushUtils.kt
  scripts/analysis/lint-results.txt
Labels: 3. to review, backport-request

#3502 avoid error when declining recording consent
  app/src/main/java/com/nextcloud/talk/activities/CallActivity.kt
Labels: 3. to review, backport-request

#3514 Update build files to latest DSL
  app/build.gradle
  build.gradle
Labels: 2. developing, technical debt

#3513 update changelog
  CHANGELOG.md
Labels: 3. to review

#3512 Material3: Add drag handle
  app/src/main/java/com/nextcloud/talk/chat/ChatActivity.kt
  app/src/main/java/com/nextcloud/talk/ui/bottom/sheet/ProfileBottomSheet.kt
  app/src/main/res/layout/dialog_conversation_operations.xml
  app/src/main/res/layout/dialog_message_actions.xml
  app/src/main/res/layout/dialog_message_reactions.xml
  app/src/main/res/layout/dialog_more_call_actions.xml
  app/src/main/res/layout/dialog_scope.xml
  scripts/analysis/lint-results.txt
Labels: 3. to review

#3510 Bump hwsecurity-fido from 2.4.5 to 4.1.0-patch2
  app/build.gradle
  app/src/main/java/com/nextcloud/talk/account/WebViewLoginActivity.kt
Labels: 3. to review, technical debt, dependencies

#3537 Add drag handle to remaining bottom sheets
  app/src/main/res/layout/dialog_attachment.xml
  app/src/main/res/layout/dialog_audio_output.xml
  app/src/main/res/layout/dialog_conversation_operations.xml
  app/src/main/res/layout/dialog_message_actions.xml
  app/src/main/res/layout/dialog_message_reactions.xml
  app/src/main/res/layout/dialog_scope.xml
Labels: design, technical debt

#3515 AudioUtils bug fix for media playback
  app/src/main/java/com/nextcloud/talk/utils/AudioUtils.kt
Labels: bug, 3. to review, backport-request
