Repository nextcloud/talk-android, pull requests merged in 2023-04, with the labels that each got.

#2920 Bump ChatKit to 0.4.2
  app/build.gradle
Labels: 3. to review

#2922 Fix ci and new lint issues
  app/src/androidTest/java/com/nextcloud/talk/ui/LoginIT.java
  app/src/main/res/layout-land/activity_profile.xml
  app/src/main/res/layout/controller_conversation_info.xml
Labels: 3. to review

#2925 fix(i18n): Adjust links to transifex
  CONTRIBUTING.md
  README.md
  app/src/main/res/values/strings.xml
Labels: 3. to review

#2927 Fix to scroll to first unread message
  app/src/main/java/com/nextcloud/talk/chat/ChatActivity.kt
Labels: 3. to review

#2932 Replace Controller with Activity for ConversationList
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/nextcloud/talk/activities/BaseActivity.kt
  app/src/main/java/com/nextcloud/talk/activities/MainActivity.kt
  app/src/main/java/com/nextcloud/talk/chat/ChatActivity.kt
  app/src/main/java/com/nextcloud/talk/contacts/ContactsActivity.kt
  app/src/main/java/com/nextcloud/talk/controllers/AccountVerificationController.kt
  app/src/main/java/com/nextcloud/talk/controllers/base/BaseController.kt
  app/src/main/java/com/nextcloud/talk/conversation/info/ConversationInfoActivity.kt
  app/src/main/java/com/nextcloud/talk/conversationlist/ConversationsListActivity.kt
  app/src/main/java/com/nextcloud/talk/location/GeocodingActivity.kt
  app/src/main/java/com/nextcloud/talk/location/LocationPickerActivity.kt
  app/src/main/java/com/nextcloud/talk/messagesearch/MessageSearchActivity.kt
  app/src/main/java/com/nextcloud/talk/profile/ProfileActivity.kt
  app/src/main/java/com/nextcloud/talk/settings/SettingsActivity.kt
  app/src/main/java/com/nextcloud/talk/ui/dialog/ChooseAccountDialogFragment.java
  app/src/main/java/com/nextcloud/talk/ui/dialog/ConversationsListBottomDialog.kt
  app/src/main/java/com/nextcloud/talk/utils/bundle/BundleKeys.kt
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/controller_conversations_rv.xml
  app/src/main/res/menu/menu_contacts.xml
  app/src/main/res/values/styles.xml
Labels: 3. to review

#2951 Group mentions
  app/src/main/java/com/nextcloud/talk/adapters/items/MentionAutocompleteItem.java
  app/src/main/java/com/nextcloud/talk/adapters/messages/IncomingTextMessageViewHolder.kt
  app/src/main/java/com/nextcloud/talk/adapters/messages/OutcomingTextMessageViewHolder.kt
  app/src/main/java/com/nextcloud/talk/chat/ChatActivity.kt
  app/src/main/java/com/nextcloud/talk/utils/DisplayUtils.java
Labels: enhancement, 3. to review, feature: 🗨️ chat

#2960 Fix to open conversation list when navigating back
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/nextcloud/talk/chat/ChatActivity.kt
Labels: 3. to review

#2963 Handle new capabilities json structure
  app/src/main/java/com/nextcloud/talk/data/user/model/User.kt
  app/src/main/java/com/nextcloud/talk/models/json/capabilities/SpreedCapability.kt
  app/src/main/java/com/nextcloud/talk/utils/database/user/CapabilitiesUtilNew.kt
Labels: 3. to review

#2976 Fix call feature parsing
  app/src/main/java/com/nextcloud/talk/data/user/model/User.kt
  app/src/main/java/com/nextcloud/talk/utils/database/user/CapabilitiesUtilNew.kt
Labels: bug, 3. to review

#2980 Remove remaining webrtc download implementation
  buildSrc/build.gradle
Labels: 3. to review
