Repository nextcloud/talk-android, pull requests merged in 2023-11, with the labels that each got.

#3427 Avoid Npe for call with a guest without name
  app/src/main/java/com/nextcloud/talk/activities/CallActivity.kt
Labels: 3. to review, backport-request

#3417 hide "unread mention" bubble in search mode
  app/src/main/java/com/nextcloud/talk/conversationlist/ConversationsListActivity.kt
Labels: bug, 3. to review

#3431 Bump version to 18.0.0 Alpha 1
  app/build.gradle
Labels: 3. to review

#3416 feature/2331/saveFiles
  app/src/main/java/com/nextcloud/talk/activities/FullScreenImageActivity.kt
  app/src/main/java/com/nextcloud/talk/chat/ChatActivity.kt
  app/src/main/java/com/nextcloud/talk/jobs/SaveFileToStorageWorker.kt
  app/src/main/java/com/nextcloud/talk/ui/dialog/MessageActionsDialog.kt
  app/src/main/res/layout/dialog_message_actions.xml
  app/src/main/res/menu/menu_preview.xml
  app/src/main/res/values/strings.xml
Labels: enhancement, 3. to review, feature: 🗨️ chat

#3430 Solve chat list disappears on configuration change
  app/src/main/java/com/nextcloud/talk/chat/viewmodels/ChatViewModel.kt
Labels: 3. to review, backport-request

#3433 followup changes to save file feature
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/nextcloud/talk/chat/ChatActivity.kt
  app/src/main/java/com/nextcloud/talk/fullscreenfile/FullScreenImageActivity.kt
  app/src/main/java/com/nextcloud/talk/fullscreenfile/FullScreenMediaActivity.kt
  app/src/main/java/com/nextcloud/talk/fullscreenfile/FullScreenTextViewerActivity.kt
  app/src/main/java/com/nextcloud/talk/jobs/SaveFileToStorageWorker.kt
  app/src/main/java/com/nextcloud/talk/ui/dialog/SaveToStorageDialogFragment.kt
  app/src/main/java/com/nextcloud/talk/utils/FileViewerUtils.kt
  app/src/main/res/drawable/baseline_download_24.xml
  app/src/main/res/layout/activity_full_screen_image.xml
  app/src/main/res/layout/activity_full_screen_media.xml
  app/src/main/res/layout/activity_full_screen_text.xml
  app/src/main/res/layout/dialog_message_actions.xml
  app/src/main/res/values-v27/styles.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: 3. to review

#3406 File Captions 🏷️
  app/src/main/java/com/nextcloud/talk/adapters/messages/IncomingPreviewMessageViewHolder.java
  app/src/main/java/com/nextcloud/talk/adapters/messages/OutcomingPreviewMessageViewHolder.java
  app/src/main/java/com/nextcloud/talk/adapters/messages/PreviewMessageViewHolder.kt
  app/src/main/java/com/nextcloud/talk/chat/ChatActivity.kt
  app/src/main/java/com/nextcloud/talk/models/json/chat/ChatMessage.kt
  app/src/main/java/com/nextcloud/talk/remotefilebrowser/activities/RemoteFileBrowserActivity.kt
  app/src/main/java/com/nextcloud/talk/ui/dialog/FileAttachmentPreviewFragment.kt
  app/src/main/res/layout/dialog_file_attachment_preview.xml
  app/src/main/res/layout/item_custom_incoming_preview_message.xml
  app/src/main/res/layout/item_custom_outcoming_preview_message.xml
  app/src/main/res/values/strings.xml
Labels: enhancement, 3. to review, feature: 🗨️ chat

#3451 File Caption Bug Fix - Bubble no longer under the user name
  app/src/main/res/layout/item_custom_incoming_preview_message.xml
Labels: bug, 3. to review, feature: 🗨️ chat

#3454 Fix to delete user when unregister for notifications failed
  app/src/main/java/com/nextcloud/talk/jobs/AccountRemovalWorker.java
Labels: 3. to review

#3457 close Call notification when onError is triggered.
  app/src/main/java/com/nextcloud/talk/jobs/NotificationWorker.kt
Labels: 3. to review

#3466 Bugfix/noid/fix save file dialog
  app/src/main/java/com/nextcloud/talk/ui/dialog/SaveToStorageDialogFragment.kt
  app/src/main/res/values-v27/styles.xml
  app/src/main/res/values/styles.xml
Labels: 3. to review, backport-request

#3453 Bug Fix - IllegalStateException in stopAudioRecording + Polishes
  app/src/main/java/com/nextcloud/talk/adapters/messages/IncomingPreviewMessageViewHolder.java
  app/src/main/java/com/nextcloud/talk/adapters/messages/IncomingVoiceMessageViewHolder.kt
  app/src/main/java/com/nextcloud/talk/adapters/messages/OutcomingPreviewMessageViewHolder.java
  app/src/main/java/com/nextcloud/talk/adapters/messages/OutcomingVoiceMessageViewHolder.kt
  app/src/main/java/com/nextcloud/talk/chat/ChatActivity.kt
  app/src/main/java/com/nextcloud/talk/conversationinfo/ConversationInfoActivity.kt
  app/src/main/java/com/nextcloud/talk/ui/MicInputCloud.kt
  app/src/main/java/com/nextcloud/talk/ui/WaveformSeekBar.kt
  app/src/main/java/com/nextcloud/talk/utils/preferences/AppPreferences.java
  app/src/main/java/com/nextcloud/talk/utils/preferences/AppPreferencesImpl.kt
Labels: bug, 3. to review, backport-request, feature: 🗨️ chat

#3474 translate "no proxy" in settings
  app/src/main/java/com/nextcloud/talk/settings/SettingsActivity.kt
  app/src/main/java/com/nextcloud/talk/utils/preferences/AppPreferencesImpl.kt
Labels: backport-request

#3482 avoid crash when NC notification could not be retrieved
  app/src/main/java/com/nextcloud/talk/jobs/NotificationWorker.kt
Labels: 3. to review, backport-request
