Repository nextcloud/talk-android, pull requests merged in 2023-07, with the labels that each got.

#3132 fix to load conversationlist only once after login
  app/src/main/java/com/nextcloud/talk/controllers/AccountVerificationController.kt
Labels: 3. to review

#3149 Create pr-feedback.yml
  .github/workflows/pr-feedback.yml
Labels: 3. to review

#3163 avoid ClassCastException on ItemLongClick in ConversationsListActivity
  app/src/main/java/com/nextcloud/talk/conversationlist/ConversationsListActivity.kt
Labels: backport-request

#3165 avoid NPE in ProfileActivity because userInfo could be null
  app/src/main/java/com/nextcloud/talk/profile/ProfileActivity.kt
Labels: backport-request

#3170 fix to be able to enter open conversation name
  app/src/main/java/com/nextcloud/talk/controllers/bottomsheet/EntryMenuController.kt
Labels: backport-request

#3155 Implement text formatting via markdown
  app/build.gradle
  app/src/main/java/com/nextcloud/talk/adapters/messages/IncomingLinkPreviewMessageViewHolder.kt
  app/src/main/java/com/nextcloud/talk/adapters/messages/IncomingLocationMessageViewHolder.kt
  app/src/main/java/com/nextcloud/talk/adapters/messages/IncomingPollMessageViewHolder.kt
  app/src/main/java/com/nextcloud/talk/adapters/messages/IncomingTextMessageViewHolder.kt
  app/src/main/java/com/nextcloud/talk/adapters/messages/IncomingVoiceMessageViewHolder.kt
  app/src/main/java/com/nextcloud/talk/adapters/messages/OutcomingLinkPreviewMessageViewHolder.kt
  app/src/main/java/com/nextcloud/talk/adapters/messages/OutcomingLocationMessageViewHolder.kt
  app/src/main/java/com/nextcloud/talk/adapters/messages/OutcomingPollMessageViewHolder.kt
  app/src/main/java/com/nextcloud/talk/adapters/messages/OutcomingTextMessageViewHolder.kt
  app/src/main/java/com/nextcloud/talk/adapters/messages/OutcomingVoiceMessageViewHolder.kt
  app/src/main/java/com/nextcloud/talk/dagger/modules/UtilsModule.kt
  app/src/main/java/com/nextcloud/talk/utils/DisplayUtils.java
  app/src/main/java/com/nextcloud/talk/utils/message/MessageUtils.kt
  build.gradle
Labels: enhancement, 3. to review, feature: 🗨️ chat

#3181 minor Websocket fixes
  app/src/main/java/com/nextcloud/talk/activities/CallActivity.java
  app/src/main/java/com/nextcloud/talk/chat/ChatActivity.kt
  app/src/main/java/com/nextcloud/talk/chat/viewmodels/ChatViewModel.kt
  app/src/main/java/com/nextcloud/talk/jobs/WebsocketConnectionsWorker.java
  app/src/main/java/com/nextcloud/talk/models/json/websocket/RoomWebSocketMessage.kt
  app/src/main/java/com/nextcloud/talk/utils/singletons/ApplicationWideCurrentRoomHolder.java
  app/src/main/java/com/nextcloud/talk/webrtc/WebSocketConnectionHelper.java
  app/src/main/java/com/nextcloud/talk/webrtc/WebSocketInstance.kt
Labels: backport-request

#3188 Translation string fixes
  app/src/main/java/com/nextcloud/talk/settings/SettingsActivity.kt
  app/src/main/res/layout/activity_settings.xml
  app/src/main/res/values/strings.xml
Labels: 3. to review, technical debt, backport-request

#3192 Display total duration of voice messages
  app/src/main/java/com/nextcloud/talk/adapters/messages/IncomingVoiceMessageViewHolder.kt
  app/src/main/java/com/nextcloud/talk/adapters/messages/OutcomingVoiceMessageViewHolder.kt
  app/src/main/java/com/nextcloud/talk/chat/ChatActivity.kt
  app/src/main/res/layout/item_custom_incoming_voice_message.xml
  app/src/main/res/layout/item_custom_outcoming_voice_message.xml
Labels: enhancement, 3. to review

#3190 Websocket improvements2
  app/src/main/java/com/nextcloud/talk/chat/ChatActivity.kt
  app/src/main/java/com/nextcloud/talk/jobs/WebsocketConnectionsWorker.java
  app/src/main/java/com/nextcloud/talk/webrtc/WebSocketConnectionHelper.java
  app/src/main/java/com/nextcloud/talk/webrtc/WebSocketInstance.kt
Labels: 3. to review, backport-request

#3135 Allow continuous recording and previewing of voice messages
  app/src/main/java/com/nextcloud/talk/chat/ChatActivity.kt
  app/src/main/java/com/nextcloud/talk/ui/MessageInput.kt
  app/src/main/java/com/nextcloud/talk/ui/MicInputCloud.kt
  app/src/main/java/com/nextcloud/talk/ui/theme/TalkSpecificViewThemeUtils.kt
  app/src/main/res/drawable/baseline_stop_24.xml
  app/src/main/res/layout/activity_chat.xml
  app/src/main/res/layout/view_message_input.xml
  app/src/main/res/values/attrs.xml
  app/src/main/res/values/strings.xml
Labels: enhancement, 3. to review, feature: 🗨️ chat

#3195 Rewind & Replay bug fix for Audio Duration
  app/src/main/java/com/nextcloud/talk/adapters/messages/IncomingVoiceMessageViewHolder.kt
  app/src/main/java/com/nextcloud/talk/adapters/messages/OutcomingVoiceMessageViewHolder.kt
  app/src/main/java/com/nextcloud/talk/chat/ChatActivity.kt
Labels: 3. to review

#3201 add to 17.0.2 to changelog
  CHANGELOG.md
Labels: 3. to review

#3210 Implement permission check for notifications on Android 13
  app/src/main/java/com/nextcloud/talk/conversationlist/ConversationsListActivity.kt
  app/src/main/java/com/nextcloud/talk/utils/permissions/PlatformPermissionUtil.kt
  app/src/main/java/com/nextcloud/talk/utils/permissions/PlatformPermissionUtilImpl.kt
Labels: bug, technical debt, backport-request

#3217 Implement status infos on chat view for 1on1 conversations
  app/src/main/java/com/nextcloud/talk/chat/ChatActivity.kt
  app/src/main/res/layout/activity_chat.xml
Labels: enhancement, 3. to review, feature: 🗨️ chat

#3218 Implement respecting the markdown rendering flag
  app/src/main/java/com/nextcloud/talk/adapters/messages/IncomingLinkPreviewMessageViewHolder.kt
  app/src/main/java/com/nextcloud/talk/adapters/messages/IncomingLocationMessageViewHolder.kt
  app/src/main/java/com/nextcloud/talk/adapters/messages/IncomingPollMessageViewHolder.kt
  app/src/main/java/com/nextcloud/talk/adapters/messages/IncomingTextMessageViewHolder.kt
  app/src/main/java/com/nextcloud/talk/adapters/messages/IncomingVoiceMessageViewHolder.kt
  app/src/main/java/com/nextcloud/talk/adapters/messages/OutcomingLinkPreviewMessageViewHolder.kt
  app/src/main/java/com/nextcloud/talk/adapters/messages/OutcomingLocationMessageViewHolder.kt
  app/src/main/java/com/nextcloud/talk/adapters/messages/OutcomingPollMessageViewHolder.kt
  app/src/main/java/com/nextcloud/talk/adapters/messages/OutcomingTextMessageViewHolder.kt
  app/src/main/java/com/nextcloud/talk/adapters/messages/OutcomingVoiceMessageViewHolder.kt
  app/src/main/java/com/nextcloud/talk/models/json/chat/ChatMessage.kt
  app/src/main/java/com/nextcloud/talk/utils/message/MessageUtils.kt
Labels: enhancement, 3. to review, feature: 🗨️ chat

#3220 Replace plus icon with pencil for main fab action
  app/src/main/res/layout/controller_conversations_rv.xml
Labels: design, 3. to review, papercut

#3222 Resize chat headline to 18sp
  app/src/main/res/layout/activity_chat.xml
Labels: design
