Repository nextcloud/talk-android, pull requests merged in 2023-01, with the labels that each got.

#2667 bump webrtc version to 108.5359.0
  app/build.gradle
Labels: 3. to review, backport-request

#2687 Bump version to 16.0.0
  app/build.gradle
Labels: 3. to review

#2600 Split call participants and peer connections
  app/src/main/java/com/nextcloud/talk/activities/CallActivity.java
  app/src/main/java/com/nextcloud/talk/adapters/ParticipantDisplayItem.java
  app/src/main/java/com/nextcloud/talk/adapters/ParticipantDisplayItemNotifier.java
  app/src/main/java/com/nextcloud/talk/adapters/ParticipantsAdapter.java
  app/src/main/java/com/nextcloud/talk/call/CallParticipant.java
  app/src/main/java/com/nextcloud/talk/call/CallParticipantList.java
  app/src/main/java/com/nextcloud/talk/call/CallParticipantListNotifier.java
  app/src/main/java/com/nextcloud/talk/call/CallParticipantModel.java
  app/src/main/java/com/nextcloud/talk/call/CallParticipantModelNotifier.java
  app/src/main/java/com/nextcloud/talk/call/MutableCallParticipantModel.java
  app/src/main/java/com/nextcloud/talk/webrtc/PeerConnectionWrapper.java
  app/src/test/java/com/nextcloud/talk/call/CallParticipantListExternalSignalingTest.java
  app/src/test/java/com/nextcloud/talk/call/CallParticipantListInternalSignalingTest.java
  app/src/test/java/com/nextcloud/talk/call/CallParticipantListTest.java
Labels: 3. to review, feature: ☎️ call

#2694 avoid crashes with NPEs for bindings
  app/src/main/java/com/nextcloud/talk/controllers/AccountVerificationController.kt
  app/src/main/java/com/nextcloud/talk/controllers/ChatController.kt
  app/src/main/java/com/nextcloud/talk/controllers/ContactsController.kt
  app/src/main/java/com/nextcloud/talk/controllers/ConversationInfoController.kt
  app/src/main/java/com/nextcloud/talk/controllers/ConversationsListController.kt
  app/src/main/java/com/nextcloud/talk/controllers/GeocodingController.kt
  app/src/main/java/com/nextcloud/talk/controllers/LocationPickerController.kt
  app/src/main/java/com/nextcloud/talk/controllers/LockedController.kt
  app/src/main/java/com/nextcloud/talk/controllers/ProfileController.kt
  app/src/main/java/com/nextcloud/talk/controllers/RingtoneSelectionController.kt
  app/src/main/java/com/nextcloud/talk/controllers/ServerSelectionController.kt
  app/src/main/java/com/nextcloud/talk/controllers/SettingsController.kt
  app/src/main/java/com/nextcloud/talk/controllers/SwitchAccountController.kt
  app/src/main/java/com/nextcloud/talk/controllers/WebViewLoginController.kt
  app/src/main/java/com/nextcloud/talk/controllers/base/BaseController.kt
  app/src/main/java/com/nextcloud/talk/controllers/bottomsheet/EntryMenuController.kt
  app/src/main/java/com/nextcloud/talk/controllers/bottomsheet/OperationsMenuController.kt
  app/src/main/java/com/nextcloud/talk/controllers/util/ControllerViewBindingDelegate.kt
Labels: 3. to review, backport-request

#2697 fix missing file icons in chat
  app/src/main/java/com/nextcloud/talk/adapters/messages/PreviewMessageViewHolder.kt
  app/src/main/java/com/nextcloud/talk/controllers/ChatController.kt
  app/src/main/java/com/nextcloud/talk/extensions/ImageViewExtensions.kt
Labels: 3. to review, backport-request

#2701 update changelog for 15.1.1
  CHANGELOG.md
Labels: 3. to review

#2684 Do not create offer for received screen share
  app/src/main/java/com/nextcloud/talk/webrtc/PeerConnectionWrapper.java
Labels: bug, 3. to review, feature: ☎️ call

#2706 Bugfix/2705/fix to show author name in group conversation
  app/src/main/java/com/nextcloud/talk/adapters/messages/IncomingLinkPreviewMessageViewHolder.kt
  app/src/main/java/com/nextcloud/talk/adapters/messages/IncomingLocationMessageViewHolder.kt
  app/src/main/java/com/nextcloud/talk/adapters/messages/IncomingPollMessageViewHolder.kt
  app/src/main/java/com/nextcloud/talk/adapters/messages/IncomingPreviewMessageViewHolder.java
  app/src/main/java/com/nextcloud/talk/adapters/messages/IncomingTextMessageViewHolder.kt
  app/src/main/java/com/nextcloud/talk/adapters/messages/IncomingVoiceMessageViewHolder.kt
  app/src/main/res/layout/item_custom_incoming_location_message.xml
Labels: backport-request

#2708 avoid NPE on hangup
  app/src/main/java/com/nextcloud/talk/activities/CallActivity.java
Labels: 3. to review, backport-request

#2710 avoid crash when answering call
  app/src/main/java/com/nextcloud/talk/activities/CallNotificationActivity.kt
Labels: backport-request, feature: ☎️ call

#2714 improve voice message quality
  app/src/main/java/com/nextcloud/talk/controllers/ChatController.kt
Labels: 3. to review, backport-request

#2614 Feature/2554/call recording support
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/nextcloud/talk/activities/CallActivity.java
  app/src/main/java/com/nextcloud/talk/activities/CallBaseActivity.java
  app/src/main/java/com/nextcloud/talk/activities/CallNotificationActivity.kt
  app/src/main/java/com/nextcloud/talk/api/NcApi.java
  app/src/main/java/com/nextcloud/talk/controllers/ChatController.kt
  app/src/main/java/com/nextcloud/talk/dagger/modules/RepositoryModule.kt
  app/src/main/java/com/nextcloud/talk/dagger/modules/ViewModelModule.kt
  app/src/main/java/com/nextcloud/talk/models/domain/StartCallRecordingModel.kt
  app/src/main/java/com/nextcloud/talk/models/domain/StopCallRecordingModel.kt
  app/src/main/java/com/nextcloud/talk/models/json/chat/ChatMessage.kt
  app/src/main/java/com/nextcloud/talk/models/json/conversations/Conversation.kt
  app/src/main/java/com/nextcloud/talk/models/json/converters/EnumSystemMessageTypeConverter.kt
  app/src/main/java/com/nextcloud/talk/repositories/callrecording/CallRecordingRepository.kt
  app/src/main/java/com/nextcloud/talk/repositories/callrecording/CallRecordingRepositoryImpl.kt
  app/src/main/java/com/nextcloud/talk/ui/dialog/MoreCallActionsDialog.kt
  app/src/main/java/com/nextcloud/talk/utils/ApiUtils.java
  app/src/main/java/com/nextcloud/talk/utils/VibrationUtils.kt
  app/src/main/java/com/nextcloud/talk/utils/bundle/BundleKeys.kt
  app/src/main/java/com/nextcloud/talk/utils/database/user/CapabilitiesUtilNew.kt
  app/src/main/java/com/nextcloud/talk/viewmodels/CallRecordingViewModel.kt
  app/src/main/java/com/nextcloud/talk/webrtc/MagicWebSocketInstance.java
  app/src/main/java/com/nextcloud/talk/webrtc/WebSocketConnectionHelper.java
  app/src/main/java/com/nextcloud/talk/webrtc/WebSocketInstance.kt
  app/src/main/res/drawable/ic_dots_horizontal_white.xml
  app/src/main/res/drawable/record_start.xml
  app/src/main/res/drawable/record_stop.xml
  app/src/main/res/layout/call_activity.xml
  app/src/main/res/layout/dialog_audio_output.xml
  app/src/main/res/layout/dialog_more_call_actions.xml
  app/src/main/res/values/strings.xml
  app/src/test/java/com/nextcloud/talk/test/fakes/FakeCallRecordingRepository.kt
  app/src/test/java/com/nextcloud/talk/viewmodels/AbstractViewModelTest.kt
  app/src/test/java/com/nextcloud/talk/viewmodels/CallRecordingViewModelTest.kt
Labels: 3. to review
