Repository nextcloud/talk-android, pull requests merged in 2023-03, with the labels that each got.

#2810 Show upload failed notification when failed normal upload
  app/src/main/java/com/nextcloud/talk/jobs/UploadAndShareFilesWorker.kt
  app/src/main/res/drawable/baseline_error_24.xml
Labels: backport-request

#2808 Avoid duplicated messages / Fix messages not being displayed
  app/src/main/java/com/nextcloud/talk/activities/CallActivity.java
  app/src/main/java/com/nextcloud/talk/controllers/ChatController.kt
Labels: 2. developing, backport-request

#2820 Hide inactive breakout rooms from conversation list
  app/src/main/java/com/nextcloud/talk/adapters/items/ConversationItem.kt
  app/src/main/java/com/nextcloud/talk/controllers/ChatController.kt
  app/src/main/java/com/nextcloud/talk/controllers/ConversationsListController.kt
  app/src/main/java/com/nextcloud/talk/models/json/conversations/Conversation.kt
  app/src/main/java/com/nextcloud/talk/models/json/converters/ConversationObjectTypeConverter.kt
Labels: backport-request

#2815 Request RoomInfo every 30 sec instead 5sec when not waiting in lobby
  app/src/main/java/com/nextcloud/talk/controllers/ChatController.kt
Labels: 3. to review, backport-request, feature: 🗨️ chat

#2824 Restrict to join other rooms while being in a call
  app/src/main/java/com/nextcloud/talk/controllers/ChatController.kt
  app/src/main/java/com/nextcloud/talk/controllers/ConversationsListController.kt
  app/src/main/res/values/strings.xml
Labels: 3. to review, backport-request

#2826 Add toast for debug mode if failed to get NC notification
  app/src/main/java/com/nextcloud/talk/jobs/NotificationWorker.kt
Labels: backport-request

#2828 fix string so build is possible again
  app/src/main/res/values/strings.xml
Labels: 3. to review, backport-request

#2830 Fix theming of set status dialog buttons
  app/src/main/java/com/nextcloud/talk/ui/dialog/SetStatusDialogFragment.kt
  app/src/main/java/com/nextcloud/talk/ui/theme/TalkSpecificViewThemeUtils.kt
  app/src/main/res/layout/dialog_set_status.xml
Labels: backport-request

#2835 Avoid NPE (replace scrollToPositionWithOffset(..) with scrollToPositi…
  app/src/main/java/com/nextcloud/talk/controllers/ChatController.kt
Labels: 3. to review, backport-request, feature: 🗨️ chat

#2833 Show keyboard at click on empty space
  app/src/main/res/layout/view_message_input.xml
Labels: 3. to review, backport-request, feature: 🗨️ chat

#2837 Avoid NPE for voice message recording
  app/src/main/java/com/nextcloud/talk/controllers/ChatController.kt
Labels: 3. to review, backport-request, feature: 🗨️ chat

#2841 Fix rare crash when starting call
  app/src/main/java/com/nextcloud/talk/controllers/ChatController.kt
Labels: 3. to review, backport-request, feature: 🗨️ chat, feature: ☎️ call

#2844 Scroll to quoted message also for outgoing messages
  app/src/main/java/com/nextcloud/talk/adapters/messages/OutcomingTextMessageViewHolder.kt
Labels: 3. to review, backport-request

#2845 Bugfix/2814/avoid duplicated messages after history pull
  app/src/main/java/com/nextcloud/talk/controllers/ChatController.kt
  scripts/analysis/lint-results.txt
Labels: 2. developing, backport-request

#2848 Fix horizontal (=landscape) call design
  app/src/main/res/layout/call_activity.xml
Labels: 3. to review, backport-request

#2852 Fix to get websocketInstance
  app/src/main/java/com/nextcloud/talk/application/NextcloudTalkApplication.kt
  app/src/main/java/com/nextcloud/talk/controllers/AccountVerificationController.kt
  app/src/main/java/com/nextcloud/talk/controllers/ChatController.kt
  app/src/main/java/com/nextcloud/talk/jobs/CapabilitiesWorker.java
  app/src/main/java/com/nextcloud/talk/jobs/SignalingSettingsWorker.java
  app/src/main/java/com/nextcloud/talk/webrtc/WebSocketConnectionHelper.java
Labels: 3. to review, backport-request

#2671 Split different exception scopes / Use own OkHttp client for coil
  app/src/main/java/com/nextcloud/talk/activities/BaseActivity.kt
  app/src/main/java/com/nextcloud/talk/application/NextcloudTalkApplication.kt
  app/src/main/java/com/nextcloud/talk/components/filebrowser/webdav/ReadFilesystemOperation.java
  app/src/main/java/com/nextcloud/talk/components/filebrowser/webdav/ReadFolderListingOperation.kt
  app/src/main/java/com/nextcloud/talk/controllers/WebViewLoginController.kt
  app/src/main/java/com/nextcloud/talk/dagger/modules/RestModule.java
  app/src/main/java/com/nextcloud/talk/events/CertificateEvent.java
  app/src/main/java/com/nextcloud/talk/upload/chunked/ChunkedFileUploader.kt
  app/src/main/java/com/nextcloud/talk/utils/ssl/KeyManager.java
  app/src/main/java/com/nextcloud/talk/utils/ssl/TrustManager.java
  app/src/main/java/com/nextcloud/talk/webrtc/WebSocketInstance.kt
Labels: bug, 3. to review

#2863 Fix to display chips with emojis
  app/src/main/java/com/nextcloud/talk/adapters/messages/IncomingTextMessageViewHolder.kt
  app/src/main/java/com/nextcloud/talk/adapters/messages/OutcomingTextMessageViewHolder.kt
  app/src/main/java/com/nextcloud/talk/utils/DisplayUtils.java
Labels: 3. to review, backport-request

#2865 Feature/2819/add call recordings to shared items
  app/src/main/java/com/nextcloud/talk/shareditems/activities/SharedItemsActivity.kt
  app/src/main/java/com/nextcloud/talk/shareditems/model/SharedItemType.kt
  app/src/main/res/layout/activity_shared_items.xml
  app/src/main/res/values/strings.xml
Labels: 3. to review, backport-request

#2850 Fix horizontal (=landscape) call design button layouting/sizing
  app/src/main/res/layout/call_activity.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/styles.xml
Labels: 3. to review, backport-request

#2866 Send raise hand signaling message.
  app/src/main/java/com/nextcloud/talk/activities/CallActivity.java
  app/src/main/java/com/nextcloud/talk/webrtc/PeerConnectionWrapper.java
Labels: 3. to review, backport-request

#2871 Hide call recording participant
  app/src/main/java/com/nextcloud/talk/activities/CallActivity.java
  app/src/main/java/com/nextcloud/talk/call/CallParticipant.java
  app/src/main/java/com/nextcloud/talk/call/CallParticipantList.java
  app/src/main/java/com/nextcloud/talk/call/CallParticipantModel.java
  app/src/main/java/com/nextcloud/talk/call/MutableCallParticipantModel.java
  app/src/main/java/com/nextcloud/talk/models/json/participants/Participant.kt
  app/src/main/java/com/nextcloud/talk/signaling/SignalingMessageReceiver.java
Labels: backport-request

#2873 Build(deps): Bump android-common from 0.6.0 to 0.7.0
  app/build.gradle
Labels: 3. to review, backport-request

#2882 Avoid NPE in loadAvatarImage
  app/src/main/java/com/nextcloud/talk/utils/DisplayUtils.java
Labels: backport-request

#2881 Avoid NPE in setupSwipeToReply
  app/src/main/java/com/nextcloud/talk/controllers/ChatController.kt
Labels: backport-request

#2880 Bump target and compile SDK to 33
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/nextcloud/talk/controllers/ChatController.kt
  app/src/main/java/com/nextcloud/talk/controllers/ConversationsListController.kt
  app/src/main/java/com/nextcloud/talk/jobs/UploadAndShareFilesWorker.kt
  app/src/main/java/com/nextcloud/talk/messagesearch/MessageSearchActivity.kt
  app/src/main/java/com/nextcloud/talk/utils/permissions/PlatformPermissionUtil.kt
  app/src/main/java/com/nextcloud/talk/utils/permissions/PlatformPermissionUtilImpl.kt
  app/src/main/res/values/strings.xml
Labels: 3. to review, technical debt

#2894 buildToolsVersion does not need to be specified
  app/build.gradle
Labels: 3. to review

#2912 Replace Controller with Activity for settings
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/nextcloud/talk/activities/MainActivity.kt
  app/src/main/java/com/nextcloud/talk/controllers/ConversationsListController.kt
  app/src/main/java/com/nextcloud/talk/jobs/AccountRemovalWorker.java
  app/src/main/java/com/nextcloud/talk/jobs/ContactAddressBookWorker.kt
  app/src/main/java/com/nextcloud/talk/settings/SettingsActivity.kt
  app/src/main/res/layout/activity_settings.xml
Labels: 3. to review

#2919 Split design for landscape editing/viewing a profile
  app/src/main/res/layout-land/activity_profile.xml
Labels: 3. to review
