Repository nextcloud/talk-android, pull requests merged in 2024-10, with the labels that each got.

#4293 make predefined status use custom time
  app/src/main/java/com/nextcloud/talk/ui/dialog/SetStatusDialogFragment.kt
Labels: 3. to review

#4321 Lock kotlin java version
  app/build.gradle
Labels: technical debt

#4300 Feature/4299/improve offline support
  app/src/main/java/com/nextcloud/talk/chat/ChatActivity.kt
  app/src/main/java/com/nextcloud/talk/chat/data/ChatMessageRepository.kt
  app/src/main/java/com/nextcloud/talk/chat/data/network/OfflineFirstChatRepository.kt
  app/src/main/java/com/nextcloud/talk/chat/viewmodels/ChatViewModel.kt
  app/src/main/java/com/nextcloud/talk/conversationlist/data/OfflineConversationsRepository.kt
  app/src/main/java/com/nextcloud/talk/conversationlist/data/network/OfflineFirstConversationsRepository.kt
Labels: 3. to review, backport-request

#4346 Fix ignored blank lines in Javadocs
  app/src/main/java/com/nextcloud/talk/call/CallParticipant.java
  app/src/main/java/com/nextcloud/talk/call/CallParticipantList.java
  app/src/main/java/com/nextcloud/talk/call/CallParticipantListNotifier.java
  app/src/main/java/com/nextcloud/talk/call/CallParticipantModel.java
  app/src/main/java/com/nextcloud/talk/call/MutableCallParticipantModel.java
  app/src/main/java/com/nextcloud/talk/signaling/LocalParticipantMessageNotifier.java
  app/src/main/java/com/nextcloud/talk/signaling/OfferMessageNotifier.java
  app/src/main/java/com/nextcloud/talk/signaling/ParticipantListMessageNotifier.java
  app/src/main/java/com/nextcloud/talk/signaling/SignalingMessageReceiver.java
  app/src/main/java/com/nextcloud/talk/webrtc/DataChannelMessageNotifier.java
  app/src/main/java/com/nextcloud/talk/webrtc/PeerConnectionNotifier.java
Labels: bug, 3. to review, backport-request

#4359 Remove dead code to set the call state
  app/src/main/java/com/nextcloud/talk/activities/CallActivity.kt
Labels: bug, 3. to review, backport-request, feature: ☎️ call

#4327 show deck card in messages
  app/src/main/java/com/nextcloud/talk/adapters/items/ConversationItem.kt
  app/src/main/java/com/nextcloud/talk/adapters/messages/IncomingDeckCardViewHolder.kt
  app/src/main/java/com/nextcloud/talk/adapters/messages/OutcomingDeckCardViewHolder.kt
  app/src/main/java/com/nextcloud/talk/adapters/messages/TalkMessagesListAdapter.java
  app/src/main/java/com/nextcloud/talk/chat/ChatActivity.kt
  app/src/main/java/com/nextcloud/talk/chat/data/model/ChatMessage.kt
  app/src/main/res/drawable/deck.xml
  app/src/main/res/layout/item_custom_incoming_deck_card_message.xml
  app/src/main/res/layout/item_custom_outcoming_deck_card_message.xml
  app/src/main/res/values/strings.xml
Labels: 3. to review

#4371 Fix handling of end call for everyone with external signaling
  app/src/main/java/com/nextcloud/talk/signaling/SignalingMessageReceiver.java
  app/src/test/java/com/nextcloud/talk/signaling/SignalingMessageReceiverParticipantListTest.java
Labels: bug, 3. to review, backport-request, feature: ☎️ call

#4368 Time setting for lobby
  app/src/main/java/com/nextcloud/talk/conversationinfo/ConversationInfoActivity.kt
Labels: 3. to review, backport-request

#4318 group chat messages
  app/src/main/java/com/nextcloud/talk/chat/ChatActivity.kt
  app/src/main/java/com/nextcloud/talk/utils/DateUtils.kt
Labels: 3. to review, backport-request

#4333 Archived Conversations 🗃️
  app/schemas/com.nextcloud.talk.data.source.local.TalkDatabase/11.json
  app/src/main/java/com/nextcloud/talk/api/NcApiCoroutines.kt
  app/src/main/java/com/nextcloud/talk/conversationinfo/ConversationInfoActivity.kt
  app/src/main/java/com/nextcloud/talk/conversationinfo/viewmodel/ConversationInfoViewModel.kt
  app/src/main/java/com/nextcloud/talk/conversationlist/ConversationsListActivity.kt
  app/src/main/java/com/nextcloud/talk/dagger/modules/RepositoryModule.kt
  app/src/main/java/com/nextcloud/talk/data/database/mappers/ConversationMapUtils.kt
  app/src/main/java/com/nextcloud/talk/data/database/model/ConversationEntity.kt
  app/src/main/java/com/nextcloud/talk/data/source/local/Migrations.kt
  app/src/main/java/com/nextcloud/talk/data/source/local/TalkDatabase.kt
  app/src/main/java/com/nextcloud/talk/models/domain/ConversationModel.kt
  app/src/main/java/com/nextcloud/talk/models/json/conversations/Conversation.kt
  app/src/main/java/com/nextcloud/talk/repositories/conversations/ConversationsRepository.kt
  app/src/main/java/com/nextcloud/talk/repositories/conversations/ConversationsRepositoryImpl.kt
  app/src/main/java/com/nextcloud/talk/ui/dialog/FilterConversationFragment.kt
  app/src/main/java/com/nextcloud/talk/utils/ApiUtils.kt
  app/src/main/java/com/nextcloud/talk/utils/CapabilitiesUtil.kt
  app/src/main/res/drawable/outline_archive_24.xml
  app/src/main/res/layout/activity_conversation_info.xml
  app/src/main/res/layout/dialog_filter_conversation.xml
  app/src/main/res/values/strings.xml
Labels: 3. to review
