Repository nextcloud/talk-android, pull requests merged in 2024-07, with the labels that each got.

#3980 build(qa): Switch deprecated `set-output` to `$GITHUB_OUTPUT`
  .github/workflows/qa.yml
Labels: 3. to review, technical debt

#3936 Contacts activity
  .editorconfig
  .idea/inspectionProfiles/ktlint.xml
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/nextcloud/talk/adapters/items/ContactItem.java
  app/src/main/java/com/nextcloud/talk/adapters/items/ContactItem.kt
  app/src/main/java/com/nextcloud/talk/adapters/items/GenericTextHeaderItem.java
  app/src/main/java/com/nextcloud/talk/adapters/items/GenericTextHeaderItem.kt
  app/src/main/java/com/nextcloud/talk/api/NcApiCoroutines.kt
  app/src/main/java/com/nextcloud/talk/contacts/ContactsActivity.kt
  app/src/main/java/com/nextcloud/talk/contacts/ContactsActivityCompose.kt
  app/src/main/java/com/nextcloud/talk/contacts/ContactsRepository.kt
  app/src/main/java/com/nextcloud/talk/contacts/ContactsRepositoryImpl.kt
  app/src/main/java/com/nextcloud/talk/contacts/ContactsViewModel.kt
  app/src/main/java/com/nextcloud/talk/contacts/SearchComponent.kt
  app/src/main/java/com/nextcloud/talk/contacts/ShareType.kt
  app/src/main/java/com/nextcloud/talk/conversationlist/ConversationsListActivity.kt
  app/src/main/java/com/nextcloud/talk/dagger/modules/BusModule.java
  app/src/main/java/com/nextcloud/talk/dagger/modules/RepositoryModule.kt
  app/src/main/java/com/nextcloud/talk/dagger/modules/RestModule.java
  app/src/main/java/com/nextcloud/talk/dagger/modules/ViewModelModule.kt
  app/src/main/java/com/nextcloud/talk/utils/ContactUtils.kt
  app/src/main/res/drawable/baseline_chat_bubble_outline_24.xml
  app/src/main/res/values/strings.xml
  build.gradle
  gradle/verification-metadata.xml
Labels: enhancement, 3. to review, feature: 📄 conversations

#4020 remove jCenter
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/nextcloud/talk/adapters/messages/IncomingVoiceMessageViewHolder.kt
  app/src/main/java/com/nextcloud/talk/extensions/ImageViewExtensions.kt
  app/src/main/java/com/nextcloud/talk/utils/TextDrawable.kt
  app/src/main/res/values/colors.xml
  build.gradle
  detekt.yml
  gradle.properties
  gradle/verification-keyring.keys
  gradle/verification-metadata.xml
Labels: 3. to review

#4021 Editing a replied-to message no longer makes the reference to the original message disappear
  app/src/main/java/com/nextcloud/talk/chat/ChatActivity.kt
Labels: 3. to review, feature: 🗨️ chat

#4035 Fix typo in automerge attribute
  renovate.json5
Labels: bug, 3. to review

#4037 Block fido updates (again)
  app/build.gradle
  renovate.json5
Labels: bug, 3. to review
