Repository nextcloud/talk-android, pull requests merged in 2024-08, with the labels that each got.

#3904 🚫 Allow Banning Users and Guests
  app/src/main/java/com/nextcloud/talk/api/NcApi.java
  app/src/main/java/com/nextcloud/talk/chat/data/ChatRepository.kt
  app/src/main/java/com/nextcloud/talk/chat/data/network/NetworkChatRepositoryImpl.kt
  app/src/main/java/com/nextcloud/talk/conversationinfo/ConversationInfoActivity.kt
  app/src/main/java/com/nextcloud/talk/conversationinfo/viewmodel/ConversationInfoViewModel.kt
  app/src/main/java/com/nextcloud/talk/models/json/participants/TalkBan.kt
  app/src/main/java/com/nextcloud/talk/models/json/participants/TalkBanOCS.kt
  app/src/main/java/com/nextcloud/talk/models/json/participants/TalkBanOverall.kt
  app/src/main/java/com/nextcloud/talk/ui/dialog/DialogBanListFragment.kt
  app/src/main/java/com/nextcloud/talk/utils/ApiUtils.kt
  app/src/main/java/com/nextcloud/talk/utils/CapabilitiesUtil.kt
  app/src/main/res/drawable/baseline_block_24.xml
  app/src/main/res/layout/activity_conversation_info.xml
  app/src/main/res/layout/ban_item_list.xml
  app/src/main/res/layout/dialog_ban_actor.xml
  app/src/main/res/layout/fragment_dialog_ban_list.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
Labels: medium, 2. developing, feature: 🗨️ chat, feedback-requested

#4060 Fix strings for banning
  app/src/main/java/com/nextcloud/talk/conversationinfo/ConversationInfoActivity.kt
  app/src/main/res/layout/dialog_ban_participant.xml
  app/src/main/res/values/strings.xml
Labels: 3. to review

#4102 Pin jackson core to 2.14.3
  app/build.gradle
  renovate.json5
Labels: bug, 3. to review, technical debt, dependencies

#4086 Fixing federated acceptance messages
  app/src/main/java/com/nextcloud/talk/chat/data/model/ChatMessage.kt
  app/src/main/java/com/nextcloud/talk/models/json/converters/EnumSystemMessageTypeConverter.kt
Labels: 3. to review, feature: 🗨️ chat, feature: 🌐 federation

#4111 chore: update workflows from templates
  .github/workflows/fixup.yml
  .github/workflows/pr-feedback.yml
  .github/workflows/reuse.yml
Labels: 3. to review, dependencies, automated

#4068 bump version to 20.1.0 Alpha 01
  app/build.gradle
Labels: 3. to review

#4122 No Edit Time limit on Note to Self Messages
  app/src/main/java/com/nextcloud/talk/ui/dialog/MessageActionsDialog.kt
  app/src/main/java/com/nextcloud/talk/utils/CapabilitiesUtil.kt
Labels: 3. to review, backport-request
