Repository nextcloud/talk-android, pull requests merged in 2024-03, with the labels that each got.

#3674 Fix: File Attachment Preview Dialog crashes ChatActivity
  app/src/main/java/com/nextcloud/talk/chat/ChatActivity.kt
  app/src/main/java/com/nextcloud/talk/ui/dialog/FileAttachmentPreviewFragment.kt
  app/src/main/res/layout/dialog_file_attachment_preview.xml
Labels: 3. to review

#3682 Renaming strings from circles to teams.
  app/src/main/java/com/nextcloud/talk/adapters/items/ParticipantItem.java
  app/src/main/java/com/nextcloud/talk/contacts/ContactsActivity.kt
  app/src/main/java/com/nextcloud/talk/conversationinfo/ConversationInfoActivity.kt
  app/src/main/res/values/strings.xml
Labels: backport-request

#3692 Place shimmer on top of the view to avoid view jumping
  app/src/main/java/com/nextcloud/talk/contacts/ContactsActivity.kt
  app/src/main/res/layout/activity_contacts.xml
Labels: 3. to review

#3685 add rest of SpreedFeatures to Enums
  app/src/main/java/com/nextcloud/talk/adapters/items/ConversationItem.kt
  app/src/main/java/com/nextcloud/talk/ui/dialog/ConversationsListBottomDialog.kt
  app/src/main/java/com/nextcloud/talk/ui/dialog/MessageActionsDialog.kt
  app/src/main/java/com/nextcloud/talk/utils/ApiUtils.kt
  app/src/main/java/com/nextcloud/talk/utils/CapabilitiesUtil.kt
  app/src/main/java/com/nextcloud/talk/utils/ConversationUtils.kt
  app/src/main/java/com/nextcloud/talk/utils/ParticipantPermissions.kt
  app/src/main/java/com/nextcloud/talk/utils/preferences/preferencestorage/DatabaseStorageModule.java
Labels: 3. to review

#3675 Follow up fixes to ChatActivity w/ recent refactoring
  app/src/main/java/com/nextcloud/talk/chat/ChatActivity.kt
  app/src/main/java/com/nextcloud/talk/chat/viewmodels/ChatViewModel.kt
  app/src/main/java/com/nextcloud/talk/conversationlist/ConversationsListActivity.kt
  app/src/main/res/values/strings.xml
Labels: 3. to review, feature: 🗨️ chat, feature: 🌐 federation

#3702 Add SPDX header from sync
  .github/workflows/pr-feedback.yml
Labels: technical debt, sync

#3677 Fix: Use of parameterized constructor with fragments
  app/src/main/java/com/nextcloud/talk/chat/ChatActivity.kt
  app/src/main/java/com/nextcloud/talk/conversationlist/ConversationsListActivity.kt
  app/src/main/java/com/nextcloud/talk/ui/dialog/DateTimePickerFragment.kt
  app/src/main/java/com/nextcloud/talk/ui/dialog/FilterConversationFragment.kt
  app/src/main/res/layout/dialog_date_time_picker.xml
Labels: 3. to review

#3698 hide some features if federation is not available
  app/src/main/java/com/nextcloud/talk/chat/ChatActivity.kt
  app/src/main/java/com/nextcloud/talk/conversationlist/ConversationsListActivity.kt
  app/src/main/java/com/nextcloud/talk/ui/dialog/MessageActionsDialog.kt
  app/src/main/java/com/nextcloud/talk/utils/CapabilitiesUtil.kt
Labels: 3. to review

#3711 fix placement of contacts header items
  app/src/main/res/layout/activity_contacts.xml
Labels: 3. to review

#3716 Fix Recents Screen
  app/src/main/java/com/nextcloud/talk/activities/BaseActivity.kt
Labels: 3. to review

#3712 fix to hide open conversations after returning from search
  app/src/main/java/com/nextcloud/talk/conversationlist/ConversationsListActivity.kt
Labels: 3. to review

#3704 Resumes playback of VoiceMessages on screen rotation and continue playing a voice message if chatActivity in background but still open
  app/src/main/java/com/nextcloud/talk/chat/ChatActivity.kt
Labels: 3. to review

#3722 Chore/noid/pin ubuntudependency
  .devcontainer/Dockerfile
Labels: technical debt

#3721 Add SPDX header
  .drone.yml
  .github/FUNDING.yml
  .github/ISSUE_TEMPLATE/bug_report.yml.license
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.yml.license
  .github/no-response.yml
  .github/pull_request_template.md.license
  LICENSES/Apache-2.0.txt
  LICENSES/GPL-3.0-or-later.txt
  LICENSES/MIT.txt
  app/build.gradle
  app/proguard-rules.pro
  app/src/main/java/com/nextcloud/talk/chat/ChatActivity.kt
  build.gradle
  gradle.properties
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  renovate.json5.license
  settings.gradle
Labels: 3. to review, technical debt

#3723 Add reuse dep5 package definition
  .reuse/dep5
Labels: 3. to review, technical debt

#3724 fix name bug
  .github/ISSUE_TEMPLATE/feature_request.md.license
Labels: 3. to review, technical debt

#3725 Bump heap space
  .github/workflows/codeql.yml
Labels: technical debt, don't merge

#3726 SPDX header part2
  .editorconfig
  .gitignore
  .reuse/dep5
  CHANGELOG.md
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  README.md
  SECURITY.md
  SETUP.md
  app/src/gplay/AndroidManifest.xml
  app/src/main/AndroidManifest.xml
  detekt.yml
  gradle/verification-keyring.keys.license
  gradle/verification-metadata.xml.license
  gradle/wrapper/gradle-wrapper.jar.license
  spotbugs-filter.xml
Labels: technical debt

#3710 use X-Chat-Last-Common-Read to fix read status
  app/src/main/java/com/nextcloud/talk/chat/ChatActivity.kt
Labels: 3. to review

#3707 Implemented delete-messages-unlimited feature
  app/src/main/java/com/nextcloud/talk/chat/ChatActivity.kt
  app/src/main/java/com/nextcloud/talk/utils/CapabilitiesUtil.kt
Labels: 3. to review

#3719 Update mine type icons
  app/src/main/res/drawable/ic_mimetype_application_pdf.xml
  app/src/main/res/drawable/ic_mimetype_image.xml
  app/src/main/res/drawable/ic_mimetype_text.xml
  app/src/main/res/drawable/ic_mimetype_video.xml
  app/src/main/res/drawable/ic_mimetype_x_office_document.xml
  app/src/main/res/drawable/ic_mimetype_x_office_presentation.xml
  app/src/main/res/drawable/ic_mimetype_x_office_spreadsheet.xml
Labels: 3. to review

#3720 Retain Settings Screen Scroll State
  app/src/main/res/layout/activity_settings.xml
Labels: 3. to review

#3739 Update text mimetype color
  app/src/main/res/drawable/ic_mimetype_text.xml
Labels: 3. to review

#3736 Feature/noid/hide items for federated rooms
  app/src/main/java/com/nextcloud/talk/conversationinfo/ConversationInfoActivity.kt
  app/src/main/java/com/nextcloud/talk/shareditems/repositories/SharedItemsRepositoryImpl.kt
  app/src/main/java/com/nextcloud/talk/shareditems/viewmodels/SharedItemsViewModel.kt
  app/src/main/java/com/nextcloud/talk/ui/dialog/AttachmentDialog.kt
Labels: 3. to review

#3701 Federated Mentions
  app/src/main/java/com/nextcloud/talk/adapters/items/MentionAutocompleteItem.java
  app/src/main/java/com/nextcloud/talk/adapters/items/MentionAutocompleteItem.kt
  app/src/main/java/com/nextcloud/talk/adapters/items/ParticipantItem.java
  app/src/main/java/com/nextcloud/talk/adapters/messages/IncomingLinkPreviewMessageViewHolder.kt
  app/src/main/java/com/nextcloud/talk/adapters/messages/IncomingLocationMessageViewHolder.kt
  app/src/main/java/com/nextcloud/talk/adapters/messages/IncomingPollMessageViewHolder.kt
  app/src/main/java/com/nextcloud/talk/adapters/messages/IncomingTextMessageViewHolder.kt
  app/src/main/java/com/nextcloud/talk/adapters/messages/IncomingVoiceMessageViewHolder.kt
  app/src/main/java/com/nextcloud/talk/adapters/messages/PreviewMessageViewHolder.kt
  app/src/main/java/com/nextcloud/talk/adapters/messages/SystemMessageViewHolder.kt
  app/src/main/java/com/nextcloud/talk/callbacks/MentionAutocompleteCallback.java
  app/src/main/java/com/nextcloud/talk/chat/ChatActivity.kt
  app/src/main/java/com/nextcloud/talk/extensions/ImageViewExtensions.kt
  app/src/main/java/com/nextcloud/talk/location/LocationPickerActivity.kt
  app/src/main/java/com/nextcloud/talk/models/json/chat/ChatMessage.kt
  app/src/main/java/com/nextcloud/talk/models/json/mention/Mention.kt
  app/src/main/java/com/nextcloud/talk/presenters/MentionAutocompletePresenter.java
  app/src/main/java/com/nextcloud/talk/utils/ApiUtils.kt
  app/src/main/java/com/nextcloud/talk/utils/DisplayUtils.java
  app/src/main/java/com/nextcloud/talk/utils/DisplayUtils.kt
  app/src/main/java/com/nextcloud/talk/utils/message/MessageUtils.kt
Labels: enhancement, 3. to review, feature: 🗨️ chat, feature: 🌐 federation

#3740 Remove flickering background on the app bar
  app/src/main/res/layout/activity_conversations.xml
Labels: 3. to review

#3748 Add SPDX header
  .reuse/dep5
  LICENSES/CC-BY-SA-3.0.txt
  app/src/test/java/com/nextcloud/talk/call/CallParticipantListExternalSignalingTest.java
  app/src/test/java/com/nextcloud/talk/call/CallParticipantListInternalSignalingTest.java
  app/src/test/java/com/nextcloud/talk/call/CallParticipantListTest.java
  app/src/test/java/com/nextcloud/talk/call/CallParticipantModelTest.kt
  app/src/test/java/com/nextcloud/talk/messagesearch/MessageSearchHelperTest.kt
  app/src/test/java/com/nextcloud/talk/signaling/SignalingMessageReceiverCallParticipantTest.java
  app/src/test/java/com/nextcloud/talk/signaling/SignalingMessageReceiverLocalParticipantTest.java
  app/src/test/java/com/nextcloud/talk/signaling/SignalingMessageReceiverOfferTest.java
  app/src/test/java/com/nextcloud/talk/signaling/SignalingMessageReceiverParticipantListTest.java
  app/src/test/java/com/nextcloud/talk/signaling/SignalingMessageReceiverTest.java
  app/src/test/java/com/nextcloud/talk/signaling/SignalingMessageReceiverWebRtcTest.java
  app/src/test/java/com/nextcloud/talk/test/fakes/FakeCallRecordingRepository.kt
  app/src/test/java/com/nextcloud/talk/test/fakes/FakeUnifiedSearchRepository.kt
  app/src/test/java/com/nextcloud/talk/utils/BundleKeysTest.kt
  app/src/test/java/com/nextcloud/talk/utils/DoNotDisturbUtilsTest.java
  app/src/test/java/com/nextcloud/talk/utils/ParticipantPermissionsTest.kt
  app/src/test/java/com/nextcloud/talk/utils/ShareUtilsTest.kt
  app/src/test/java/com/nextcloud/talk/utils/UserIdUtilsTest.kt
  app/src/test/java/com/nextcloud/talk/viewmodels/AbstractViewModelTest.kt
  app/src/test/java/com/nextcloud/talk/viewmodels/CallRecordingViewModelTest.kt
  app/src/test/java/com/nextcloud/talk/webrtc/DataChannelMessageNotifierTest.kt
  app/src/test/java/com/nextcloud/talk/webrtc/GlobalsTest.kt
  app/src/test/java/com/nextcloud/talk/webrtc/PeerConnectionNotifierTest.kt
Labels: 3. to review, technical debt

#3738 Use DialogFragment for Phone Number Integration
  app/src/main/java/com/nextcloud/talk/settings/SettingsActivity.kt
  app/src/main/java/com/nextcloud/talk/ui/dialog/SetPhoneNumberDialogFragment.kt
  app/src/main/res/layout/dialog_set_phone_number.xml
  app/src/main/res/values/strings.xml
Labels: 3. to review

#3753 bump version to 19.1.0 Alpha01
  app/build.gradle
Labels: 3. to review

#3756 SPDX header6
  .reuse/dep5
  README.md
  app/src/main/assets/leafletMapMessagePreview.html.license
  app/src/main/java/com/nextcloud/talk/adapters/ParticipantDisplayItem.java
  app/src/main/java/com/nextcloud/talk/adapters/ParticipantsAdapter.java
  app/src/main/java/com/nextcloud/talk/adapters/messages/CommonMessageInterface.kt
  app/src/main/java/com/nextcloud/talk/adapters/messages/PreviewMessageInterface.kt
  app/src/main/java/com/nextcloud/talk/adapters/messages/SystemMessageInterface.kt
  app/src/main/java/com/nextcloud/talk/conversationinfo/GuestAccessHelper.kt
  app/src/main/java/com/nextcloud/talk/models/domain/ConversationModel.kt
  app/src/main/java/com/nextcloud/talk/models/json/status/ClearAt.kt
  app/src/main/java/com/nextcloud/talk/models/json/status/predefined/PredefinedStatus.kt
  app/src/main/java/com/nextcloud/talk/repositories/unifiedsearch/UnifiedSearchRepository.kt
  app/src/main/java/com/nextcloud/talk/shareditems/model/SharedItem.kt
  app/src/main/java/com/nextcloud/talk/translate/repositories/TranslateRepository.kt
  app/src/main/java/com/nextcloud/talk/translate/repositories/TranslateRepositoryImpl.kt
  app/src/main/java/com/nextcloud/talk/translate/viewmodels/TranslateViewModel.kt
  app/src/main/java/com/nextcloud/talk/upload/normal/FileUploader.kt
  app/src/main/java/com/nextcloud/talk/utils/ContactUtils.kt
  app/src/main/java/com/nextcloud/talk/webrtc/Globals.java
  app/src/main/res/animator/appbar_elevation_off.xml
  app/src/main/res/animator/appbar_elevation_on.xml
  app/src/main/res/drawable/ic_launcher_foreground.xml
  app/src/main/res/layout/activity_settings.xml
  app/src/main/res/layout/edit_message_view.xml
  app/src/main/res/layout/item_guest_access_settings.xml
  app/src/main/res/layout/item_notification_settings.xml
  app/src/main/res/layout/item_webinar_info.xml
  app/src/main/res/values-v27/styles.xml
  app/src/main/res/values/styles.xml
  app/src/qa/res/drawable/ic_launcher_background.xml
  app/src/qa/res/drawable/ic_launcher_foreground.xml
  app/src/qa/res/mipmap-anydpi-v26/ic_launcher.xml
  docs/TURN.md
  docs/branching.png.license
  docs/branching.svg.license
  docs/gplayDebugBuildVariant.png.license
  docs/notifications.md
  docs/semantic_versioning_code.png.license
  scripts/analysis/analysis-wrapper.sh
  scripts/analysis/getBranchName.sh
  scripts/analysis/lint-results.txt.license
  scripts/analysis/lint-up.rb
  scripts/analysis/spotbugs-up.rb
  scripts/analysis/spotbugsComparison.py
  scripts/analysis/spotbugsSummary.py
  scripts/metadata/generate_metadata.py
  scripts/tools/OxygenConversion.MD
Labels: 3. to review, technical debt

#3758 Add SPDX header
  LICENCE.md
  app/src/generic/java/com/nextcloud/talk/utils/ClosedInterfaceImpl.java
  app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  app/src/main/res/values-land/dimens.xml
  app/src/main/res/values-night/colors.xml
  app/src/main/res/values-sw600dp/dimens.xml
  app/src/main/res/values-v28/arrays.xml
  app/src/main/res/values-v28/defaults.xml
  app/src/main/res/values-w820dp/dimens.xml
  app/src/main/res/values/arrays.xml
  app/src/main/res/values/attrs.xml
  app/src/main/res/values/bool.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/defaults.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/setup.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/auth.xml
  app/src/main/res/xml/backup_config.xml
  app/src/main/res/xml/chip_others.xml
  app/src/main/res/xml/chip_you.xml
  app/src/main/res/xml/contacts.xml
  app/src/main/res/xml/file_provider_paths.xml
  app/src/main/res/xml/network_security_config.xml
  app/src/main/res/xml/syncadapter.xml
  app/src/qa/java/com/nextcloud/talk/utils/ClosedInterfaceImpl.java
  app/src/qa/res/values/setup.xml
  contribute/developer-certificate-of-origin.license
Labels: technical debt

#3769 Feature/noid/federation invitation fixes
  app/src/main/java/com/nextcloud/talk/chat/ChatActivity.kt
  app/src/main/java/com/nextcloud/talk/conversationlist/viewmodels/ConversationsListViewModel.kt
  app/src/main/java/com/nextcloud/talk/extensions/ImageViewExtensions.kt
  app/src/main/java/com/nextcloud/talk/invitation/InvitationsActivity.kt
  app/src/main/java/com/nextcloud/talk/invitation/data/Invitation.kt
  app/src/main/java/com/nextcloud/talk/invitation/data/InvitationsRepositoryImpl.kt
  app/src/main/java/com/nextcloud/talk/models/json/chat/ChatMessage.kt
  app/src/main/java/com/nextcloud/talk/models/json/invitation/Invitation.kt
  app/src/main/java/com/nextcloud/talk/utils/message/MessageUtils.kt
Labels: 3. to review, backport-request
