Repository nextcloud/talk-android, pull requests merged in 2024-06, with the labels that each got.

#3942 Fixed MediaPlayerHandler crashing on lifecycle change
  app/src/main/java/com/nextcloud/talk/chat/ChatActivity.kt
Labels: 3. to review

#3941 Fixed Database module initialization error
  app/src/main/java/com/nextcloud/talk/conversationinfo/ConversationInfoActivity.kt
Labels: 3. to review, backport-request

#3792 Refactored Message input view into it's own Fragment
  app/src/main/java/com/nextcloud/talk/application/NextcloudTalkApplication.kt
  app/src/main/java/com/nextcloud/talk/chat/ChatActivity.kt
  app/src/main/java/com/nextcloud/talk/chat/MessageInputFragment.kt
  app/src/main/java/com/nextcloud/talk/chat/MessageInputVoiceRecordingFragment.kt
  app/src/main/java/com/nextcloud/talk/chat/data/io/AudioFocusRequestManager.kt
  app/src/main/java/com/nextcloud/talk/chat/data/io/AudioRecorderManager.kt
  app/src/main/java/com/nextcloud/talk/chat/data/io/LifecycleAwareManager.kt
  app/src/main/java/com/nextcloud/talk/chat/data/io/MediaPlayerManager.kt
  app/src/main/java/com/nextcloud/talk/chat/data/io/MediaRecorderManager.kt
  app/src/main/java/com/nextcloud/talk/chat/viewmodels/ChatViewModel.kt
  app/src/main/java/com/nextcloud/talk/chat/viewmodels/MessageInputViewModel.kt
  app/src/main/java/com/nextcloud/talk/dagger/modules/ManagerModule.kt
  app/src/main/java/com/nextcloud/talk/dagger/modules/ViewModelModule.kt
  app/src/main/java/com/nextcloud/talk/ui/dialog/MessageActionsDialog.kt
  app/src/main/res/layout/activity_chat.xml
  app/src/main/res/layout/fragment_message_input.xml
  app/src/main/res/layout/fragment_message_input_voice_recording.xml
  app/src/main/res/values/strings.xml
  scripts/analysis/lint-results.txt
Labels: 3. to review, feature: 🗨️ chat, feedback-requested

#3959 Follow up fix to refactoring
  app/src/main/java/com/nextcloud/talk/chat/ChatActivity.kt
  app/src/main/java/com/nextcloud/talk/chat/viewmodels/ChatViewModel.kt
Labels: bug, 3. to review

#3969 update to gradle 8.5.0
  build.gradle
  gradle/verification-keyring.keys
  gradle/verification-metadata.xml
Labels: 3. to review

#3970 update to kotlin 2.0 / use ksp where possible
  app/build.gradle
  app/src/main/java/com/nextcloud/talk/chat/data/io/AudioFocusRequestManager.kt
  build.gradle
  gradle/verification-metadata.xml
Labels: 3. to review
