Repository nextcloud/talk-android, pull requests merged in 2024-09, with the labels that each got.

#4136 fix to scroll to last read message
  app/src/main/java/com/nextcloud/talk/chat/ChatActivity.kt
  app/src/main/java/com/nextcloud/talk/chat/data/ChatMessageRepository.kt
  app/src/main/java/com/nextcloud/talk/chat/data/network/OfflineFirstChatRepository.kt
  app/src/main/java/com/nextcloud/talk/chat/viewmodels/ChatViewModel.kt
Labels: 3. to review, backport-request

#4069 Bug fixes for offline support
  app/src/main/java/com/nextcloud/talk/chat/ChatActivity.kt
  app/src/main/java/com/nextcloud/talk/chat/data/ChatMessageRepository.kt
  app/src/main/java/com/nextcloud/talk/chat/data/network/OfflineFirstChatRepository.kt
  app/src/main/java/com/nextcloud/talk/chat/viewmodels/ChatViewModel.kt
  app/src/main/java/com/nextcloud/talk/conversationlist/ConversationsListActivity.kt
  app/src/main/java/com/nextcloud/talk/conversationlist/data/network/OfflineFirstConversationsRepository.kt
  app/src/main/java/com/nextcloud/talk/dagger/modules/RepositoryModule.kt
  app/src/main/java/com/nextcloud/talk/data/database/dao/ConversationsDao.kt
Labels: backport-request

#4064 Create new conversation
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/nextcloud/talk/api/NcApiCoroutines.kt
  app/src/main/java/com/nextcloud/talk/contacts/ContactsActivityCompose.kt
  app/src/main/java/com/nextcloud/talk/contacts/ContactsViewModel.kt
  app/src/main/java/com/nextcloud/talk/contacts/SearchComponent.kt
  app/src/main/java/com/nextcloud/talk/contacts/ShareType.kt
  app/src/main/java/com/nextcloud/talk/conversationcreation/ConversationCreationActivity.kt
  app/src/main/java/com/nextcloud/talk/conversationcreation/ConversationCreationRepository.kt
  app/src/main/java/com/nextcloud/talk/conversationcreation/ConversationCreationRepositoryImpl.kt
  app/src/main/java/com/nextcloud/talk/conversationcreation/ConversationCreationViewModel.kt
  app/src/main/java/com/nextcloud/talk/dagger/modules/RepositoryModule.kt
  app/src/main/java/com/nextcloud/talk/dagger/modules/ViewModelModule.kt
  app/src/main/java/com/nextcloud/talk/data/database/mappers/ChatMessageMapUtils.kt
  app/src/main/java/com/nextcloud/talk/utils/ApiUtils.kt
  app/src/main/res/drawable/baseline_tag_faces_24.xml
  app/src/main/res/values/strings.xml
  app/src/test/java/com/nextcloud/talk/contacts/ContactsViewModelTest.kt
  gradle/verification-metadata.xml
Labels: 3. to review, backport-request

#4100 Revert "fix: deactivate broken test and remove test platform config"
  app/build.gradle
  app/src/test/java/com/nextcloud/talk/utils/ParticipantPermissionsTest.kt
  gradle/verification-keyring.keys
  gradle/verification-metadata.xml
Labels: 3. to review

#4162 Bugfix/4078/fix self reaction when re entering chat
  app/src/main/java/com/nextcloud/talk/data/source/local/converters/ArrayListConverter.kt
  app/src/main/java/com/nextcloud/talk/ui/theme/TalkSpecificViewThemeUtils.kt
Labels: 3. to review

#4182 Select contacts from search
  .idea/inspectionProfiles/ktlint.xml
  app/src/main/java/com/nextcloud/talk/chat/ChatActivity.kt
  app/src/main/java/com/nextcloud/talk/contacts/ContactsActivityCompose.kt
  app/src/main/java/com/nextcloud/talk/contacts/ContactsViewModel.kt
  app/src/main/java/com/nextcloud/talk/contacts/SearchComponent.kt
  gradle/verification-keyring.keys
  gradle/verification-metadata.xml
Labels: 3. to review, backport-request

#4191 remove theming of call buttons to remove disabled look for dark mode
  app/src/main/java/com/nextcloud/talk/chat/ChatActivity.kt
Labels: 3. to review, backport-request

#4194 sleep one second before websocket reconnect
  app/src/main/java/com/nextcloud/talk/webrtc/WebSocketInstance.kt
Labels: 3. to review, backport-request

#4193 do not try to pull chat messages when offline or paused
  app/src/main/java/com/nextcloud/talk/chat/data/network/OfflineFirstChatRepository.kt
Labels: 3. to review, backport-request

#4196 User avatar selection
  app/build.gradle
  app/src/main/java/com/nextcloud/talk/api/NcApiCoroutines.kt
  app/src/main/java/com/nextcloud/talk/conversationcreation/ConversationCreationActivity.kt
  app/src/main/java/com/nextcloud/talk/conversationcreation/ConversationCreationRepository.kt
  app/src/main/java/com/nextcloud/talk/conversationcreation/ConversationCreationRepositoryImpl.kt
  app/src/main/java/com/nextcloud/talk/conversationcreation/ConversationCreationViewModel.kt
Labels: 3. to review

#4183 Queuing offline messages to be sent online
  app/src/main/java/com/nextcloud/talk/chat/MessageInputFragment.kt
  app/src/main/java/com/nextcloud/talk/chat/viewmodels/MessageInputViewModel.kt
  app/src/main/java/com/nextcloud/talk/utils/preferences/AppPreferencesImpl.kt
  app/src/main/res/values/strings.xml
Labels: backport-request

#4216 Update SETUP.md
  SETUP.md
Labels: 3. to review

#4223 fix to load chat for old server version
  app/src/main/java/com/nextcloud/talk/activities/CallActivity.kt
  app/src/main/java/com/nextcloud/talk/models/json/conversations/Conversation.kt
Labels: backport-request

#4221 fix to show user status in conversation list
  app/src/main/java/com/nextcloud/talk/conversationlist/data/network/OfflineFirstConversationsRepository.kt
Labels: 3. to review, backport-request

#4231 fix to show accounts from older servers in switch account dialog
  app/src/main/java/com/nextcloud/talk/ui/dialog/ChooseAccountDialogFragment.java
Labels: backport-request

#4240 fix to hide messageInputFragment when user has no restriction to write
  app/src/main/java/com/nextcloud/talk/chat/ChatActivity.kt
Labels: 3. to review, backport-request

#4239 fix to not remove call buttons for federated conversations after 30 seconds
  app/src/main/java/com/nextcloud/talk/chat/ChatActivity.kt
Labels: 3. to review, backport-request

#4250 Conversation creation modification
  app/src/main/java/com/nextcloud/talk/activities/CallActivity.kt
  app/src/main/java/com/nextcloud/talk/chat/ChatActivity.kt
  app/src/main/java/com/nextcloud/talk/conversationcreation/ConversationCreationActivity.kt
  app/src/main/java/com/nextcloud/talk/conversationcreation/ConversationCreationViewModel.kt
Labels: backport-request

#4256 Fix Codacy Warnings - Ensure Composable Function Names Start with a Capital Letter
  detekt.yml
Labels: 3. to review

#4259 Password improvement
  app/src/main/java/com/nextcloud/talk/conversationcreation/ConversationCreationActivity.kt
  app/src/main/java/com/nextcloud/talk/conversationcreation/ConversationCreationViewModel.kt
  app/src/main/res/drawable/baseline_lock_open_24.xml
  app/src/main/res/values/strings.xml
Labels: 3. to review

#4277 Bugfix/4272/fix to handle old server versions
  app/src/main/java/com/nextcloud/talk/activities/CallActivity.kt
  app/src/main/java/com/nextcloud/talk/conversationinfo/ConversationInfoActivity.kt
  app/src/main/java/com/nextcloud/talk/data/database/mappers/ConversationMapUtils.kt
  app/src/main/java/com/nextcloud/talk/models/domain/ConversationModel.kt
  app/src/main/java/com/nextcloud/talk/models/json/conversations/Conversation.kt
  app/src/main/java/com/nextcloud/talk/ui/dialog/ConversationsListBottomDialog.kt
  app/src/main/java/com/nextcloud/talk/utils/CapabilitiesUtil.kt
  app/src/main/java/com/nextcloud/talk/utils/ConversationUtils.kt
  app/src/test/java/com/nextcloud/talk/json/ConversationConversionTest.kt
  app/src/test/resources/RoomOverallExample_APIv1.json
  app/src/test/resources/RoomOverallExample_APIv2.json
  app/src/test/resources/RoomOverallExample_APIv4.json
Labels: 3. to review, backport-request

#4284 add copyright header to fix reuse
  REUSE.toml
  app/src/test/java/com/nextcloud/talk/json/ConversationConversionTest.kt
Labels: 3. to review, backport-request

#4273 [Bug Fix] Fix wrong value when choosing custom reminder date
  app/src/main/java/com/nextcloud/talk/ui/dialog/DateTimePickerFragment.kt
Labels: 3. to review
