Repository nextcloud/talk-android, pull requests merged in 2024-02, with the labels that each got.

#3586 Implementing Add to Notes in Message Actions
  app/src/main/java/com/nextcloud/talk/chat/ChatActivity.kt
  app/src/main/java/com/nextcloud/talk/chat/data/ChatRepository.kt
  app/src/main/java/com/nextcloud/talk/chat/data/ChatRepositoryImpl.kt
  app/src/main/java/com/nextcloud/talk/chat/viewmodels/ChatViewModel.kt
  app/src/main/java/com/nextcloud/talk/jobs/UploadAndShareFilesWorker.kt
  app/src/main/java/com/nextcloud/talk/ui/dialog/MessageActionsDialog.kt
  app/src/main/res/drawable/ic_edit_note_24.xml
  app/src/main/res/layout/dialog_message_actions.xml
  app/src/main/res/values/strings.xml
Labels: 3. to review, feature: 🗨️ chat

#3617 Rename dav4 jvm package ID
  app/build.gradle
  gradle/verification-keyring.keys
  gradle/verification-metadata.xml
Labels: 3. to review, technical debt

#3625 chore: update workflows from templates
  .github/workflows/fixup.yml
Labels: 3. to review, dependencies, automated

#3535 Handle audio focus and becoming noisy
  app/src/main/java/com/nextcloud/talk/chat/ChatActivity.kt
  app/src/main/java/com/nextcloud/talk/chat/viewmodels/ChatViewModel.kt
  app/src/main/java/com/nextcloud/talk/fullscreenfile/FullScreenMediaActivity.kt
Labels: 3. to review

#3567 Grouping upload notification
  app/src/main/java/com/nextcloud/talk/jobs/UploadAndShareFilesWorker.kt
  app/src/main/java/com/nextcloud/talk/utils/NotificationUtils.kt
Labels: enhancement, 3. to review, feature: 🔔 notifications, feature: 🤝 sharing

#3613 avoid to send "speaking" data channel message when mic is muted
  app/src/main/java/com/nextcloud/talk/activities/CallActivity.kt
Labels: 3. to review

#3645 remove FOREGROUND_SERVICE_PHONE_CALL
  app/src/gplay/AndroidManifest.xml
Labels: 3. to review, backport-request

#3647 bump version to 19.0.0 Alpha 01
  app/build.gradle
Labels: 3. to review

#3657 Remove dependabot
  .github/dependabot.yml
Labels: technical debt

#3653 Feature/3532/federated invitation handling
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/nextcloud/talk/account/SwitchAccountActivity.kt
  app/src/main/java/com/nextcloud/talk/activities/MainActivity.kt
  app/src/main/java/com/nextcloud/talk/adapters/items/AdvancedUserItem.java
  app/src/main/java/com/nextcloud/talk/adapters/items/AdvancedUserItem.kt
  app/src/main/java/com/nextcloud/talk/api/NcApi.java
  app/src/main/java/com/nextcloud/talk/conversationlist/ConversationsListActivity.kt
  app/src/main/java/com/nextcloud/talk/conversationlist/data/ConversationsListRepository.kt
  app/src/main/java/com/nextcloud/talk/conversationlist/data/ConversationsListRepositoryImpl.kt
  app/src/main/java/com/nextcloud/talk/conversationlist/viewmodels/ConversationsListViewModel.kt
  app/src/main/java/com/nextcloud/talk/dagger/modules/RepositoryModule.kt
  app/src/main/java/com/nextcloud/talk/dagger/modules/RestModule.java
  app/src/main/java/com/nextcloud/talk/dagger/modules/ViewModelModule.kt
  app/src/main/java/com/nextcloud/talk/invitation/InvitationsActivity.kt
  app/src/main/java/com/nextcloud/talk/invitation/adapters/InvitationsAdapter.kt
  app/src/main/java/com/nextcloud/talk/invitation/data/Invitation.kt
  app/src/main/java/com/nextcloud/talk/invitation/data/InvitationActionModel.kt
  app/src/main/java/com/nextcloud/talk/invitation/data/InvitationsModel.kt
  app/src/main/java/com/nextcloud/talk/invitation/data/InvitationsRepository.kt
  app/src/main/java/com/nextcloud/talk/invitation/data/InvitationsRepositoryImpl.kt
  app/src/main/java/com/nextcloud/talk/invitation/viewmodels/InvitationsViewModel.kt
  app/src/main/java/com/nextcloud/talk/jobs/NotificationWorker.kt
  app/src/main/java/com/nextcloud/talk/models/json/invitation/Invitation.kt
  app/src/main/java/com/nextcloud/talk/models/json/invitation/InvitationOCS.kt
  app/src/main/java/com/nextcloud/talk/models/json/invitation/InvitationOverall.kt
  app/src/main/java/com/nextcloud/talk/openconversations/ListOpenConversationsActivity.kt
  app/src/main/java/com/nextcloud/talk/openconversations/adapters/OpenConversationsAdapter.kt
  app/src/main/java/com/nextcloud/talk/ui/dialog/ChooseAccountDialogFragment.java
  app/src/main/java/com/nextcloud/talk/ui/dialog/ChooseAccountShareToDialogFragment.kt
  app/src/main/java/com/nextcloud/talk/utils/ApiUtils.java
  app/src/main/java/com/nextcloud/talk/utils/bundle/BundleKeys.kt
  app/src/main/res/drawable/baseline_notifications_24.xml
  app/src/main/res/layout/account_item.xml
  app/src/main/res/layout/activity_conversations.xml
  app/src/main/res/layout/activity_invitations.xml
  app/src/main/res/layout/federated_invitation_hint.xml
  app/src/main/res/layout/rv_item_invitation.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
  scripts/analysis/lint-results.txt
Labels: 3. to review, feature: 🌐 federation

#3666 webRtc v121.6167.0 followup
  app/src/main/java/com/nextcloud/talk/activities/CallActivity.kt
  app/src/main/java/com/nextcloud/talk/application/NextcloudTalkApplication.kt
  app/src/main/java/com/nextcloud/talk/jobs/NotificationWorker.kt
  app/src/main/java/com/nextcloud/talk/webrtc/PeerConnectionWrapper.java
  app/src/main/java/com/nextcloud/talk/webrtc/WebRTCUtils.java
Labels: 3. to review, backport-request

#3630 Preparing for federation - Developing data layer for chats
  app/src/main/java/com/nextcloud/talk/chat/ChatActivity.kt
  app/src/main/java/com/nextcloud/talk/chat/data/ChatRepository.kt
  app/src/main/java/com/nextcloud/talk/chat/data/network/NetworkChatRepositoryImpl.kt
  app/src/main/java/com/nextcloud/talk/chat/viewmodels/ChatViewModel.kt
  app/src/main/java/com/nextcloud/talk/dagger/modules/RepositoryModule.kt
  app/src/main/java/com/nextcloud/talk/models/json/chat/ChatUtils.kt
Labels: 3. to review, feature: 🗨️ chat, feature: 🌐 federation
