Repository nextcloud/talk-android, pull requests merged in 2024-12, with the labels that each got.

#4502 Fix formatting
  app/src/main/java/com/nextcloud/talk/activities/CallActivity.kt
  app/src/main/java/com/nextcloud/talk/adapters/items/ConversationItem.kt
  app/src/main/java/com/nextcloud/talk/adapters/items/ParticipantItem.kt
  app/src/main/java/com/nextcloud/talk/adapters/messages/IncomingDeckCardViewHolder.kt
  app/src/main/java/com/nextcloud/talk/adapters/messages/IncomingLinkPreviewMessageViewHolder.kt
  app/src/main/java/com/nextcloud/talk/adapters/messages/IncomingLocationMessageViewHolder.kt
  app/src/main/java/com/nextcloud/talk/adapters/messages/IncomingPollMessageViewHolder.kt
  app/src/main/java/com/nextcloud/talk/adapters/messages/IncomingTextMessageViewHolder.kt
  app/src/main/java/com/nextcloud/talk/adapters/messages/IncomingVoiceMessageViewHolder.kt
  app/src/main/java/com/nextcloud/talk/adapters/messages/TemporaryMessageViewHolder.kt
  app/src/main/java/com/nextcloud/talk/chat/data/network/OfflineFirstChatRepository.kt
  app/src/main/java/com/nextcloud/talk/utils/ChatMessageUtils.kt
  app/src/main/java/com/nextcloud/talk/utils/DisplayUtils.kt
  app/src/main/java/com/nextcloud/talk/utils/preferences/AppPreferencesImpl.kt
  detekt.yml
  scripts/analysis/lint-results.txt
Labels: 3. to review, technical debt

#4505 Update avatar icons
  app/src/main/res/drawable-night/ic_circular_group.xml
  app/src/main/res/drawable-night/ic_circular_link.xml
  app/src/main/res/drawable-night/ic_circular_mail.xml
  app/src/main/res/drawable/ic_avatar_link.xml
  app/src/main/res/drawable/ic_avatar_mail.xml
  app/src/main/res/drawable/ic_circular_group.xml
  app/src/main/res/drawable/ic_circular_link.xml
  app/src/main/res/drawable/ic_circular_mail.xml
  drawable_resources/other/circular_group.svg
  drawable_resources/other/circular_group.svg.license
  drawable_resources/other/circular_link.svg
  drawable_resources/other/circular_link.svg.license
  drawable_resources/other/circular_mail.svg
  drawable_resources/other/circular_mail.svg.license
Labels: design, 3. to review

#4482 Add playback speed control to voice messages
  app/src/main/java/com/nextcloud/talk/adapters/messages/IncomingVoiceMessageViewHolder.kt
  app/src/main/java/com/nextcloud/talk/adapters/messages/OutcomingVoiceMessageViewHolder.kt
  app/src/main/java/com/nextcloud/talk/adapters/messages/VoiceMessageInterface.kt
  app/src/main/java/com/nextcloud/talk/chat/ChatActivity.kt
  app/src/main/java/com/nextcloud/talk/chat/viewmodels/ChatViewModel.kt
  app/src/main/java/com/nextcloud/talk/chat/viewmodels/MessageInputViewModel.kt
  app/src/main/java/com/nextcloud/talk/ui/PlaybackSpeedControl.kt
  app/src/main/java/com/nextcloud/talk/utils/preferences/AppPreferences.java
  app/src/main/java/com/nextcloud/talk/utils/preferences/AppPreferencesImpl.kt
  app/src/main/res/layout/fragment_message_input_voice_recording.xml
  app/src/main/res/layout/item_custom_incoming_voice_message.xml
  app/src/main/res/layout/item_custom_outcoming_voice_message.xml
  app/src/main/res/values/strings.xml
  app/src/test/java/com/nextcloud/talk/utils/ParticipantPermissionsTest.kt
Labels: enhancement, 3. to review

#4506 Add public and federated room badge
  app/src/main/java/com/nextcloud/talk/adapters/items/ConversationItem.kt
  app/src/main/res/drawable/cutout_circle.xml
  app/src/main/res/drawable/ic_avatar_federation.xml
  app/src/main/res/layout/rv_item_conversation_with_last_message.xml
  app/src/main/res/values/strings.xml
Labels: enhancement, design, 3. to review

#4389 User now knows if no offline messages are saved when entering a conversation
  app/src/main/java/com/nextcloud/talk/chat/ChatActivity.kt
  app/src/main/java/com/nextcloud/talk/chat/data/ChatMessageRepository.kt
  app/src/main/java/com/nextcloud/talk/chat/data/network/OfflineFirstChatRepository.kt
  app/src/main/java/com/nextcloud/talk/chat/viewmodels/ChatViewModel.kt
  app/src/main/res/layout/activity_chat.xml
  app/src/main/res/layout/no_saved_messages_view.xml
  app/src/main/res/values/strings.xml
Labels: 3. to review, backport-request

#4515 add changelog entries
  CHANGELOG.md
Labels: 3. to review

#4519 Improve detekt score
  app/src/main/java/com/nextcloud/talk/activities/CallActivity.kt
  app/src/main/java/com/nextcloud/talk/adapters/items/ContactItem.kt
  app/src/main/java/com/nextcloud/talk/adapters/items/MentionAutocompleteItem.kt
  app/src/main/java/com/nextcloud/talk/adapters/messages/IncomingDeckCardViewHolder.kt
  app/src/main/java/com/nextcloud/talk/adapters/messages/IncomingLinkPreviewMessageViewHolder.kt
  app/src/main/java/com/nextcloud/talk/adapters/messages/IncomingLocationMessageViewHolder.kt
  app/src/main/java/com/nextcloud/talk/adapters/messages/IncomingPollMessageViewHolder.kt
  app/src/main/java/com/nextcloud/talk/adapters/messages/IncomingTextMessageViewHolder.kt
  app/src/main/java/com/nextcloud/talk/adapters/messages/IncomingVoiceMessageViewHolder.kt
  app/src/main/java/com/nextcloud/talk/adapters/messages/OutcomingDeckCardViewHolder.kt
  app/src/main/java/com/nextcloud/talk/adapters/messages/OutcomingLinkPreviewMessageViewHolder.kt
  app/src/main/java/com/nextcloud/talk/adapters/messages/OutcomingLocationMessageViewHolder.kt
  app/src/main/java/com/nextcloud/talk/adapters/messages/OutcomingPollMessageViewHolder.kt
  app/src/main/java/com/nextcloud/talk/adapters/messages/OutcomingTextMessageViewHolder.kt
  app/src/main/java/com/nextcloud/talk/adapters/messages/OutcomingVoiceMessageViewHolder.kt
  app/src/main/java/com/nextcloud/talk/adapters/messages/TemporaryMessageViewHolder.kt
  app/src/main/java/com/nextcloud/talk/chat/ChatActivity.kt
  app/src/main/java/com/nextcloud/talk/chat/MessageInputFragment.kt
  app/src/main/java/com/nextcloud/talk/chat/data/network/OfflineFirstChatRepository.kt
  app/src/main/java/com/nextcloud/talk/contacts/ContactsViewModel.kt
  app/src/main/java/com/nextcloud/talk/conversationcreation/ConversationCreationViewModel.kt
  app/src/main/java/com/nextcloud/talk/conversationinfo/viewmodel/ConversationInfoViewModel.kt
  app/src/main/java/com/nextcloud/talk/conversationinfoedit/viewmodel/ConversationInfoEditViewModel.kt
  app/src/main/java/com/nextcloud/talk/conversationlist/ConversationsListActivity.kt
  app/src/main/java/com/nextcloud/talk/conversationlist/data/network/OfflineFirstConversationsRepository.kt
  app/src/main/java/com/nextcloud/talk/data/source/local/converters/ArrayListConverter.kt
  app/src/main/java/com/nextcloud/talk/jobs/LeaveConversationWorker.kt
  app/src/main/java/com/nextcloud/talk/jobs/SaveFileToStorageWorker.kt
  app/src/main/java/com/nextcloud/talk/settings/SettingsActivity.kt
  app/src/main/java/com/nextcloud/talk/ui/dialog/ConversationsListBottomDialog.kt
  app/src/main/java/com/nextcloud/talk/utils/DisplayUtils.kt
  app/src/main/java/com/nextcloud/talk/utils/PushUtils.kt
  app/src/main/java/com/nextcloud/talk/utils/preferences/AppPreferencesImpl.kt
  app/src/main/java/com/nextcloud/talk/utils/preferences/preferencestorage/DatabaseStorageModule.kt
  app/src/test/java/com/nextcloud/talk/contacts/repository/FakeRepositoryError.kt
  detekt.yml
Labels: 3. to review, technical debt

#4527 Lower detekt score
  app/src/main/java/com/nextcloud/talk/account/ServerSelectionActivity.kt
  app/src/main/java/com/nextcloud/talk/account/WebViewLoginActivity.kt
  app/src/main/java/com/nextcloud/talk/activities/CallActivity.kt
  app/src/main/java/com/nextcloud/talk/adapters/items/ContactItem.kt
  app/src/main/java/com/nextcloud/talk/adapters/items/MentionAutocompleteItem.kt
  app/src/main/java/com/nextcloud/talk/adapters/messages/IncomingDeckCardViewHolder.kt
  app/src/main/java/com/nextcloud/talk/adapters/messages/IncomingLinkPreviewMessageViewHolder.kt
  app/src/main/java/com/nextcloud/talk/adapters/messages/IncomingLocationMessageViewHolder.kt
  app/src/main/java/com/nextcloud/talk/adapters/messages/IncomingPollMessageViewHolder.kt
  app/src/main/java/com/nextcloud/talk/adapters/messages/IncomingTextMessageViewHolder.kt
  app/src/main/java/com/nextcloud/talk/adapters/messages/IncomingVoiceMessageViewHolder.kt
  app/src/main/java/com/nextcloud/talk/adapters/messages/OutcomingDeckCardViewHolder.kt
  app/src/main/java/com/nextcloud/talk/data/source/local/Migrations.kt
  app/src/main/java/com/nextcloud/talk/diagnose/DiagnoseActivity.kt
  app/src/main/java/com/nextcloud/talk/jobs/SaveFileToStorageWorker.kt
  app/src/main/java/com/nextcloud/talk/location/LocationPickerActivity.kt
  app/src/main/java/com/nextcloud/talk/models/json/converters/EnumSystemMessageTypeConverter.kt
  app/src/main/java/com/nextcloud/talk/settings/SettingsActivity.kt
  app/src/main/java/com/nextcloud/talk/ui/dialog/MessageActionsDialog.kt
  app/src/main/java/com/nextcloud/talk/ui/theme/TalkSpecificViewThemeUtils.kt
  app/src/main/java/com/nextcloud/talk/utils/preferences/preferencestorage/DatabaseStorageModule.kt
  app/src/test/java/com/nextcloud/talk/json/ConversationConversionTest.kt
  detekt.yml
Labels: 3. to review, technical debt, backport-request

#4493 display conversation avatar for open conversations
  app/src/main/java/com/nextcloud/talk/adapters/messages/IncomingDeckCardViewHolder.kt
  app/src/main/java/com/nextcloud/talk/openconversations/ListOpenConversationsActivity.kt
  app/src/main/java/com/nextcloud/talk/openconversations/adapters/OpenConversationsAdapter.kt
  app/src/main/java/com/nextcloud/talk/openconversations/data/JoinConversationModel.kt
  app/src/main/java/com/nextcloud/talk/openconversations/data/OpenConversation.kt
  app/src/main/java/com/nextcloud/talk/openconversations/data/OpenConversationsModel.kt
  app/src/main/java/com/nextcloud/talk/openconversations/data/OpenConversationsRepository.kt
  app/src/main/java/com/nextcloud/talk/openconversations/data/OpenConversationsRepositoryImpl.kt
  app/src/main/java/com/nextcloud/talk/openconversations/viewmodels/OpenConversationsViewModel.kt
  scripts/analysis/lint-results.txt
Labels: 3. to review, backport-request

#4522 remove hilt dependency
  app/build.gradle
  build.gradle
Labels: 3. to review

#4525 Fixed Message draft overlayed icon bug
  app/src/main/java/com/nextcloud/talk/chat/MessageInputFragment.kt
Labels: 3. to review, backport-request

#4542 update notification checklist
  docs/grantNotificationPermissionAfterInstall.png
  docs/grantNotificationPermissionAfterInstall.png.license
  docs/ignoreBatteryOptimizationDialog.png
  docs/ignoreBatteryOptimizationDialog.png.license
  docs/ignoreBatteryOptimizationSelectAllApps.png
  docs/ignoreBatteryOptimizationSelectAllApps.png.license
  docs/ignoreBatteryOptimizationTurnOffSwitch.png
  docs/ignoreBatteryOptimizationTurnOffSwitch.png.license
  docs/notificationSettingsExample.png
  docs/notificationSettingsExample.png.license
  docs/notifications.md
  docs/notificationsNotSetUpCorrectlyWarning.png
  docs/notificationsNotSetUpCorrectlyWarning.png.license
Labels: 3. to review

#4497 Add clear icon for search view in open conversations
  app/src/main/java/com/nextcloud/talk/openconversations/ListOpenConversationsActivity.kt
  app/src/main/res/layout/activity_open_conversations.xml
Labels: 3. to review

#4546 Set remainder for messages in federated conversation
  app/src/main/java/com/nextcloud/talk/ui/dialog/MessageActionsDialog.kt
Labels: 3. to review

#4544 detekt improvements
  app/src/main/java/com/nextcloud/talk/adapters/messages/OutcomingTextMessageViewHolder.kt
  app/src/main/java/com/nextcloud/talk/adapters/messages/OutcomingVoiceMessageViewHolder.kt
  app/src/main/java/com/nextcloud/talk/adapters/messages/SystemMessageViewHolder.kt
  app/src/main/java/com/nextcloud/talk/chat/ChatActivity.kt
  app/src/main/java/com/nextcloud/talk/chat/MessageInputFragment.kt
  app/src/main/java/com/nextcloud/talk/chat/data/network/OfflineFirstChatRepository.kt
  app/src/main/java/com/nextcloud/talk/conversationinfo/ConversationInfoActivity.kt
  app/src/main/java/com/nextcloud/talk/conversationinfoedit/ConversationInfoEditActivity.kt
  app/src/main/java/com/nextcloud/talk/conversationlist/ConversationsListActivity.kt
  app/src/main/java/com/nextcloud/talk/diagnose/DiagnoseActivity.kt
  app/src/main/java/com/nextcloud/talk/jobs/ContactAddressBookWorker.kt
  app/src/main/java/com/nextcloud/talk/jobs/NotificationWorker.kt
  app/src/main/java/com/nextcloud/talk/jobs/SaveFileToStorageWorker.kt
  app/src/main/java/com/nextcloud/talk/jobs/UploadAndShareFilesWorker.kt
  app/src/main/java/com/nextcloud/talk/utils/PushUtils.kt
  detekt.yml
  scripts/analysis/lint-results.txt
Labels: 3. to review, technical debt, backport-request

#4521 Out of office
  app/src/main/java/com/nextcloud/talk/api/NcApiCoroutines.kt
  app/src/main/java/com/nextcloud/talk/chat/ChatActivity.kt
  app/src/main/java/com/nextcloud/talk/chat/data/network/ChatNetworkDataSource.kt
  app/src/main/java/com/nextcloud/talk/chat/data/network/RetrofitChatNetwork.kt
  app/src/main/java/com/nextcloud/talk/chat/viewmodels/ChatViewModel.kt
  app/src/main/java/com/nextcloud/talk/dagger/modules/RepositoryModule.kt
  app/src/main/java/com/nextcloud/talk/models/json/userAbsence/UserAbsenceData.kt
  app/src/main/java/com/nextcloud/talk/models/json/userAbsence/UserAbsenceOCS.kt
  app/src/main/java/com/nextcloud/talk/models/json/userAbsence/UserAbsenceOverall.kt
  app/src/main/java/com/nextcloud/talk/utils/ApiUtils.kt
  app/src/main/java/com/nextcloud/talk/utils/DateUtils.kt
  app/src/main/res/layout/activity_chat.xml
  app/src/main/res/layout/out_of_office_view.xml
  app/src/main/res/values/strings.xml
Labels: 3. to review

#4549 Auto play consecutive audio messages, prefetch audio messages, show fetched audio durations, temporarily mark as listened audio messages, fixed a bug to listen last second of audio message
  LICENSES/CC-BY-4.0.txt
  REUSE.toml
  app/src/main/java/com/nextcloud/talk/adapters/messages/IncomingPreviewMessageViewHolder.java
  app/src/main/java/com/nextcloud/talk/adapters/messages/IncomingVoiceMessageViewHolder.kt
  app/src/main/java/com/nextcloud/talk/adapters/messages/OutcomingPreviewMessageViewHolder.java
  app/src/main/java/com/nextcloud/talk/adapters/messages/OutcomingVoiceMessageViewHolder.kt
  app/src/main/java/com/nextcloud/talk/chat/ChatActivity.kt
  app/src/main/java/com/nextcloud/talk/chat/data/model/ChatMessage.kt
  app/src/main/java/com/nextcloud/talk/ui/theme/TalkSpecificViewThemeUtils.kt
  app/src/main/res/raw/next_voice_message_doodle.ogg
  app/src/main/res/values-night/colors.xml
  app/src/main/res/values/colors.xml
Labels: enhancement, 3. to review

#4566 fix(ktlint): correct code formatting
  app/src/main/java/com/nextcloud/talk/chat/ChatActivity.kt
Labels: bug, 3. to review

#4568 chore(CI): Updating reuse.yml workflow from template
  .github/workflows/reuse.yml
Labels: dependencies
