Repository nextcloud/talk-android, pull requests merged in 2024-05, with the labels that each got.

#3901 Set taskAffinity to empty value on application level
  app/src/main/AndroidManifest.xml
Labels: backport-request

#3900 set light or dark bar colors for login screens instead primary color
  app/src/main/java/com/nextcloud/talk/account/AccountVerificationActivity.kt
  app/src/main/java/com/nextcloud/talk/account/ServerSelectionActivity.kt
  app/src/main/java/com/nextcloud/talk/account/SwitchAccountActivity.kt
  app/src/main/java/com/nextcloud/talk/account/WebViewLoginActivity.kt
  app/src/main/java/com/nextcloud/talk/activities/BaseActivity.kt
Labels: 3. to review

#3908 Show description in open conversation list
  app/src/main/java/com/nextcloud/talk/chat/ChatActivity.kt
  app/src/main/java/com/nextcloud/talk/openconversations/adapters/OpenConversationsAdapter.kt
  app/src/main/java/com/nextcloud/talk/openconversations/data/OpenConversation.kt
  app/src/main/java/com/nextcloud/talk/openconversations/data/OpenConversationsRepositoryImpl.kt
  app/src/main/res/layout/activity_open_conversations.xml
  app/src/main/res/layout/rv_item_open_conversation.xml
  app/src/main/res/values/dimens.xml
Labels: 3. to review

#3909 fix unread message behavior
  app/src/main/java/com/nextcloud/talk/chat/ChatActivity.kt
Labels: backport-request

#3918 fix to not set clipboard text repeatedly
  app/src/main/java/com/nextcloud/talk/chat/ChatActivity.kt
Labels: 3. to review, backport-request

#3932 use notification logo from separate xml file
  app/src/main/java/com/nextcloud/talk/jobs/NotificationWorker.kt
  app/src/main/res/drawable/ic_notification.xml
Labels: 3. to review, backport-request

#3922 Bugfix/3669/fix to open preview links in files app
  app/src/main/java/com/nextcloud/talk/adapters/messages/IncomingLinkPreviewMessageViewHolder.kt
  app/src/main/java/com/nextcloud/talk/adapters/messages/OutcomingLinkPreviewMessageViewHolder.kt
  app/src/main/java/com/nextcloud/talk/utils/UriUtils.kt
Labels: backport-request

#3923 open internal links for files app from any screen + open talk links inside the app
  app/src/main/java/com/nextcloud/talk/activities/BaseActivity.kt
  app/src/main/java/com/nextcloud/talk/activities/CallActivity.kt
  app/src/main/java/com/nextcloud/talk/chat/ChatActivity.kt
  app/src/main/java/com/nextcloud/talk/conversationinfo/ConversationInfoActivity.kt
  app/src/main/java/com/nextcloud/talk/conversationinfoedit/ConversationInfoEditActivity.kt
  app/src/main/java/com/nextcloud/talk/diagnose/DiagnoseActivity.kt
  app/src/main/java/com/nextcloud/talk/invitation/InvitationsActivity.kt
  app/src/main/java/com/nextcloud/talk/messagesearch/MessageSearchActivity.kt
  app/src/main/java/com/nextcloud/talk/openconversations/ListOpenConversationsActivity.kt
  app/src/main/java/com/nextcloud/talk/settings/SettingsActivity.kt
  app/src/main/java/com/nextcloud/talk/shareditems/activities/SharedItemsActivity.kt
  app/src/main/java/com/nextcloud/talk/utils/UriUtils.kt
Labels: 3. to review
