Repository nextcloud/talk-android, pull requests merged in 2024-01, with the labels that each got.

#3549 chore: update workflows from templates
  .github/workflows/pr-feedback.yml
Labels: 3. to review, dependencies, automated

#3559 Cursor position is saved in message drafts
  app/src/main/java/com/nextcloud/talk/chat/ChatActivity.kt
Labels: 3. to review, feature: 🗨️ chat

#3563 Cancel upload from notification
  app/src/main/java/com/nextcloud/talk/jobs/UploadAndShareFilesWorker.kt
  app/src/main/java/com/nextcloud/talk/upload/chunked/ChunkedFileUploader.kt
  app/src/main/res/drawable/ic_cancel_white_24dp.xml
Labels: enhancement, 3. to review, feature: 🔔 notifications, feature: 🤝 sharing

#3594 Add dependency checksums and signing key information
  .gitignore
  gradle.properties
  gradle/verification-keyring.keys
  gradle/verification-metadata.xml
Labels: 3. to review, technical debt, feature: 🏗️ CI

#3533 🤖Android 1️⃣4️⃣
  app/build.gradle
  app/lint.xml
  app/src/gplay/AndroidManifest.xml
  app/src/main/java/com/nextcloud/talk/activities/CallActivity.kt
  app/src/main/java/com/nextcloud/talk/utils/ContextExtensions.kt
  app/src/main/java/com/nextcloud/talk/utils/ReceiverFlag.kt
  app/src/main/java/com/nextcloud/talk/webrtc/WebRtcAudioManager.java
  app/src/main/java/com/nextcloud/talk/webrtc/WebRtcBluetoothManager.java
  scripts/analysis/lint-results.txt
Labels: 3. to review, technical debt
