Repository nextcloud/talk-android, pull requests merged in 2024-11, with the labels that each got.

#4390 fix messages not shown + improve unread marker behavior
  app/src/main/java/com/nextcloud/talk/adapters/messages/UnreadNoticeMessageViewHolder.java
  app/src/main/java/com/nextcloud/talk/chat/ChatActivity.kt
  app/src/main/java/com/nextcloud/talk/chat/data/ChatMessageRepository.kt
  app/src/main/java/com/nextcloud/talk/chat/data/network/OfflineFirstChatRepository.kt
  app/src/main/res/layout/activity_chat.xml
Labels: 3. to review, backport-request

#4360 Last moderator should not leave the room
  app/src/main/java/com/nextcloud/talk/conversationinfo/ConversationInfoActivity.kt
  app/src/main/java/com/nextcloud/talk/jobs/LeaveConversationWorker.java
  app/src/main/java/com/nextcloud/talk/jobs/LeaveConversationWorker.kt
  app/src/main/java/com/nextcloud/talk/ui/dialog/ConversationsListBottomDialog.kt
  app/src/main/res/values/strings.xml
Labels: 3. to review, backport-request

#4417 Fix DB migration 11 to 12
  app/schemas/com.nextcloud.talk.data.source.local.TalkDatabase/11.json
  app/schemas/com.nextcloud.talk.data.source.local.TalkDatabase/12.json
  app/src/main/java/com/nextcloud/talk/data/source/local/Migrations.kt
Labels: 3. to review

#4408 Make messages in 'Note To Self' chat room take full available screen width
  app/src/main/java/com/nextcloud/talk/adapters/messages/AdjustableMessageHolderInterface.kt
  app/src/main/java/com/nextcloud/talk/adapters/messages/OutcomingDeckCardViewHolder.kt
  app/src/main/java/com/nextcloud/talk/adapters/messages/OutcomingLinkPreviewMessageViewHolder.kt
  app/src/main/java/com/nextcloud/talk/adapters/messages/OutcomingLocationMessageViewHolder.kt
  app/src/main/java/com/nextcloud/talk/adapters/messages/OutcomingTextMessageViewHolder.kt
  app/src/main/java/com/nextcloud/talk/adapters/messages/OutcomingVoiceMessageViewHolder.kt
  app/src/main/java/com/nextcloud/talk/adapters/messages/TalkMessagesListAdapter.java
  app/src/main/java/com/nextcloud/talk/call/CallParticipantList.java
  app/src/main/java/com/nextcloud/talk/chat/viewmodels/ChatViewModel.kt
  app/src/main/java/com/nextcloud/talk/presenters/MentionAutocompletePresenter.java
  app/src/main/java/com/nextcloud/talk/ui/dialog/ChooseAccountDialogFragment.java
  app/src/main/java/com/nextcloud/talk/ui/dialog/MessageActionsDialog.kt
  detekt.yml
Labels: enhancement, 3. to review

#4386 Add support for all parameter in leave call endpoint
  app/src/main/java/com/nextcloud/talk/activities/CallActivity.kt
  app/src/main/java/com/nextcloud/talk/api/NcApi.java
  app/src/main/java/com/nextcloud/talk/callnotification/CallNotificationActivity.kt
  app/src/main/java/com/nextcloud/talk/chat/ChatActivity.kt
  app/src/main/java/com/nextcloud/talk/jobs/NotificationWorker.kt
  app/src/main/res/layout/call_activity.xml
  app/src/main/res/values/strings.xml
Labels: 3. to review, backport-request

#4442 fix crash when getting previousChatMessage
  app/src/main/java/com/nextcloud/talk/chat/ChatActivity.kt
Labels: 3. to review

#4448 Bugfix/noid/fix websocket connection for chat
  app/src/main/java/com/nextcloud/talk/chat/ChatActivity.kt
  app/src/main/java/com/nextcloud/talk/webrtc/WebSocketInstance.kt
Labels: 3. to review

#4436 fix to provide all call emojis
  app/src/main/java/com/nextcloud/talk/ui/dialog/MoreCallActionsDialog.kt
  app/src/main/res/layout/dialog_more_call_actions.xml
Labels: 3. to review

#4428 Lock room
  app/src/main/java/com/nextcloud/talk/api/NcApi.java
  app/src/main/java/com/nextcloud/talk/conversationinfo/ConversationInfoActivity.kt
  app/src/main/java/com/nextcloud/talk/conversationinfo/viewmodel/ConversationInfoViewModel.kt
  app/src/main/java/com/nextcloud/talk/repositories/conversations/ConversationsRepository.kt
  app/src/main/java/com/nextcloud/talk/repositories/conversations/ConversationsRepositoryImpl.kt
  app/src/main/java/com/nextcloud/talk/utils/ApiUtils.kt
  app/src/main/java/com/nextcloud/talk/utils/ConversationUtils.kt
  app/src/main/res/layout/activity_conversation_info.xml
  app/src/main/res/values/strings.xml
Labels: 3. to review

#4392 Restore user status
  app/src/main/java/com/nextcloud/talk/adapters/PredefinedStatusClickListener.kt
  app/src/main/java/com/nextcloud/talk/adapters/PredefinedStatusListAdapter.kt
  app/src/main/java/com/nextcloud/talk/adapters/PredefinedStatusViewHolder.kt
  app/src/main/java/com/nextcloud/talk/api/NcApi.java
  app/src/main/java/com/nextcloud/talk/models/json/capabilities/UserStatusCapability.kt
  app/src/main/java/com/nextcloud/talk/models/json/status/predefined/PredefinedStatus.kt
  app/src/main/java/com/nextcloud/talk/ui/dialog/SetStatusDialogFragment.kt
  app/src/main/java/com/nextcloud/talk/utils/ApiUtils.kt
  app/src/main/java/com/nextcloud/talk/utils/CapabilitiesUtil.kt
  app/src/main/res/layout/dialog_set_status.xml
  app/src/main/res/layout/predefined_status.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: 3. to review

#4458 [l10n] Change apostrophe
  app/src/main/res/values/strings.xml
Labels: backport-request

#4451 fix NPE currentConversation!!.internalId
  app/src/main/java/com/nextcloud/talk/chat/MessageInputFragment.kt
Labels: 3. to review

#4437 Migrating Rxjava to coroutines #1
  app/src/main/java/com/nextcloud/talk/api/NcApi.java
  app/src/main/java/com/nextcloud/talk/api/NcApiCoroutines.kt
  app/src/main/java/com/nextcloud/talk/settings/SettingsActivity.kt
Labels: 3. to review

#4446 Migrate Rxjava to coroutines #2
  app/src/main/java/com/nextcloud/talk/api/NcApi.java
  app/src/main/java/com/nextcloud/talk/api/NcApiCoroutines.kt
  app/src/main/java/com/nextcloud/talk/conversationcreation/ConversationCreationRepositoryImpl.kt
  app/src/main/java/com/nextcloud/talk/conversationinfo/ConversationInfoActivity.kt
  app/src/main/java/com/nextcloud/talk/conversationinfo/GuestAccessHelper.kt
  app/src/main/java/com/nextcloud/talk/conversationinfo/viewmodel/ConversationInfoViewModel.kt
  app/src/main/java/com/nextcloud/talk/repositories/conversations/ConversationsRepository.kt
  app/src/main/java/com/nextcloud/talk/repositories/conversations/ConversationsRepositoryImpl.kt
Labels: 3. to review

#4455 Migrate Rxjava to Coroutines
  app/src/main/java/com/nextcloud/talk/api/NcApi.java
  app/src/main/java/com/nextcloud/talk/api/NcApiCoroutines.kt
  app/src/main/java/com/nextcloud/talk/conversation/RenameConversationDialogFragment.kt
  app/src/main/java/com/nextcloud/talk/conversation/repository/ConversationRepository.kt
  app/src/main/java/com/nextcloud/talk/conversation/repository/ConversationRepositoryImpl.kt
  app/src/main/java/com/nextcloud/talk/conversation/viewmodel/RenameConversationViewModel.kt
  app/src/main/java/com/nextcloud/talk/conversationinfo/ConversationInfoActivity.kt
  app/src/main/java/com/nextcloud/talk/conversationinfo/viewmodel/ConversationInfoViewModel.kt
  app/src/main/java/com/nextcloud/talk/conversationinfoedit/ConversationInfoEditActivity.kt
  app/src/main/java/com/nextcloud/talk/conversationinfoedit/data/ConversationInfoEditRepository.kt
  app/src/main/java/com/nextcloud/talk/conversationinfoedit/data/ConversationInfoEditRepositoryImpl.kt
  app/src/main/java/com/nextcloud/talk/conversationinfoedit/viewmodel/ConversationInfoEditViewModel.kt
  app/src/main/java/com/nextcloud/talk/dagger/modules/RepositoryModule.kt
  app/src/main/java/com/nextcloud/talk/dagger/modules/ViewModelModule.kt
  app/src/main/java/com/nextcloud/talk/repositories/conversations/ConversationsRepository.kt
  app/src/main/java/com/nextcloud/talk/repositories/conversations/ConversationsRepositoryImpl.kt
Labels: 3. to review

#4467 docs: Align GitHub issue templates
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: 3. to review

#4423 Better call started indicator
  app/src/main/java/com/nextcloud/talk/adapters/messages/CallStartedViewHolder.kt
  app/src/main/java/com/nextcloud/talk/adapters/messages/TalkMessagesListAdapter.java
  app/src/main/java/com/nextcloud/talk/chat/ChatActivity.kt
  app/src/main/java/com/nextcloud/talk/chat/MessageInputFragment.kt
  app/src/main/java/com/nextcloud/talk/chat/viewmodels/MessageInputViewModel.kt
  app/src/main/res/drawable/ic_keyboard_arrow_up.xml
  app/src/main/res/layout/call_started_message.xml
  app/src/main/res/layout/fragment_message_input.xml
Labels: 3. to review

#4415 Disabling/Hiding features when offline
  app/src/main/java/com/nextcloud/talk/chat/ChatActivity.kt
  app/src/main/java/com/nextcloud/talk/chat/MessageInputFragment.kt
  app/src/main/java/com/nextcloud/talk/conversationlist/ConversationsListActivity.kt
  app/src/main/java/com/nextcloud/talk/data/network/NetworkMonitor.kt
  app/src/main/java/com/nextcloud/talk/data/network/NetworkMonitorImpl.kt
  app/src/main/java/com/nextcloud/talk/ui/dialog/ChooseAccountDialogFragment.java
  app/src/main/java/com/nextcloud/talk/ui/dialog/MessageActionsDialog.kt
Labels: 3. to review

#4461 Migrating from Rxjava to coroutines #4
  app/src/main/java/com/nextcloud/talk/api/NcApi.java
  app/src/main/java/com/nextcloud/talk/api/NcApiCoroutines.kt
  app/src/main/java/com/nextcloud/talk/conversationinfo/ConversationInfoActivity.kt
  app/src/main/java/com/nextcloud/talk/ui/dialog/ConversationsListBottomDialog.kt
  app/src/main/java/com/nextcloud/talk/utils/preferences/preferencestorage/DatabaseStorageModule.java
  app/src/main/java/com/nextcloud/talk/utils/preferences/preferencestorage/DatabaseStorageModule.kt
Labels: 3. to review

#4464 coroutine_5
  app/src/main/java/com/nextcloud/talk/api/NcApi.java
  app/src/main/java/com/nextcloud/talk/api/NcApiCoroutines.kt
  app/src/main/java/com/nextcloud/talk/chat/data/network/ChatNetworkDataSource.kt
  app/src/main/java/com/nextcloud/talk/chat/data/network/RetrofitChatNetwork.kt
  app/src/main/java/com/nextcloud/talk/conversationinfo/viewmodel/ConversationInfoViewModel.kt
  app/src/main/java/com/nextcloud/talk/repositories/conversations/ConversationsRepository.kt
  app/src/main/java/com/nextcloud/talk/repositories/conversations/ConversationsRepositoryImpl.kt
Labels: 3. to review

#4470 bump minSdkVersion to 26 and remove old checks
  app/build.gradle
  app/src/androidTest/java/com/nextcloud/talk/utils/VibrationUtilsTest.kt
  app/src/main/java/com/nextcloud/talk/activities/BaseActivity.kt
  app/src/main/java/com/nextcloud/talk/activities/CallActivity.kt
  app/src/main/java/com/nextcloud/talk/activities/CallBaseActivity.java
  app/src/main/java/com/nextcloud/talk/adapters/items/ContactItem.kt
  app/src/main/java/com/nextcloud/talk/adapters/items/ConversationItem.kt
  app/src/main/java/com/nextcloud/talk/adapters/items/MentionAutocompleteItem.kt
  app/src/main/java/com/nextcloud/talk/callnotification/CallNotificationActivity.kt
  app/src/main/java/com/nextcloud/talk/chat/data/io/AudioFocusRequestManager.kt
  app/src/main/java/com/nextcloud/talk/contacts/ContactsActivity.kt
  app/src/main/java/com/nextcloud/talk/conversationlist/ConversationsListActivity.kt
  app/src/main/java/com/nextcloud/talk/extensions/ImageViewExtensions.kt
  app/src/main/java/com/nextcloud/talk/jobs/AccountRemovalWorker.java
  app/src/main/java/com/nextcloud/talk/jobs/NotificationWorker.kt
  app/src/main/java/com/nextcloud/talk/location/GeocodingActivity.kt
  app/src/main/java/com/nextcloud/talk/location/LocationPickerActivity.kt
  app/src/main/java/com/nextcloud/talk/settings/SettingsActivity.kt
  app/src/main/java/com/nextcloud/talk/ui/theme/TalkSpecificViewThemeUtils.kt
  app/src/main/java/com/nextcloud/talk/upload/chunked/ChunkedFileUploader.kt
  app/src/main/java/com/nextcloud/talk/utils/DisplayUtils.kt
  app/src/main/java/com/nextcloud/talk/utils/FileUtils.kt
  app/src/main/java/com/nextcloud/talk/utils/ImageEmojiEditText.kt
  app/src/main/java/com/nextcloud/talk/utils/NotificationUtils.kt
  app/src/main/java/com/nextcloud/talk/utils/VibrationUtils.kt
Labels: 3. to review

#4476 Add permanent warning when notifications are not set up correctly
  app/src/main/java/com/nextcloud/talk/conversationlist/ConversationsListActivity.kt
  app/src/main/java/com/nextcloud/talk/settings/SettingsActivity.kt
  app/src/main/java/com/nextcloud/talk/utils/DrawableUtils.kt
  app/src/main/java/com/nextcloud/talk/utils/bundle/BundleKeys.kt
  app/src/main/java/com/nextcloud/talk/utils/preferences/AppPreferences.java
  app/src/main/java/com/nextcloud/talk/utils/preferences/AppPreferencesImpl.kt
  app/src/main/res/layout/activity_conversations.xml
  app/src/main/res/layout/activity_settings.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: 3. to review, backport-request
