Repository nextcloud/talk-android, pull requests merged in 2024-04, with the labels that each got.

#3789 Add SPDX header template
  .idea/copyright/Nextcloud_Talk___Android_Client.xml
  .idea/copyright/profiles_settings.xml
Labels: 3. to review, technical debt

#3790 Update devcontainer to jdk17
  .devcontainer/Dockerfile
  .devcontainer/README.md
Labels: technical debt

#3752 Use new Result APIs instead of startActivityForResult() and onActivityResult().
  app/src/main/java/com/nextcloud/talk/chat/ChatActivity.kt
  app/src/main/java/com/nextcloud/talk/conversationinfoedit/ConversationInfoEditActivity.kt
  app/src/main/java/com/nextcloud/talk/lock/LockedActivity.kt
  app/src/main/java/com/nextcloud/talk/profile/ProfileActivity.kt
  app/src/main/java/com/nextcloud/talk/utils/PickImage.kt
Labels: 3. to review

#3746 Fix message delay on send and delete
  app/src/main/java/com/nextcloud/talk/chat/ChatActivity.kt
  app/src/main/res/layout/dialog_message_actions.xml
Labels: 2. developing, backport-request, feature: 🗨️ chat

#3766 shows edit message view only when user edits a message
  app/src/main/java/com/nextcloud/talk/chat/ChatActivity.kt
  app/src/main/res/layout/activity_chat.xml
Labels: backport-request

#3768 Fix crash on sendStopTypingMessage
  app/src/main/java/com/nextcloud/talk/chat/ChatActivity.kt
Labels: backport-request

#3776 Network checks and show network error dialog
  app/src/main/java/com/nextcloud/talk/conversationlist/ConversationsListActivity.kt
  app/src/main/res/values/strings.xml
Labels: backport-request, feature: 📄 conversations

#3793 translate all boolean values in diagnosis screen
  app/src/main/java/com/nextcloud/talk/diagnose/DiagnoseActivity.kt
Labels: 3. to review, backport-request

#3801 avoid NPE when serverVersion is not known
  app/src/main/java/com/nextcloud/talk/account/ServerSelectionActivity.kt
  app/src/main/java/com/nextcloud/talk/conversationlist/ConversationsListActivity.kt
  app/src/main/java/com/nextcloud/talk/settings/SettingsActivity.kt
  app/src/main/java/com/nextcloud/talk/utils/CapabilitiesUtil.kt
Labels: backport-request

#3803 avoid NPE when context is not known when creating conversation
  app/src/main/java/com/nextcloud/talk/conversation/CreateConversationDialogFragment.kt
Labels: backport-request

#3823 avoid error when clicking on federated user
  app/src/main/java/com/nextcloud/talk/adapters/messages/IncomingLinkPreviewMessageViewHolder.kt
  app/src/main/java/com/nextcloud/talk/adapters/messages/IncomingLocationMessageViewHolder.kt
  app/src/main/java/com/nextcloud/talk/adapters/messages/IncomingPollMessageViewHolder.kt
  app/src/main/java/com/nextcloud/talk/adapters/messages/IncomingTextMessageViewHolder.kt
  app/src/main/java/com/nextcloud/talk/adapters/messages/IncomingVoiceMessageViewHolder.kt
  app/src/main/java/com/nextcloud/talk/adapters/messages/PreviewMessageViewHolder.kt
  app/src/main/java/com/nextcloud/talk/ui/bottom/sheet/ProfileBottomSheet.kt
  app/src/main/java/com/nextcloud/talk/utils/DisplayUtils.kt
Labels: 3. to review, backport-request

#3830 Bugfix/3315/fix empty call notification screen
  app/src/main/java/com/nextcloud/talk/activities/MainActivity.kt
  app/src/main/java/com/nextcloud/talk/callnotification/CallNotificationActivity.kt
  app/src/main/java/com/nextcloud/talk/callnotification/viewmodel/CallNotificationViewModel.kt
  app/src/main/java/com/nextcloud/talk/dagger/modules/ViewModelModule.kt
  app/src/main/java/com/nextcloud/talk/jobs/NotificationWorker.kt
  app/src/main/java/com/nextcloud/talk/jobs/UploadAndShareFilesWorker.kt
  app/src/main/java/com/nextcloud/talk/utils/bundle/BundleKeys.kt
  app/src/main/res/layout/call_notification_activity.xml
Labels: 3. to review, backport-request

#3842 fix to set ConversationType for "Note to self"
  app/src/main/java/com/nextcloud/talk/adapters/items/ConversationItem.kt
  app/src/main/java/com/nextcloud/talk/models/domain/ConversationModel.kt
  app/src/main/java/com/nextcloud/talk/models/json/conversations/Conversation.kt
  app/src/main/java/com/nextcloud/talk/models/json/converters/EnumRoomTypeConverter.java
  app/src/main/java/com/nextcloud/talk/utils/ConversationUtils.kt
Labels: 3. to review, backport-request

#3847 fix to show "Note to self" icon in conversation info
  app/src/main/java/com/nextcloud/talk/conversationinfo/ConversationInfoActivity.kt
Labels: 3. to review, backport-request

#3839 Fix onLoadMore not refreshing instantly
  app/src/main/java/com/nextcloud/talk/chat/ChatActivity.kt
Labels: 3. to review, backport-request

#3849 fix to open calls as voice only when user clicked on voice button
  app/src/main/java/com/nextcloud/talk/callnotification/CallNotificationActivity.kt
Labels: 3. to review, backport-request

#3868 rename classes called 'Magic*'
  app/src/main/java/com/nextcloud/talk/activities/BaseActivity.kt
  app/src/main/java/com/nextcloud/talk/callbacks/MentionAutocompleteCallback.java
  app/src/main/java/com/nextcloud/talk/chat/ChatActivity.kt
  app/src/main/java/com/nextcloud/talk/events/CertificateEvent.java
  app/src/main/java/com/nextcloud/talk/utils/CharPolicy.java
  app/src/main/java/com/nextcloud/talk/webrtc/PeerConnectionWrapper.java
  app/src/main/java/com/nextcloud/talk/webrtc/ProximitySensor.java
  app/src/main/java/com/nextcloud/talk/webrtc/WebRTCUtils.java
  app/src/main/java/com/nextcloud/talk/webrtc/WebRtcAudioManager.java
  app/src/main/java/com/nextcloud/talk/webrtc/WebRtcBluetoothManager.java
Labels: 3. to review

#3871 fix: Have correct SPDX license header for logo/trademarked items
  LICENSES/LicenseRef-NextcloudTrademarks.txt
  app/src/main/res/drawable/ic_launcher_foreground.xml
  app/src/main/res/drawable/ic_logo.xml
  app/src/main/res/drawable/ic_talk.xml
  app/src/qa/res/drawable/ic_launcher_foreground.xml
Labels: bug, 3. to review, backport-request

#3879 Updating pr-feedback.yml workflow from template
  .github/workflows/pr-feedback.yml
Labels: dependencies

#3878 fix visibility of conversation options
  app/src/main/java/com/nextcloud/talk/conversationinfo/ConversationInfoActivity.kt
Labels: 3. to review
