Repository nextcloud/talk-android, pull requests merged in 2025-01, with the labels that each got.

#4536 Improve handling of data channels
  app/src/main/java/com/nextcloud/talk/activities/CallActivity.kt
  app/src/main/java/com/nextcloud/talk/webrtc/PeerConnectionWrapper.java
  app/src/test/java/android/util/Log.java
  app/src/test/java/com/nextcloud/talk/webrtc/PeerConnectionWrapperTest.kt
Labels: bug, 3. to review, backport-request

#4569 Fix audio and video not received
  app/src/main/java/com/nextcloud/talk/activities/CallActivity.kt
Labels: bug, 3. to review, regression, backport-request, feature: ☎️ call

#4577 Migrate Gradle action
  .github/workflows/unit-tests.yml
Labels: 3. to review, technical debt, feature: 🏗️ CI

#4553 open .webm video files with internal player
  app/src/main/java/com/nextcloud/talk/utils/FileViewerUtils.kt
  app/src/main/java/com/nextcloud/talk/utils/Mimetype.kt
Labels: 3. to review, backport-request

#4558 Fix sending local state to other participants
  app/src/main/java/com/nextcloud/talk/activities/CallActivity.kt
  app/src/main/java/com/nextcloud/talk/call/LocalCallParticipantModel.java
  app/src/main/java/com/nextcloud/talk/call/LocalCallParticipantModelNotifier.java
  app/src/main/java/com/nextcloud/talk/call/LocalStateBroadcaster.java
  app/src/main/java/com/nextcloud/talk/call/LocalStateBroadcasterMcu.java
  app/src/main/java/com/nextcloud/talk/call/LocalStateBroadcasterNoMcu.java
  app/src/main/java/com/nextcloud/talk/call/MessageSender.java
  app/src/main/java/com/nextcloud/talk/call/MessageSenderMcu.java
  app/src/main/java/com/nextcloud/talk/call/MessageSenderNoMcu.java
  app/src/main/java/com/nextcloud/talk/call/MutableLocalCallParticipantModel.java
  app/src/main/java/com/nextcloud/talk/webrtc/PeerConnectionWrapper.java
  app/src/test/java/com/nextcloud/talk/call/LocalCallParticipantModelTest.kt
  app/src/test/java/com/nextcloud/talk/call/LocalStateBroadcasterMcuTest.kt
  app/src/test/java/com/nextcloud/talk/call/LocalStateBroadcasterNoMcuTest.kt
  app/src/test/java/com/nextcloud/talk/call/LocalStateBroadcasterTest.kt
  app/src/test/java/com/nextcloud/talk/call/MessageSenderMcuTest.kt
  app/src/test/java/com/nextcloud/talk/call/MessageSenderNoMcuTest.kt
  app/src/test/java/com/nextcloud/talk/call/MessageSenderTest.kt
Labels: bug, 3. to review, backport-request, feature: ☎️ call

#4551 show message send button when there is text in input message field
  app/src/main/java/com/nextcloud/talk/chat/MessageInputFragment.kt
Labels: backport-request

#4474 Replace Popup bubble with Material Button
  app/build.gradle
  app/src/main/java/com/nextcloud/talk/conversationlist/ConversationsListActivity.kt
  app/src/main/res/anim/popup_animation.xml
  app/src/main/res/layout/activity_conversations.xml
  scripts/analysis/lint-results.txt
Labels: 3. to review, backport-request

#4591 fix translation for polls_option_delete
  app/src/main/res/values/strings.xml
Labels: 3. to review, backport-request

#4552 Migrating away from java.util.Date to java.time - DateTimePickerFragment
  .idea/inspectionProfiles/ktlint.xml
  app/src/main/java/com/nextcloud/talk/chat/ChatActivity.kt
  app/src/main/java/com/nextcloud/talk/chat/viewmodels/ChatViewModel.kt
  app/src/main/java/com/nextcloud/talk/ui/dialog/DateTimeCompose.kt
  app/src/main/java/com/nextcloud/talk/ui/dialog/DateTimePickerFragment.kt
  app/src/main/res/layout/activity_chat.xml
  app/src/main/res/layout/dialog_date_time_picker.xml
  scripts/analysis/lint-results.txt
Labels: 3. to review

#4422 Feature/4378/add temporary messages while sending
  app/schemas/com.nextcloud.talk.data.source.local.TalkDatabase/13.json
  app/src/main/java/com/nextcloud/talk/adapters/messages/IncomingTextMessageViewHolder.kt
  app/src/main/java/com/nextcloud/talk/adapters/messages/OutcomingTextMessageViewHolder.kt
  app/src/main/java/com/nextcloud/talk/adapters/messages/TalkMessagesListAdapter.java
  app/src/main/java/com/nextcloud/talk/adapters/messages/TemporaryMessageInterface.kt
  app/src/main/java/com/nextcloud/talk/adapters/messages/TemporaryMessageViewHolder.kt
  app/src/main/java/com/nextcloud/talk/api/NcApi.java
  app/src/main/java/com/nextcloud/talk/api/NcApiCoroutines.kt
  app/src/main/java/com/nextcloud/talk/chat/ChatActivity.kt
  app/src/main/java/com/nextcloud/talk/chat/MessageInputFragment.kt
  app/src/main/java/com/nextcloud/talk/chat/data/ChatMessageRepository.kt
  app/src/main/java/com/nextcloud/talk/chat/data/model/ChatMessage.kt
  app/src/main/java/com/nextcloud/talk/chat/data/network/ChatNetworkDataSource.kt
  app/src/main/java/com/nextcloud/talk/chat/data/network/OfflineFirstChatRepository.kt
  app/src/main/java/com/nextcloud/talk/chat/data/network/RetrofitChatNetwork.kt
  app/src/main/java/com/nextcloud/talk/chat/viewmodels/ChatViewModel.kt
  app/src/main/java/com/nextcloud/talk/chat/viewmodels/MessageInputViewModel.kt
  app/src/main/java/com/nextcloud/talk/conversationlist/data/network/OfflineFirstConversationsRepository.kt
  app/src/main/java/com/nextcloud/talk/dagger/modules/RepositoryModule.kt
  app/src/main/java/com/nextcloud/talk/data/database/dao/ChatMessagesDao.kt
  app/src/main/java/com/nextcloud/talk/data/database/mappers/ChatMessageMapUtils.kt
  app/src/main/java/com/nextcloud/talk/data/database/model/ChatMessageEntity.kt
  app/src/main/java/com/nextcloud/talk/data/source/local/Migrations.kt
  app/src/main/java/com/nextcloud/talk/data/source/local/TalkDatabase.kt
  app/src/main/java/com/nextcloud/talk/extensions/LongFormatExtension.kt
  app/src/main/java/com/nextcloud/talk/jobs/AccountRemovalWorker.java
  app/src/main/java/com/nextcloud/talk/models/json/chat/ChatMessageJson.kt
  app/src/main/java/com/nextcloud/talk/receivers/DirectReplyReceiver.kt
  app/src/main/java/com/nextcloud/talk/ui/dialog/TempMessageActionsDialog.kt
  app/src/main/java/com/nextcloud/talk/utils/message/SendMessageUtils.kt
  app/src/main/java/com/nextcloud/talk/utils/preferences/AppPreferences.java
  app/src/main/java/com/nextcloud/talk/utils/preferences/AppPreferencesImpl.kt
  app/src/main/res/drawable/baseline_error_outline_24.xml
  app/src/main/res/drawable/baseline_report_problem_24.xml
  app/src/main/res/drawable/baseline_schedule_24.xml
  app/src/main/res/layout/dialog_temp_message_actions.xml
  app/src/main/res/layout/item_custom_outcoming_text_message.xml
  app/src/main/res/layout/item_temporary_message.xml
  app/src/main/res/values/strings.xml
  scripts/analysis/lint-results.txt
Labels: 3. to review, backport-request

#4204 Added option `Immediate` for passcode timeout.
  app/src/main/res/values-v28/arrays.xml
  app/src/main/res/values/arrays.xml
  app/src/main/res/values/strings.xml
Labels: 3. to review, feedback-requested

#4611 hopefully fix NPE for currentUser in addToConversationItems
  app/src/main/java/com/nextcloud/talk/conversationlist/ConversationsListActivity.kt
Labels: 3. to review, backport-request

#4598 fix TooManyRequestsException
  app/src/main/java/com/nextcloud/talk/adapters/messages/OutcomingTextMessageViewHolder.kt
  app/src/main/java/com/nextcloud/talk/chat/ChatActivity.kt
  app/src/main/java/com/nextcloud/talk/chat/data/network/OfflineFirstChatRepository.kt
  app/src/main/java/com/nextcloud/talk/conversationlist/ConversationsListActivity.kt
  app/src/main/java/com/nextcloud/talk/conversationlist/data/network/OfflineFirstConversationsRepository.kt
  app/src/main/java/com/nextcloud/talk/data/network/NetworkMonitor.kt
  app/src/main/java/com/nextcloud/talk/data/network/NetworkMonitorImpl.kt
  app/src/main/java/com/nextcloud/talk/ui/dialog/MessageActionsDialog.kt
  app/src/main/java/com/nextcloud/talk/ui/dialog/TempMessageActionsDialog.kt
Labels: 3. to review, backport-request

#4620 Fix reactions background
  app/src/main/java/com/nextcloud/talk/adapters/messages/OutcomingTextMessageViewHolder.kt
  app/src/main/java/com/nextcloud/talk/adapters/messages/PreviewMessageViewHolder.kt
  app/src/main/java/com/nextcloud/talk/adapters/messages/Reaction.kt
  app/src/main/java/com/nextcloud/talk/ui/theme/TalkSpecificViewThemeUtils.kt
  app/src/main/res/drawable/ic_mimetype_application_pdf.xml
  app/src/main/res/drawable/reaction_self_background.xml
  app/src/main/res/layout/reactions_inside_message.xml
  detekt.yml
Labels: bug, design, 3. to review

#4634 enable to select authentication cert in server selection screen
  app/src/main/res/values/setup.xml
Labels: 3. to review

#4627 Rework can leave/delete conversation
  app/src/main/java/com/nextcloud/talk/conversationinfo/ConversationInfoActivity.kt
Labels: 3. to review

#4630 no "unread messages" popup for invisible messages
  app/src/main/java/com/nextcloud/talk/chat/ChatActivity.kt
Labels: 3. to review

#4641 Bugfix/4605/fix duplicate messages
  app/src/main/java/com/nextcloud/talk/chat/ChatActivity.kt
  app/src/main/java/com/nextcloud/talk/chat/data/ChatMessageRepository.kt
  app/src/main/java/com/nextcloud/talk/chat/data/network/OfflineFirstChatRepository.kt
  app/src/main/java/com/nextcloud/talk/chat/viewmodels/ChatViewModel.kt
Labels: 3. to review

#4645 fix shimmer and "offlineNoMessages"-info handling
  app/src/main/java/com/nextcloud/talk/chat/ChatActivity.kt
  app/src/main/java/com/nextcloud/talk/chat/data/network/OfflineFirstChatRepository.kt
Labels: 3. to review

#4624 Follow up fixes for 'Archive Conversations
  app/src/main/java/com/nextcloud/talk/conversationinfo/ConversationInfoActivity.kt
  app/src/main/java/com/nextcloud/talk/conversationlist/ConversationsListActivity.kt
  app/src/main/java/com/nextcloud/talk/ui/dialog/ConversationsListBottomDialog.kt
  app/src/main/res/layout/activity_conversation_info.xml
  app/src/main/res/layout/activity_conversations.xml
  app/src/main/res/layout/dialog_conversation_operations.xml
  app/src/main/res/values/strings.xml
Labels: 3. to review

#4663 Message of type actorId "sample" should show talk logo avatar
  app/src/main/java/com/nextcloud/talk/utils/ChatMessageUtils.kt
Labels: 3. to review

#4659 Switched the "Close" and "Set" Buttons in the remind-me-later dialog
  app/src/main/java/com/nextcloud/talk/ui/dialog/DateTimeCompose.kt
Labels: 3. to review, backport-request

#4664 remove duplicated dependencies
  app/build.gradle
Labels: 3. to review
