Repository nextcloud/talk-android, pull requests merged in 2025-09, with the labels that each got.

#5277 don't group system messages over date separator
  app/src/main/java/com/nextcloud/talk/chat/ChatActivity.kt
Labels: 3. to review

#5330 Make thread icon dark/light aware
  app/src/main/res/layout/item_thread_title.xml
Labels: design, 3. to review

#5345 Feature/3074/improve threads5
  app/build.gradle
  app/src/main/java/com/nextcloud/talk/api/NcApiCoroutines.kt
  app/src/main/java/com/nextcloud/talk/chat/ChatActivity.kt
  app/src/main/java/com/nextcloud/talk/chat/OverflowMenu.kt
  app/src/main/java/com/nextcloud/talk/chat/data/network/ChatNetworkDataSource.kt
  app/src/main/java/com/nextcloud/talk/chat/data/network/RetrofitChatNetwork.kt
  app/src/main/java/com/nextcloud/talk/chat/viewmodels/ChatViewModel.kt
  app/src/main/java/com/nextcloud/talk/threadsoverview/data/ThreadsRepository.kt
  app/src/main/java/com/nextcloud/talk/threadsoverview/data/ThreadsRepositoryImpl.kt
  app/src/main/java/com/nextcloud/talk/utils/ApiUtils.kt
  app/src/main/res/drawable/outline_forum_24.xml
  app/src/main/res/drawable/outline_notifications_active_24.xml
  app/src/main/res/menu/menu_conversation.xml
  app/src/main/res/values/strings.xml
Labels: 3. to review, backport-request

#5342 Add busy status + split set status dialog
  app/src/main/java/com/nextcloud/talk/adapters/items/MentionAutocompleteItem.kt
  app/src/main/java/com/nextcloud/talk/adapters/items/ParticipantItem.kt
  app/src/main/java/com/nextcloud/talk/models/json/status/StatusType.kt
  app/src/main/java/com/nextcloud/talk/ui/StatusDrawable.java
  app/src/main/java/com/nextcloud/talk/ui/dialog/ChooseAccountDialogFragment.java
  app/src/main/java/com/nextcloud/talk/ui/dialog/OnlineStatusBottomDialogFragment.kt
  app/src/main/java/com/nextcloud/talk/ui/dialog/StatusMessageBottomDialogFragment.kt
  app/src/main/res/drawable/ic_check_circle_outlined.xml
  app/src/main/res/drawable/ic_user_status_busy.xml
  app/src/main/res/layout/dialog_choose_account.xml
  app/src/main/res/layout/dialog_set_online_status.xml
  app/src/main/res/layout/dialog_set_status_message.xml
  app/src/main/res/layout/predefined_status.xml
  app/src/main/res/values/strings.xml
Labels: 3. to review, backport-request

#5375 styled(threads): Align threads overview style with web UI
  app/src/main/java/com/nextcloud/talk/threadsoverview/components/ThreadRow.kt
Labels: design, 3. to review
