Repository nextcloud/talk-android, pull requests merged in 2025-06, with the labels that each got.

#5030 Fixes message timestamp color
  app/src/main/java/com/nextcloud/talk/adapters/messages/IncomingTextMessageViewHolder.kt
  app/src/main/java/com/nextcloud/talk/adapters/messages/OutcomingTextMessageViewHolder.kt
Labels: 3. to review

#5028 UI improvements to automatic conversation deletion information for event, sip and instant meetings conversation
  app/src/main/java/com/nextcloud/talk/chat/ChatActivity.kt
  app/src/main/res/layout/item_event_schedule.xml
  app/src/main/res/layout/remainder_to_delete_conversation.xml
Labels: 3. to review

#5050 ci(chksm): Add meta-data
  gradle/verification-keyring.keys
  gradle/verification-metadata.xml
Labels: 3. to review, technical debt, feature: CI 🏗️

#5032 Adding a short cut to note-to-self
  app/src/main/java/com/nextcloud/talk/account/WebViewLoginActivity.kt
  app/src/main/java/com/nextcloud/talk/bottomsheet/items/ListIconDialogAdapter.kt
  app/src/main/java/com/nextcloud/talk/chat/ChatActivity.kt
  app/src/main/java/com/nextcloud/talk/conversationlist/ConversationsListActivity.kt
  app/src/main/java/com/nextcloud/talk/fullscreenfile/FullScreenMediaActivity.kt
  app/src/main/java/com/nextcloud/talk/receivers/DirectReplyReceiver.kt
  app/src/main/java/com/nextcloud/talk/utils/bundle/BundleKeys.kt
  app/src/main/res/values/strings.xml
Labels: 3. to review

#5063 fix wrong plurals implementation
  app/src/main/java/com/nextcloud/talk/chat/ChatActivity.kt
  app/src/main/res/layout/remainder_to_delete_conversation.xml
  app/src/main/res/values/strings.xml
Labels: 3. to review

#5022 avoid duplicate messages
  app/schemas/com.nextcloud.talk.data.source.local.TalkDatabase/17.json
  app/src/main/java/com/nextcloud/talk/adapters/messages/OutcomingTextMessageViewHolder.kt
  app/src/main/java/com/nextcloud/talk/chat/MessageInputFragment.kt
  app/src/main/java/com/nextcloud/talk/chat/data/ChatMessageRepository.kt
  app/src/main/java/com/nextcloud/talk/chat/data/model/ChatMessage.kt
  app/src/main/java/com/nextcloud/talk/chat/data/network/OfflineFirstChatRepository.kt
  app/src/main/java/com/nextcloud/talk/chat/viewmodels/MessageInputViewModel.kt
  app/src/main/java/com/nextcloud/talk/data/database/dao/ChatMessagesDao.kt
  app/src/main/java/com/nextcloud/talk/data/database/mappers/ChatMessageMapUtils.kt
  app/src/main/java/com/nextcloud/talk/data/database/model/ChatMessageEntity.kt
  app/src/main/java/com/nextcloud/talk/data/database/model/SendStatus.kt
  app/src/main/java/com/nextcloud/talk/data/source/local/Migrations.kt
  app/src/main/java/com/nextcloud/talk/data/source/local/TalkDatabase.kt
  app/src/main/java/com/nextcloud/talk/data/source/local/converters/SendStatusConverter.kt
  app/src/main/java/com/nextcloud/talk/ui/dialog/TempMessageActionsDialog.kt
  app/src/main/java/com/nextcloud/talk/utils/preview/ComposePreviewUtilsDaos.kt
Labels: 3. to review

#5074 fix crash in call view
  app/src/main/java/com/nextcloud/talk/call/components/ParticipantGrid.kt
  app/src/main/java/com/nextcloud/talk/call/components/ParticipantTile.kt
Labels: 3. to review, backport-request

#5094 update verification metadata
  gradle/verification-keyring.keys
  gradle/verification-metadata.xml
Labels: 3. to review
