Repository nextcloud/talk-android, pull requests merged in 2025-02, with the labels that each got.

#4667 Bugfix/4492/fix missing users in UI
  app/src/main/java/com/nextcloud/talk/data/user/UsersRepositoryImpl.kt
  app/src/main/java/com/nextcloud/talk/users/UserManager.kt
Labels: 3. to review, backport-request

#4680 chore(CI): Updating pr-feedback.yml workflow from template
  .github/workflows/pr-feedback.yml
Labels: dependencies

#4658 Set limit on conversation description length
  app/src/main/java/com/nextcloud/talk/conversationcreation/ConversationCreationActivity.kt
  app/src/main/java/com/nextcloud/talk/conversationinfoedit/ConversationInfoEditActivity.kt
  app/src/main/java/com/nextcloud/talk/utils/CapabilitiesUtil.kt
  app/src/main/res/layout/activity_conversation_info_edit.xml
Labels: 3. to review, backport-request

#4674 Fixing and improving main search
  .idea/inspectionProfiles/ktlint.xml
  app/src/main/java/com/nextcloud/talk/adapters/items/ContactItem.kt
  app/src/main/java/com/nextcloud/talk/adapters/items/FlexibleItemViewType.kt
  app/src/main/java/com/nextcloud/talk/contacts/ContactsRepository.kt
  app/src/main/java/com/nextcloud/talk/contacts/ContactsRepositoryImpl.kt
  app/src/main/java/com/nextcloud/talk/contacts/ContactsViewModel.kt
  app/src/main/java/com/nextcloud/talk/conversationlist/ConversationsListActivity.kt
  app/src/test/java/com/nextcloud/talk/contacts/repository/FakeRepositoryError.kt
  app/src/test/java/com/nextcloud/talk/contacts/repository/FakeRepositorySuccess.kt
Labels: 3. to review

#4678 Team mentions
  app/src/main/java/com/nextcloud/talk/adapters/items/MentionAutocompleteItem.kt
  app/src/main/java/com/nextcloud/talk/adapters/items/ParticipantItem.kt
  app/src/main/java/com/nextcloud/talk/chat/MessageInputFragment.kt
  app/src/main/java/com/nextcloud/talk/extensions/ImageViewExtensions.kt
  app/src/main/java/com/nextcloud/talk/models/json/chat/ChatUtils.kt
  app/src/main/java/com/nextcloud/talk/utils/DisplayUtils.kt
  app/src/main/java/com/nextcloud/talk/utils/message/MessageUtils.kt
  app/src/main/res/drawable-night/icon_team.xml
  app/src/main/res/drawable/icon_team.xml
  detekt.yml
Labels: 3. to review, backport-request

#4722 Message count is an Int hence use 'd' not 's' as formatting character
  app/src/main/res/values/strings.xml
Labels: backport-request

#4725 fix(lint): Use plurals string instead of simple string
  app/src/main/java/com/nextcloud/talk/adapters/messages/SystemMessageViewHolder.kt
  app/src/main/res/values/strings.xml
  scripts/analysis/lint-results.txt
Labels: 3. to review, technical debt, backport-request

#4728 fix(deps): update kotlin monorepo to v2.1.10
  build.gradle
  gradle/verification-metadata.xml
Labels: 3. to review, dependencies

#4710 No longer does edit button overlap the recordAudioButton
  app/src/main/java/com/nextcloud/talk/chat/MessageInputFragment.kt
Labels: 3. to review, backport-request

#4734 Avoid duplicated messages when activity comes back from background
  app/src/main/java/com/nextcloud/talk/chat/ChatActivity.kt
Labels: 3. to review, backport-request

#4729 Make link clickable
  app/src/main/java/com/nextcloud/talk/adapters/messages/SystemMessageViewHolder.kt
  app/src/main/java/com/nextcloud/talk/models/json/chat/ChatUtils.kt
Labels: 3. to review, backport-request

#4739 check if scope is initialized before canceling
  app/src/main/java/com/nextcloud/talk/chat/data/network/OfflineFirstChatRepository.kt
Labels: 3. to review, backport-request

#4738 init other data earlier than ConversationModel
  app/src/main/java/com/nextcloud/talk/chat/ChatActivity.kt
  app/src/main/java/com/nextcloud/talk/chat/data/ChatMessageRepository.kt
  app/src/main/java/com/nextcloud/talk/chat/data/network/OfflineFirstChatRepository.kt
  app/src/main/java/com/nextcloud/talk/chat/viewmodels/ChatViewModel.kt
Labels: 3. to review, backport-request

#4746 ContactsScreen: extract Composables to files and simplify passed parameters
  app/src/main/java/com/nextcloud/talk/contacts/ContactsActivityCompose.kt
  app/src/main/java/com/nextcloud/talk/contacts/ContactsScreen.kt
  app/src/main/java/com/nextcloud/talk/contacts/ContactsViewModel.kt
  app/src/main/java/com/nextcloud/talk/contacts/SearchComponent.kt
  app/src/main/java/com/nextcloud/talk/contacts/components/AppBar.kt
  app/src/main/java/com/nextcloud/talk/contacts/components/ContactItemRow.kt
  app/src/main/java/com/nextcloud/talk/contacts/components/ContactsItem.kt
  app/src/main/java/com/nextcloud/talk/contacts/components/ContactsList.kt
  app/src/main/java/com/nextcloud/talk/contacts/components/ConversationCreationOptions.kt
  app/src/main/java/com/nextcloud/talk/contacts/components/Header.kt
  app/src/main/java/com/nextcloud/talk/contacts/components/SearchComponent.kt
  app/src/main/java/com/nextcloud/talk/contacts/components/SetStatusBarColor.kt
Labels: 3. to review

#4748 avoid Npe for adapter in ConversationsListActivity
  app/src/main/java/com/nextcloud/talk/conversationlist/ConversationsListActivity.kt
Labels: 3. to review
