Repository nextcloud/talk-android, pull requests merged in 2025-07, with the labels that each got.

#5099 Show delete all messages in 1:1 only when canDeleteConversation is true
  app/src/main/java/com/nextcloud/talk/conversationinfo/ConversationInfoActivity.kt
Labels: 3. to review, backport-request

#5119 bump jackson core version
  app/build.gradle
  renovate.json5
Labels: 3. to review, backport-request

#5124 Crash fix
  app/src/main/java/com/nextcloud/talk/conversationlist/ConversationsListActivity.kt
Labels: 3. to review, backport-request

#5127 fix that contact in search is clickable
  app/src/main/java/com/nextcloud/talk/adapters/items/ContactItem.kt
  app/src/main/java/com/nextcloud/talk/adapters/items/FlexibleItemViewType.kt
  app/src/main/java/com/nextcloud/talk/conversationlist/ConversationsListActivity.kt
  app/src/main/java/com/nextcloud/talk/messagesearch/MessageSearchActivity.kt
Labels: 3. to review, backport-request

#5110 Scale DatePicker for smaller screens
  app/src/main/java/com/nextcloud/talk/ui/dialog/DateTimeCompose.kt
Labels: 3. to review, backport-request

#5142 🎨 Update searchbar to m3 theming
  app/src/main/java/com/nextcloud/talk/conversationlist/ConversationsListActivity.kt
Labels: design, 3. to review

#5100 Login flow v2
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/nextcloud/talk/account/AccountVerificationActivity.kt
  app/src/main/java/com/nextcloud/talk/account/BrowserLoginActivity.kt
  app/src/main/java/com/nextcloud/talk/account/ServerSelectionActivity.kt
  app/src/main/java/com/nextcloud/talk/account/WebViewLoginActivity.kt
  app/src/main/java/com/nextcloud/talk/activities/BaseActivity.kt
  app/src/main/java/com/nextcloud/talk/activities/MainActivity.kt
  app/src/main/java/com/nextcloud/talk/conversationlist/ConversationsListActivity.kt
  app/src/main/res/layout/activity_web_view_login.xml
  app/src/main/res/values/strings.xml
  gradle/verification-metadata.xml
Labels: 3. to review

#5117 Bug in user status dialog
  app/src/main/java/com/nextcloud/talk/ui/dialog/SetStatusDialogFragment.kt
Labels: 3. to review

#5139 reduce avatar size for group and all mentions
  app/src/main/java/com/nextcloud/talk/adapters/items/MentionAutocompleteItem.kt
  app/src/main/java/com/nextcloud/talk/utils/DisplayUtils.kt
  app/src/main/res/drawable-night/ic_circular_group_mentions.xml
  app/src/main/res/drawable-night/icon_circular_team.xml
  app/src/main/res/drawable/ic_avatar_group_small.xml
  app/src/main/res/drawable/ic_avatar_team_small.xml
  app/src/main/res/drawable/ic_circular_group_mentions.xml
  app/src/main/res/drawable/icon_circular_team.xml
  gradle/verification-keyring.keys
Labels: 3. to review

#5161 avoid NPE crash in conversation list
  app/src/main/java/com/nextcloud/talk/conversationlist/ConversationsListActivity.kt
Labels: 3. to review

#5067 Message threads
  app/schemas/com.nextcloud.talk.data.source.local.TalkDatabase/18.json
  app/src/androidTest/java/com/nextcloud/talk/data/database/dao/ChatBlocksDaoTest.kt
  app/src/androidTest/java/com/nextcloud/talk/data/database/dao/ChatMessagesDaoTest.kt
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/nextcloud/talk/adapters/messages/IncomingTextMessageViewHolder.kt
  app/src/main/java/com/nextcloud/talk/adapters/messages/OutcomingTextMessageViewHolder.kt
  app/src/main/java/com/nextcloud/talk/api/NcApiCoroutines.kt
  app/src/main/java/com/nextcloud/talk/chat/ChatActivity.kt
  app/src/main/java/com/nextcloud/talk/chat/MessageInputFragment.kt
  app/src/main/java/com/nextcloud/talk/chat/data/ChatMessageRepository.kt
  app/src/main/java/com/nextcloud/talk/chat/data/model/ChatMessage.kt
  app/src/main/java/com/nextcloud/talk/chat/data/network/ChatNetworkDataSource.kt
  app/src/main/java/com/nextcloud/talk/chat/data/network/OfflineFirstChatRepository.kt
  app/src/main/java/com/nextcloud/talk/chat/data/network/RetrofitChatNetwork.kt
  app/src/main/java/com/nextcloud/talk/chat/viewmodels/ChatViewModel.kt
  app/src/main/java/com/nextcloud/talk/components/StandardAppBar.kt
  app/src/main/java/com/nextcloud/talk/dagger/modules/RepositoryModule.kt
  app/src/main/java/com/nextcloud/talk/dagger/modules/ViewModelModule.kt
  app/src/main/java/com/nextcloud/talk/data/database/dao/ChatBlocksDao.kt
  app/src/main/java/com/nextcloud/talk/data/database/dao/ChatMessagesDao.kt
  app/src/main/java/com/nextcloud/talk/data/database/mappers/ChatMessageMapUtils.kt
  app/src/main/java/com/nextcloud/talk/data/database/model/ChatBlockEntity.kt
  app/src/main/java/com/nextcloud/talk/data/database/model/ChatMessageEntity.kt
  app/src/main/java/com/nextcloud/talk/data/source/local/Migrations.kt
  app/src/main/java/com/nextcloud/talk/data/source/local/TalkDatabase.kt
  app/src/main/java/com/nextcloud/talk/models/json/chat/ChatMessageJson.kt
  app/src/main/java/com/nextcloud/talk/models/json/converters/EnumSystemMessageTypeConverter.kt
  app/src/main/java/com/nextcloud/talk/models/json/threads/Thread.kt
  app/src/main/java/com/nextcloud/talk/models/json/threads/ThreadAttendee.kt
  app/src/main/java/com/nextcloud/talk/models/json/threads/ThreadInfo.kt
  app/src/main/java/com/nextcloud/talk/models/json/threads/ThreadOCS.kt
  app/src/main/java/com/nextcloud/talk/models/json/threads/ThreadOverall.kt
  app/src/main/java/com/nextcloud/talk/models/json/threads/ThreadsOCS.kt
  app/src/main/java/com/nextcloud/talk/models/json/threads/ThreadsOverall.kt
  app/src/main/java/com/nextcloud/talk/repositories/reactions/ReactionsRepositoryImpl.kt
  app/src/main/java/com/nextcloud/talk/threadsoverview/ThreadsOverviewActivity.kt
  app/src/main/java/com/nextcloud/talk/threadsoverview/components/ThreadRow.kt
  app/src/main/java/com/nextcloud/talk/threadsoverview/data/ThreadsRepository.kt
  app/src/main/java/com/nextcloud/talk/threadsoverview/data/ThreadsRepositoryImpl.kt
  app/src/main/java/com/nextcloud/talk/threadsoverview/viewmodels/ThreadsOverviewViewModel.kt
  app/src/main/java/com/nextcloud/talk/ui/dialog/MessageActionsDialog.kt
  app/src/main/java/com/nextcloud/talk/utils/ApiUtils.kt
  app/src/main/java/com/nextcloud/talk/utils/bundle/BundleKeys.kt
  app/src/main/java/com/nextcloud/talk/utils/preview/ComposePreviewUtils.kt
  app/src/main/java/com/nextcloud/talk/utils/preview/ComposePreviewUtilsDaos.kt
  app/src/main/res/drawable/outline_forum_24.xml
  app/src/main/res/layout/dialog_message_actions.xml
  app/src/main/res/layout/item_custom_incoming_text_message.xml
  app/src/main/res/menu/menu_conversation.xml
  app/src/main/res/values/strings.xml
Labels: 2. developing

#5175 fix crash for DB migration after upgrade to v22.0.0 Alpha 11 / Alpha 12
  app/schemas/com.nextcloud.talk.data.source.local.TalkDatabase/19.json
  app/src/main/java/com/nextcloud/talk/data/source/local/Migrations.kt
  app/src/main/java/com/nextcloud/talk/data/source/local/TalkDatabase.kt
  scripts/analysis/lint-results.txt
Labels: 3. to review

#5187 hide thread messages in normal chat / include threadId in fieldMap ...
  app/src/androidTest/java/com/nextcloud/talk/data/database/dao/ChatBlocksDaoTest.kt
  app/src/main/java/com/nextcloud/talk/adapters/messages/IncomingTextMessageViewHolder.kt
  app/src/main/java/com/nextcloud/talk/adapters/messages/OutcomingTextMessageViewHolder.kt
  app/src/main/java/com/nextcloud/talk/chat/ChatActivity.kt
  app/src/main/java/com/nextcloud/talk/chat/MessageInputFragment.kt
  app/src/main/java/com/nextcloud/talk/chat/data/network/OfflineFirstChatRepository.kt
  app/src/main/java/com/nextcloud/talk/threadsoverview/ThreadsOverviewActivity.kt
  app/src/main/java/com/nextcloud/talk/ui/dialog/MessageActionsDialog.kt
Labels: 3. to review

#5189 Fixed Login V2 Bug
  app/src/androidTest/java/com/nextcloud/talk/data/database/dao/ChatBlocksDaoTest.kt
  app/src/main/java/com/nextcloud/talk/account/BrowserLoginActivity.kt
Labels: 3. to review

#5197 Read status/Typing status setting is misconfigured
  app/src/main/java/com/nextcloud/talk/settings/SettingsActivity.kt
Labels: 3. to review

#5188 answer with files
  app/src/main/java/com/nextcloud/talk/adapters/messages/IncomingDeckCardViewHolder.kt
  app/src/main/java/com/nextcloud/talk/adapters/messages/IncomingLinkPreviewMessageViewHolder.kt
  app/src/main/java/com/nextcloud/talk/adapters/messages/IncomingLocationMessageViewHolder.kt
  app/src/main/java/com/nextcloud/talk/adapters/messages/IncomingPollMessageViewHolder.kt
  app/src/main/java/com/nextcloud/talk/adapters/messages/IncomingVoiceMessageViewHolder.kt
  app/src/main/java/com/nextcloud/talk/adapters/messages/OutcomingDeckCardViewHolder.kt
  app/src/main/java/com/nextcloud/talk/adapters/messages/OutcomingLinkPreviewMessageViewHolder.kt
  app/src/main/java/com/nextcloud/talk/adapters/messages/OutcomingLocationMessageViewHolder.kt
  app/src/main/java/com/nextcloud/talk/adapters/messages/OutcomingPollMessageViewHolder.kt
  app/src/main/java/com/nextcloud/talk/adapters/messages/OutcomingVoiceMessageViewHolder.kt
  app/src/main/java/com/nextcloud/talk/chat/ChatActivity.kt
  app/src/main/java/com/nextcloud/talk/chat/MessageInputFragment.kt
  app/src/main/java/com/nextcloud/talk/chat/MessageInputVoiceRecordingFragment.kt
  app/src/main/java/com/nextcloud/talk/chat/data/network/OfflineFirstChatRepository.kt
  app/src/main/java/com/nextcloud/talk/chat/viewmodels/ChatViewModel.kt
  app/src/main/java/com/nextcloud/talk/chat/viewmodels/MessageInputViewModel.kt
Labels: 3. to review
