Repository nextcloud/talk-android, pull requests merged in 2025-04, with the labels that each got.

#4829 Add new photo picker
  app/src/main/java/com/nextcloud/talk/chat/ChatActivity.kt
  app/src/main/java/com/nextcloud/talk/chat/MessageInputFragment.kt
  app/src/main/java/com/nextcloud/talk/jobs/UploadAndShareFilesWorker.kt
  app/src/main/java/com/nextcloud/talk/ui/dialog/AttachmentDialog.kt
  app/src/main/java/com/nextcloud/talk/ui/dialog/FileAttachmentPreviewFragment.kt
  app/src/main/res/drawable/baseline_photo_library_24.xml
  app/src/main/res/layout/dialog_attachment.xml
  app/src/main/res/values/strings.xml
Labels: 3. to review

#4834 chore(deps): Update dependency com.android.tools.build:gradle to v8.9.1
  build.gradle
  gradle/verification-metadata.xml
Labels: 3. to review, dependencies

#4747 Edit checkbox messages directly
  app/src/main/java/com/nextcloud/talk/adapters/messages/IncomingTextMessageViewHolder.kt
  app/src/main/java/com/nextcloud/talk/adapters/messages/OutcomingTextMessageViewHolder.kt
  app/src/main/java/com/nextcloud/talk/utils/message/MessageUtils.kt
  app/src/main/res/layout/item_custom_incoming_text_message.xml
  app/src/main/res/layout/item_custom_outcoming_text_message.xml
Labels: 3. to review

#4838 switch video capture between 4:3 and 16:9 ratio for portrait/landscape
  app/src/main/java/com/nextcloud/talk/activities/CallActivity.kt
  app/src/main/res/layout/call_activity.xml
  app/src/main/res/values/dimens.xml
Labels: 3. to review

#4812 fix duplicate messages because of multiple scopes
  app/src/main/java/com/nextcloud/talk/chat/data/network/OfflineFirstChatRepository.kt
Labels: 3. to review

#4867 Avoid Npe in sendChatMessage
  app/src/main/java/com/nextcloud/talk/chat/data/network/OfflineFirstChatRepository.kt
Labels: 3. to review, backport-request

#4871 add hotfix to avoid NoSupportedApiException in ContactsRepositoryImpl
  app/src/main/java/com/nextcloud/talk/contacts/ContactsRepositoryImpl.kt
  app/src/main/java/com/nextcloud/talk/data/user/model/User.kt
Labels: 3. to review, backport-request

#4875 update changelog
  CHANGELOG.md
Labels: 3. to review

#4882 show full open conversation list when search text is empty
  app/src/main/java/com/nextcloud/talk/openconversations/ListOpenConversationsActivity.kt
Labels: 3. to review

#4647 Improving search for chat messages
  .idea/inspectionProfiles/ktlint.xml
  app/src/main/java/com/nextcloud/talk/api/NcApiCoroutines.kt
  app/src/main/java/com/nextcloud/talk/chat/data/network/ChatNetworkDataSource.kt
  app/src/main/java/com/nextcloud/talk/chat/data/network/RetrofitChatNetwork.kt
  app/src/main/java/com/nextcloud/talk/chat/viewmodels/ChatViewModel.kt
  app/src/main/java/com/nextcloud/talk/contacts/ImageRequest.kt
  app/src/main/java/com/nextcloud/talk/conversationlist/ConversationsListActivity.kt
  app/src/main/java/com/nextcloud/talk/jobs/AccountRemovalWorker.java
  app/src/main/java/com/nextcloud/talk/jobs/CapabilitiesWorker.java
  app/src/main/java/com/nextcloud/talk/ui/ComposeChatAdapter.kt
  app/src/main/java/com/nextcloud/talk/ui/dialog/ContextChatCompose.kt
  app/src/main/java/com/nextcloud/talk/utils/ApiUtils.kt
  app/src/main/java/com/nextcloud/talk/utils/message/MessageUtils.kt
  app/src/main/res/layout/activity_conversations.xml
Labels: 2. developing

#4826 Feature/4712/add participant to1to1
  app/src/main/java/com/nextcloud/talk/activities/MainActivity.kt
  app/src/main/java/com/nextcloud/talk/api/NcApiCoroutines.kt
  app/src/main/java/com/nextcloud/talk/chat/ChatActivity.kt
  app/src/main/java/com/nextcloud/talk/contacts/ContactsRepositoryImpl.kt
  app/src/main/java/com/nextcloud/talk/conversation/CreateConversationDialogFragment.kt
  app/src/main/java/com/nextcloud/talk/conversation/repository/ConversationRepository.kt
  app/src/main/java/com/nextcloud/talk/conversation/repository/ConversationRepositoryImpl.kt
  app/src/main/java/com/nextcloud/talk/conversation/viewmodel/ConversationViewModel.kt
  app/src/main/java/com/nextcloud/talk/conversationcreation/ConversationCreationRepositoryImpl.kt
  app/src/main/java/com/nextcloud/talk/conversationcreation/ConversationCreationViewModel.kt
  app/src/main/java/com/nextcloud/talk/conversationinfo/ConversationInfoActivity.kt
  app/src/main/java/com/nextcloud/talk/conversationinfo/CreateRoomRequest.kt
  app/src/main/java/com/nextcloud/talk/conversationinfo/Participants.kt
  app/src/main/java/com/nextcloud/talk/conversationinfo/viewmodel/ConversationInfoViewModel.kt
  app/src/main/java/com/nextcloud/talk/dagger/modules/RepositoryModule.kt
  app/src/main/java/com/nextcloud/talk/dagger/modules/ViewModelModule.kt
  app/src/main/java/com/nextcloud/talk/jobs/AddParticipantsToConversationWorker.java
  app/src/main/java/com/nextcloud/talk/repositories/conversations/ConversationsRepository.kt
  app/src/main/java/com/nextcloud/talk/repositories/conversations/ConversationsRepositoryImpl.kt
  app/src/main/java/com/nextcloud/talk/ui/bottom/sheet/ProfileBottomSheet.kt
  app/src/main/java/com/nextcloud/talk/utils/ApiUtils.kt
  app/src/main/java/com/nextcloud/talk/utils/CapabilitiesUtil.kt
  app/src/main/res/layout/activity_conversation_info.xml
  app/src/test/java/com/nextcloud/talk/conversationinfo/viewmodel/ConversationInfoViewModelTest.kt
Labels: 3. to review

#4828 Modify some strings
  app/src/main/res/values/strings.xml
Labels: 3. to review

#4830 Test notifications
  app/src/main/java/com/nextcloud/talk/api/NcApiCoroutines.kt
  app/src/main/java/com/nextcloud/talk/dagger/modules/ViewModelModule.kt
  app/src/main/java/com/nextcloud/talk/diagnose/DiagnoseActivity.kt
  app/src/main/java/com/nextcloud/talk/diagnose/DiagnoseContentComposable.kt
  app/src/main/java/com/nextcloud/talk/diagnose/DiagnoseViewModel.kt
  app/src/main/java/com/nextcloud/talk/models/json/testNotification/TestNotificationData.kt
  app/src/main/java/com/nextcloud/talk/models/json/testNotification/TestNotificationOCS.kt
  app/src/main/java/com/nextcloud/talk/models/json/testNotification/TestNotificationOverall.kt
  app/src/main/java/com/nextcloud/talk/utils/ApiUtils.kt
  app/src/main/res/values/strings.xml
Labels: 3. to review

#4934 fix(translation): Remove leading quote, trailing space and line break…
  app/src/main/res/values/strings.xml
Labels: 3. to review

#4890 fix Conscrypt initialization order
  app/src/main/java/com/nextcloud/talk/application/NextcloudTalkApplication.kt
Labels: 3. to review
